// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Yojson from "../../../../belenios_compat_melange/yojson.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Belenios_v1__Group from "./group.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_v1__Mixnet from "./mixnet.js";
import * as Belenios_core__Common from "../core/common.js";
import * as Belenios_v1__Trustees from "./trustees.js";
import * as Belenios_core__Question from "../core/question.js";
import * as Belenios_v1__Question_h from "./question_h.js";
import * as Belenios_v1__Question_nh from "./question_nh.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";
import * as Belenios_v1__Serializable_j from "./serializable_j.js";

function of_string(x) {
  var params = Belenios_v1__Serializable_j.params_of_string(Yojson.Safe.read_json, x);
  return {
          e_version: 1,
          e_description: params.e_description,
          e_name: params.e_name,
          e_questions: params.e_questions,
          e_uuid: params.e_uuid,
          e_administrator: params.e_administrator,
          e_credential_authority: params.e_credential_authority
        };
}

function to_string(params, group, public_key) {
  var G = Belenios_v1__Group.of_string(group);
  var e_public_key = Curry._1(G.of_string, public_key);
  var params_e_description = params.e_description;
  var params_e_name = params.e_name;
  var params_e_questions = params.e_questions;
  var params_e_uuid = params.e_uuid;
  var params_e_administrator = params.e_administrator;
  var params_e_credential_authority = params.e_credential_authority;
  var params$1 = {
    e_version: 1,
    e_description: params_e_description,
    e_name: params_e_name,
    e_group: group,
    e_public_key: e_public_key,
    e_questions: params_e_questions,
    e_uuid: params_e_uuid,
    e_administrator: params_e_administrator,
    e_credential_authority: params_e_credential_authority
  };
  return Belenios_v1__Serializable_j.string_of_params((function (param) {
                return Belenios_core__Common.swrite(G.to_string, param);
              }), params$1);
}

function Make(funarg, funarg$1, funarg$2, funarg$3) {
  var j = Belenios_v1__Serializable_j.params_of_string(Yojson.Safe.read_json, funarg$1.raw_election);
  var G = Belenios_v1__Group.of_string(j.e_group);
  var params = Belenios_v1__Serializable_j.params_of_string((function (param) {
          return Belenios_core__Common.sread(G.of_string, param);
        }), funarg$1.raw_election);
  var e_uuid = params.e_uuid;
  var e_questions = params.e_questions;
  var election_e_description = params.e_description;
  var election_e_name = params.e_name;
  var election_e_administrator = params.e_administrator;
  var election_e_credential_authority = params.e_credential_authority;
  var election = {
    e_version: 1,
    e_description: election_e_description,
    e_name: election_e_name,
    e_questions: e_questions,
    e_uuid: e_uuid,
    e_administrator: election_e_administrator,
    e_credential_authority: election_e_credential_authority
  };
  var fingerprint = Belenios_core__Common.sha256_b64(funarg$1.raw_election);
  var public_key = params.e_public_key;
  var S = Belenios_core__Question.compute_signature(Curry._1(Belenios_core__Common_types.$$Array.to_list, e_questions));
  var string_of_ballot = function (x) {
    return Belenios_v1__Serializable_j.string_of_ballot((function (param) {
                  return Belenios_core__Common.swrite(G.to_string, param);
                }), x);
  };
  var ballot_of_string = function (x) {
    return Belenios_v1__Serializable_j.ballot_of_string((function (param) {
                  return Belenios_core__Common.sread(G.of_string, param);
                }), x);
  };
  var get_credential = function (x) {
    return Caml_option.some(x.credential);
  };
  var include = Curry._1(funarg, {
        G: G,
        election: election,
        fingerprint: fingerprint,
        public_key: public_key,
        S: S,
        string_of_ballot: string_of_ballot,
        ballot_of_string: ballot_of_string,
        get_credential: get_credential
      });
  var write_result = include.write_result;
  var read_result = include.read_result;
  var W = {
    G: G,
    election: election,
    fingerprint: fingerprint,
    public_key: public_key,
    S: S,
    string_of_ballot: string_of_ballot,
    ballot_of_string: ballot_of_string,
    get_credential: get_credential,
    write_result: write_result,
    read_result: read_result
  };
  var Q = Belenios_core__Question.Make(funarg$2, G, Belenios_v1__Question_h.Make(funarg$2, G), Belenios_v1__Question_nh.Make(funarg$2, G));
  var Mix = Belenios_v1__Mixnet.Make(W, funarg$2);
  var fs_prove = function (gs, x, oracle) {
    var w = Curry._1(funarg$2.random, G.q);
    var commitments = Curry._2(Belenios_core__Common_types.$$Array.map, (function (g) {
            return Curry._2(G.$star$star$tilde, g, w);
          }), gs);
    var challenge = Curry._1(oracle, commitments);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(x, challenge)), G.q);
    return {
            challenge: challenge,
            response: response
          };
  };
  var swap = function (xs) {
    var _i = xs.length - 1 | 0;
    var _accu = /* [] */0;
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i < 0) {
        return Curry._1(Belenios_core__Common_types.$$Array.of_list, accu);
      }
      var x = Caml_array.get(xs, i);
      _accu = {
        hd: x,
        tl: accu
      };
      _i = i - 1 | 0;
      continue ;
    };
  };
  var make_sig_prefix = function (hash) {
    return "sig|" + (hash + "|");
  };
  var create_ballot = function (sk, m) {
    var credential = Curry._2(G.$star$star$tilde, G.g, sk);
    var zkp = fingerprint + ("|" + Curry._1(G.to_string, credential));
    var answers = swap(Curry._3(Belenios_core__Common_types.$$Array.map2, (function (param, param$1) {
                return Curry._4(Q.create_answer, param, public_key, zkp, param$1);
              }), e_questions, m));
    var ballot_without_signature = {
      election_uuid: e_uuid,
      election_hash: fingerprint,
      credential: credential,
      answers: answers,
      signature: undefined
    };
    var s_hash = Belenios_core__Common.sha256_b64(Belenios_v1__Serializable_j.string_of_ballot((function (param) {
                return Belenios_core__Common.swrite(G.to_string, param);
              }), ballot_without_signature));
    var w = Curry._1(funarg$2.random, G.q);
    var commitment = Curry._2(G.$star$star$tilde, G.g, w);
    var prefix = make_sig_prefix(s_hash);
    var challenge = Curry._2(G.hash, prefix, [commitment]);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(sk, challenge)), G.q);
    var s_proof = {
      challenge: challenge,
      response: response
    };
    var signature = {
      s_hash: s_hash,
      s_proof: s_proof
    };
    return {
            election_uuid: e_uuid,
            election_hash: fingerprint,
            credential: credential,
            answers: answers,
            signature: signature
          };
  };
  var check_ballot = function (param) {
    var signature = param.signature;
    var answers = param.answers;
    var credential = param.credential;
    var election_hash = param.election_hash;
    var election_uuid = param.election_uuid;
    var ballot_without_signature = {
      election_uuid: election_uuid,
      election_hash: election_hash,
      credential: credential,
      answers: answers,
      signature: undefined
    };
    var expected_hash = Belenios_core__Common.sha256_b64(Belenios_v1__Serializable_j.string_of_ballot((function (param) {
                return Belenios_core__Common.swrite(G.to_string, param);
              }), ballot_without_signature));
    var zkp = fingerprint + ("|" + Curry._1(G.to_string, credential));
    if (!Caml_obj.caml_equal(election_uuid, e_uuid)) {
      return false;
    }
    if (election_hash !== fingerprint) {
      return false;
    }
    var tmp;
    if (signature !== undefined) {
      var match = signature.s_proof;
      var response = match.response;
      var challenge = match.challenge;
      var s_hash = signature.s_hash;
      if (s_hash === expected_hash) {
        var tmp$1 = false;
        if (Curry._1(G.check, credential)) {
          var tmp$2 = false;
          if (Belenios_core__Common.check_modulo(G.q, challenge)) {
            var tmp$3 = false;
            if (Belenios_core__Common.check_modulo(G.q, response)) {
              var commitment = Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, response), Curry._2(G.$star$star$tilde, credential, challenge));
              var prefix = make_sig_prefix(s_hash);
              tmp$3 = Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(G.hash, prefix, [commitment]));
            }
            tmp$2 = tmp$3;
          }
          tmp$1 = tmp$2;
        }
        tmp = tmp$1;
      } else {
        tmp = false;
      }
    } else {
      tmp = false;
    }
    if (tmp) {
      return Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (param, param$1) {
                    return Curry._4(Q.verify_answer, param, public_key, zkp, param$1);
                  }), e_questions, answers);
    } else {
      return false;
    }
  };
  var check_rawballot = function (rawballot) {
    var ballot;
    try {
      ballot = Belenios_v1__Serializable_j.ballot_of_string((function (param) {
              return Belenios_core__Common.sread(G.of_string, param);
            }), rawballot);
    }
    catch (raw_e){
      var e = Caml_js_exceptions.internalToOCamlException(raw_e);
      return {
              TAG: /* Error */1,
              _0: {
                NAME: "SerializationError",
                VAL: e
              }
            };
    }
    if (Belenios_v1__Serializable_j.string_of_ballot((function (param) {
              return Belenios_core__Common.swrite(G.to_string, param);
            }), ballot) === rawballot) {
      return {
              TAG: /* Ok */0,
              _0: {
                rc_credential: Curry._1(G.to_string, ballot.credential),
                rc_check: (function (param) {
                    return check_ballot(ballot);
                  })
              }
            };
    } else {
      return {
              TAG: /* Error */1,
              _0: "NonCanonical"
            };
    }
  };
  var process_ballots = function (bs) {
    return {
            NAME: "Array",
            VAL: Curry._2(Belenios_core__Common_types.$$Array.mapi, (function (i, q) {
                    return Curry._2(Q.process_ciphertexts, q, Curry._2(Belenios_core__Common.List.map, (function (param) {
                                      return [
                                              param[0],
                                              Curry._2(Q.extract_ciphertexts, q, Caml_array.get(param[1].answers, i))
                                            ];
                                    }), bs));
                  }), e_questions)
          };
  };
  var extract_nh_ciphertexts = function (x) {
    var x$1 = Belenios_core__Common_types.Shape.to_shape_array(x);
    var _i = x$1.length - 1 | 0;
    var _accu = /* [] */0;
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i < 0) {
        return Curry._1(Belenios_core__Common_types.$$Array.of_list, accu);
      }
      var match = Caml_array.get(e_questions, i);
      if (match.TAG === /* Homomorphic */0) {
        _i = i - 1 | 0;
        continue ;
      }
      _accu = {
        hd: Belenios_core__Common_types.Shape.to_array(Caml_array.get(x$1, i)),
        tl: accu
      };
      _i = i - 1 | 0;
      continue ;
    };
  };
  var merge_nh_ciphertexts = function (cc, x) {
    var x$1 = Curry._1(Belenios_core__Common_types.$$Array.copy, Belenios_core__Common_types.Shape.to_shape_array(x));
    var n = x$1.length;
    var m = cc.length;
    var _i = 0;
    var _j = 0;
    while(true) {
      var j = _j;
      var i = _i;
      if (i < n && j < m) {
        var match = Caml_array.get(e_questions, i);
        if (match.TAG === /* Homomorphic */0) {
          _i = i + 1 | 0;
          continue ;
        }
        Caml_array.set(x$1, i, Belenios_core__Common_types.Shape.of_array(Caml_array.get(cc, j)));
        _j = j + 1 | 0;
        _i = i + 1 | 0;
        continue ;
      }
      if (j !== m) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "election.ml",
                252,
                8
              ],
              Error: new Error()
            };
      }
      return {
              NAME: "Array",
              VAL: x$1
            };
    };
  };
  var shuffle_ciphertexts = function (cc) {
    var _i = cc.length - 1 | 0;
    var _accu = /* [] */0;
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i >= 0) {
        var c = Caml_array.get(cc, i);
        var match = Curry._2(Mix.gen_shuffle, public_key, c);
        var c$p = match[0];
        var pi = Curry._5(Mix.gen_shuffle_proof, public_key, c, c$p, match[1], match[2]);
        _accu = {
          hd: [
            c$p,
            pi
          ],
          tl: accu
        };
        _i = i - 1 | 0;
        continue ;
      }
      var match$1 = Curry._1(Belenios_core__Common_types.$$Array.split, Curry._1(Belenios_core__Common_types.$$Array.of_list, accu));
      return {
              shuffle_ciphertexts: match$1[0],
              shuffle_proofs: match$1[1]
            };
    };
  };
  var check_shuffle = function (cc, s) {
    return Belenios_core__Common_types.$$Array.for_all3(Curry._1(Mix.check_shuffle_proof, public_key), cc, s.shuffle_ciphertexts, s.shuffle_proofs);
  };
  var check_ciphertext = function (c) {
    return Belenios_core__Common_types.Shape.forall((function (param) {
                  if (Curry._1(G.check, param.alpha)) {
                    return Curry._1(G.check, param.beta);
                  } else {
                    return false;
                  }
                }), c);
  };
  var compute_factor = function (c, x) {
    if (!check_ciphertext(c)) {
      return Stdlib.invalid_arg("Invalid ciphertext");
    }
    var res = Belenios_core__Common_types.Shape.map((function (param) {
            var alpha = param.alpha;
            var zkp = "decrypt|" + (fingerprint + ("|" + (Curry._1(G.to_string, Curry._2(G.$star$star$tilde, G.g, x)) + "|")));
            return [
                    Curry._2(G.$star$star$tilde, alpha, x),
                    fs_prove([
                          G.g,
                          alpha
                        ], x, Curry._1(G.hash, zkp))
                  ];
          }), c);
    var match = Belenios_core__Common_types.Shape.split(res);
    return {
            decryption_factors: match[0],
            decryption_proofs: match[1]
          };
  };
  var check_factor = function (c, y, f) {
    var zkp = "decrypt|" + (fingerprint + ("|" + (Curry._1(G.to_string, y) + "|")));
    return Belenios_core__Common_types.Shape.forall3((function (param, f, param$1) {
                  var response = param$1.response;
                  var challenge = param$1.challenge;
                  if (!Curry._1(G.check, f)) {
                    return false;
                  }
                  if (!Belenios_core__Common.check_modulo(G.q, challenge)) {
                    return false;
                  }
                  if (!Belenios_core__Common.check_modulo(G.q, response)) {
                    return false;
                  }
                  var commitments = [
                    Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, response), Curry._2(G.$star$star$tilde, y, challenge)),
                    Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, param.alpha, response), Curry._2(G.$star$star$tilde, f, challenge))
                  ];
                  return Belenios_platform__Platform.Z.$eq$percent(Curry._2(G.hash, zkp, commitments), challenge);
                }), c, f.decryption_factors, f.decryption_proofs);
  };
  var Combinator = Belenios_v1__Trustees.MakeCombinator(G);
  var compute_result = function (encrypted_tally, partial_decryptions, trustees) {
    var num_tallied = encrypted_tally.sized_total_weight;
    var et = encrypted_tally.sized_encrypted_tally;
    var check = function (param, param$1) {
      return check_factor(et, param, param$1);
    };
    var factors = Curry._3(Combinator.combine_factors, trustees, check, partial_decryptions);
    if (factors.TAG !== /* Ok */0) {
      return {
              TAG: /* Error */1,
              _0: factors._0
            };
    }
    var results = Belenios_core__Common_types.Shape.map2((function (param, f) {
            return Curry._2(G.$star$tilde, param.beta, Curry._1(G.invert, f));
          }), et, factors._0);
    var result = Curry._3(Q.compute_result, num_tallied, S.x, results);
    return {
            TAG: /* Ok */0,
            _0: {
              result: result
            }
          };
  };
  var check_result = function (encrypted_tally, partial_decryptions, trustees, param) {
    var num_tallied = encrypted_tally.sized_total_weight;
    var encrypted_tally$1 = encrypted_tally.sized_encrypted_tally;
    if (!check_ciphertext(encrypted_tally$1)) {
      return false;
    }
    var check = function (param, param$1) {
      return check_factor(encrypted_tally$1, param, param$1);
    };
    var factors = Curry._3(Combinator.combine_factors, trustees, check, partial_decryptions);
    if (factors.TAG !== /* Ok */0) {
      return false;
    }
    var results = Belenios_core__Common_types.Shape.map2((function (param, f) {
            return Curry._2(G.$star$tilde, param.beta, Curry._1(G.invert, f));
          }), encrypted_tally$1, factors._0);
    return Curry._4(Q.check_result, num_tallied, S.x, results, param.result);
  };
  return {
          G: G,
          election: election,
          fingerprint: fingerprint,
          public_key: public_key,
          S: S,
          string_of_ballot: string_of_ballot,
          ballot_of_string: ballot_of_string,
          get_credential: get_credential,
          write_result: write_result,
          read_result: read_result,
          E: {
            create_ballot: create_ballot,
            check_ballot: check_ballot,
            check_rawballot: check_rawballot,
            process_ballots: process_ballots,
            extract_nh_ciphertexts: extract_nh_ciphertexts,
            merge_nh_ciphertexts: merge_nh_ciphertexts,
            shuffle_ciphertexts: shuffle_ciphertexts,
            check_shuffle: check_shuffle,
            compute_factor: compute_factor,
            check_factor: check_factor,
            compute_result: compute_result,
            check_result: check_result
          }
        };
}

export {
  of_string ,
  to_string ,
  Make ,
}
/* Belenios_v1__Group Not a pure module */
