// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Stdlib__Map from "melange/./map.js";
import * as Stdlib__Buffer from "melange/./buffer.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios_core__Common from "../core/common.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

function Make(funarg, funarg$1) {
  var G = funarg.G;
  var randoms = function (n) {
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (param) {
                  return Curry._1(funarg$1.random, G.q);
                }));
  };
  var gen_permutation = function (n) {
    var tmp = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return i;
          }));
    var psi = Caml_array.make(n, 0);
    var _i = 0;
    while(true) {
      var i = _i;
      if (i >= n) {
        return psi;
      }
      var k = Curry._1(funarg$1.random, Belenios_platform__Platform.Z.of_int(n - i | 0));
      var k$1 = Belenios_platform__Platform.Z.to_int(k) + i | 0;
      Caml_array.set(psi, i, Caml_array.get(tmp, k$1));
      Caml_array.set(tmp, k$1, Caml_array.get(tmp, i));
      _i = i + 1 | 0;
      continue ;
    };
  };
  var gen_shuffle = function (y, e) {
    var n = e.length;
    var psi = gen_permutation(n);
    var r = randoms(n);
    var e$1 = Curry._3(Belenios_core__Common_types.$$Array.map2, (function (param, param$1) {
            return {
                    alpha: Curry._2(G.$star$tilde, param.alpha, Curry._2(G.$star$star$tilde, G.g, param$1)),
                    beta: Curry._2(G.$star$tilde, param.beta, Curry._2(G.$star$star$tilde, y, param$1))
                  };
          }), e, r);
    var e$2 = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return Caml_array.get(e$1, Caml_array.get(psi, i));
          }));
    return [
            e$2,
            r,
            psi
          ];
  };
  var gen_permutation_commitment = function (psi, h) {
    var n = psi.length;
    var c = Caml_array.make(n, G.one);
    var r = Caml_array.make(n, Belenios_platform__Platform.Z.zero);
    var _i = 0;
    while(true) {
      var i = _i;
      if (i >= n) {
        return [
                c,
                r
              ];
      }
      var r_ = Curry._1(funarg$1.random, G.q);
      Caml_array.set(r, Caml_array.get(psi, i), r_);
      Caml_array.set(c, Caml_array.get(psi, i), Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, r_), Caml_array.get(h, i)));
      _i = i + 1 | 0;
      continue ;
    };
  };
  var get_nizkp_challenges = function (n, str) {
    var h = Belenios_platform__Platform.sha256_hex(str);
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
                  var i$1 = Belenios_platform__Platform.sha256_hex(String(i));
                  return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(h + i$1)), G.q);
                }));
  };
  var get_nizkp_challenge = function (str) {
    var h = Belenios_platform__Platform.sha256_hex(str);
    return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.of_hex(h), G.q);
  };
  var str_egs = function (e) {
    var b = Stdlib__Buffer.create(1024);
    for(var i = 0 ,i_finish = e.length; i < i_finish; ++i){
      var match = Caml_array.get(e, i);
      Curry._2(Stdlib__Printf.bprintf(b, /* Format */{
                _0: {
                  TAG: /* String */2,
                  _0: /* No_padding */0,
                  _1: {
                    TAG: /* Char_literal */12,
                    _0: /* ',' */44,
                    _1: {
                      TAG: /* String */2,
                      _0: /* No_padding */0,
                      _1: {
                        TAG: /* Char_literal */12,
                        _0: /* ',' */44,
                        _1: /* End_of_format */0
                      }
                    }
                  }
                },
                _1: "%s,%s,"
              }), Curry._1(G.to_string, match.alpha), Curry._1(G.to_string, match.beta));
    }
    return Stdlib__Buffer.contents(b);
  };
  var str_elts = function (c) {
    var b = Stdlib__Buffer.create(1024);
    for(var i = 0 ,i_finish = c.length; i < i_finish; ++i){
      Curry._1(Stdlib__Printf.bprintf(b, /* Format */{
                _0: {
                  TAG: /* String */2,
                  _0: /* No_padding */0,
                  _1: {
                    TAG: /* Char_literal */12,
                    _0: /* ',' */44,
                    _1: /* End_of_format */0
                  }
                },
                _1: "%s,"
              }), Curry._1(G.to_string, Caml_array.get(c, i)));
    }
    return Stdlib__Buffer.contents(b);
  };
  var gen_commitment_chain = function (c0, uu) {
    var n = uu.length;
    var rr = randoms(n);
    var cc = Caml_array.make(n, G.one);
    var _i = 0;
    while(true) {
      var i = _i;
      if (i >= n) {
        return [
                cc,
                rr
              ];
      }
      var ccpred = i === 0 ? c0 : Caml_array.get(cc, i - 1 | 0);
      Caml_array.set(cc, i, Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, Caml_array.get(rr, i)), Curry._2(G.$star$star$tilde, ccpred, Caml_array.get(uu, i))));
      _i = i + 1 | 0;
      continue ;
    };
  };
  var GMap = Stdlib__Map.Make({
        compare: G.compare
      });
  var make_get_generator_indep = function (param) {
    var to_avoid = {
      contents: GMap.empty
    };
    return function (n) {
      var x = Curry._1(G.get_generator, n);
      var n$p = Curry._2(GMap.find_opt, x, to_avoid.contents);
      if (n$p !== undefined) {
        return Curry._2(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                        _0: {
                          TAG: /* String_literal */11,
                          _0: "Generator #",
                          _1: {
                            TAG: /* Int */4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: /* String_literal */11,
                              _0: " collides with #",
                              _1: {
                                TAG: /* Int */4,
                                _0: /* Int_d */0,
                                _1: /* No_padding */0,
                                _2: /* No_precision */0,
                                _3: {
                                  TAG: /* Char_literal */12,
                                  _0: /* '!' */33,
                                  _1: /* End_of_format */0
                                }
                              }
                            }
                          }
                        },
                        _1: "Generator #%d collides with #%d!"
                      }), n, n$p);
      } else {
        to_avoid.contents = Curry._3(GMap.add, x, n, to_avoid.contents);
        return x;
      }
    };
  };
  var gen_shuffle_proof = function (y, ee, ee$p, rr$p, psi) {
    var get_generator_indep = make_get_generator_indep(undefined);
    var n = ee.length;
    var h = Curry._1(get_generator_indep, -1);
    if (n !== ee$p.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "mixnet.ml",
              132,
              4
            ],
            Error: new Error()
          };
    }
    if (n !== rr$p.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "mixnet.ml",
              133,
              4
            ],
            Error: new Error()
          };
    }
    if (n !== psi.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "mixnet.ml",
              134,
              4
            ],
            Error: new Error()
          };
    }
    var hh = Curry._2(Belenios_core__Common_types.$$Array.init, n, get_generator_indep);
    var match = gen_permutation_commitment(psi, hh);
    var rr = match[1];
    var cc = match[0];
    var str1 = str_egs(ee) + (str_egs(ee$p) + str_elts(cc));
    var uu = get_nizkp_challenges(n, "shuffle-challenges|" + (funarg.fingerprint + ("|" + str1)));
    var uu$p = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return Caml_array.get(uu, Caml_array.get(psi, i));
          }));
    var match$1 = gen_commitment_chain(h, uu$p);
    var rr_hat = match$1[1];
    var cc_hat = match$1[0];
    var w1 = Curry._1(funarg$1.random, G.q);
    var w2 = Curry._1(funarg$1.random, G.q);
    var w3 = Curry._1(funarg$1.random, G.q);
    var w4 = Curry._1(funarg$1.random, G.q);
    var ww_hat = randoms(n);
    var ww$p = randoms(n);
    var t1 = Curry._2(G.$star$star$tilde, G.g, w1);
    var t2 = Curry._2(G.$star$star$tilde, G.g, w2);
    var t3_ = Curry._3(Belenios_core__Common_types.$$Array.map2, G.$star$star$tilde, hh, ww$p);
    var t3 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, w3), t3_);
    var t41_ = Curry._3(Belenios_core__Common_types.$$Array.map2, (function (e$p, w$p) {
            return Curry._2(G.$star$star$tilde, e$p.beta, w$p);
          }), ee$p, ww$p);
    var t41 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, y, w4)), t41_);
    var t42_ = Curry._3(Belenios_core__Common_types.$$Array.map2, (function (e$p, w$p) {
            return Curry._2(G.$star$star$tilde, e$p.alpha, w$p);
          }), ee$p, ww$p);
    var t42 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, G.g, w4)), t42_);
    var cc_hat$p = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            if (i === 0) {
              return h;
            } else {
              return Caml_array.get(cc_hat, i - 1 | 0);
            }
          }));
    var tt_hat = Belenios_core__Common_types.$$Array.map3((function (w_hat, w$p, c_hat) {
            return Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, w_hat), Curry._2(G.$star$star$tilde, c_hat, w$p));
          }), ww_hat, ww$p, cc_hat$p);
    var t_3 = [
      t41,
      t42
    ];
    var t = [
      t1,
      t2,
      t3,
      t_3,
      tt_hat
    ];
    var str2 = str_elts([
          t1,
          t2,
          t3,
          t41,
          t42
        ]) + str_elts(tt_hat);
    var str3 = str1 + (str_elts(cc_hat) + Curry._1(G.to_string, y));
    var c = get_nizkp_challenge("shuffle-challenge|" + (funarg.fingerprint + ("|" + (str2 + str3))));
    var r_bar = Belenios_platform__Platform.Z.mod(Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, rr), G.q);
    var s1 = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(w1, Belenios_platform__Platform.Z.$star(c, r_bar)), G.q);
    var vv = Caml_array.make(n, Belenios_platform__Platform.Z.one);
    for(var i = n - 2 | 0; i >= 0; --i){
      Caml_array.set(vv, i, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$star(Caml_array.get(uu$p, i + 1 | 0), Caml_array.get(vv, i + 1 | 0)), G.q));
    }
    var r_hat = Belenios_platform__Platform.Z.mod(Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, Curry._3(Belenios_core__Common_types.$$Array.map2, Belenios_platform__Platform.Z.$star, rr_hat, vv)), G.q);
    var s2 = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(w2, Belenios_platform__Platform.Z.$star(c, r_hat)), G.q);
    var r_tilde = Belenios_platform__Platform.Z.mod(Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, Curry._3(Belenios_core__Common_types.$$Array.map2, Belenios_platform__Platform.Z.$star, rr, uu)), G.q);
    var s3 = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(w3, Belenios_platform__Platform.Z.$star(c, r_tilde)), G.q);
    var r$p = Belenios_platform__Platform.Z.mod(Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, Curry._3(Belenios_core__Common_types.$$Array.map2, Belenios_platform__Platform.Z.$star, rr$p, uu)), G.q);
    var s4 = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(w4, Belenios_platform__Platform.Z.$star(c, r$p)), G.q);
    var ss_hat = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(Caml_array.get(ww_hat, i), Belenios_platform__Platform.Z.$star(c, Caml_array.get(rr_hat, i))), G.q);
          }));
    var ss$p = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(Caml_array.get(ww$p, i), Belenios_platform__Platform.Z.$star(c, Caml_array.get(uu$p, i))), G.q);
          }));
    var s = [
      s1,
      s2,
      s3,
      s4,
      ss_hat,
      ss$p
    ];
    return [
            t,
            s,
            cc,
            cc_hat
          ];
  };
  var check_shuffle_proof = function (y, ee, ee$p, proof) {
    var get_generator_indep = make_get_generator_indep(undefined);
    var n = ee.length;
    var h = Curry._1(get_generator_indep, -1);
    if (n !== ee$p.length) {
      return false;
    }
    var s = proof[1];
    var ss$p = s[5];
    var ss_hat = s[4];
    var s4 = s[3];
    var s3 = s[2];
    var s2 = s[1];
    var s1 = s[0];
    var t = proof[0];
    var tt_hat = t[4];
    var match = t[3];
    var t42 = match[1];
    var t41 = match[0];
    var t3 = t[2];
    var t2 = t[1];
    var t1 = t[0];
    var cc_hat = proof[3];
    var cc = proof[2];
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, G.check, [
            t1,
            t2,
            t3,
            t41,
            t42
          ])) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, (function (param) {
              return Belenios_core__Common.check_modulo(G.q, param);
            }), [
            s1,
            s2,
            s3,
            s4
          ])) {
      return false;
    }
    if (n !== cc.length) {
      return false;
    }
    if (n !== cc_hat.length) {
      return false;
    }
    if (n !== tt_hat.length) {
      return false;
    }
    if (n !== ss_hat.length) {
      return false;
    }
    if (n !== ss$p.length) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, G.check, cc)) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, G.check, cc_hat)) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, G.check, tt_hat)) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, (function (param) {
              return Belenios_core__Common.check_modulo(G.q, param);
            }), ss_hat)) {
      return false;
    }
    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, (function (param) {
              return Belenios_core__Common.check_modulo(G.q, param);
            }), ss$p)) {
      return false;
    }
    var hh = Curry._2(Belenios_core__Common_types.$$Array.init, n, get_generator_indep);
    var str1 = str_egs(ee) + (str_egs(ee$p) + str_elts(cc));
    var uu = get_nizkp_challenges(n, "shuffle-challenges|" + (funarg.fingerprint + ("|" + str1)));
    var str2 = str_elts([
          t1,
          t2,
          t3,
          t41,
          t42
        ]) + str_elts(tt_hat);
    var str3 = str1 + (str_elts(cc_hat) + Curry._1(G.to_string, y));
    var c = get_nizkp_challenge("shuffle-challenge|" + (funarg.fingerprint + ("|" + (str2 + str3))));
    var c_bar = Curry._2(G.$star$tilde, Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, G.one, cc), Curry._1(G.invert, Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, G.one, hh)));
    var u = Belenios_platform__Platform.Z.mod(Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$star, Belenios_platform__Platform.Z.one, uu), G.q);
    var c_hat = Curry._2(G.$star$tilde, n === 0 ? h : Caml_array.get(cc_hat, n - 1 | 0), Curry._1(G.invert, Curry._2(G.$star$star$tilde, h, u)));
    var c_tilde = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, G.one, Curry._3(Belenios_core__Common_types.$$Array.map2, G.$star$star$tilde, cc, uu));
    var a$p = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, G.one, Curry._3(Belenios_core__Common_types.$$Array.map2, (function (x, u) {
                return Curry._2(G.$star$star$tilde, x.beta, u);
              }), ee, uu));
    var b$p = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, G.one, Curry._3(Belenios_core__Common_types.$$Array.map2, (function (x, u) {
                return Curry._2(G.$star$star$tilde, x.alpha, u);
              }), ee, uu));
    var t1$p = Curry._2(G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, c_bar, c)), Curry._2(G.$star$star$tilde, G.g, s1));
    var t2$p = Curry._2(G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, c_hat, c)), Curry._2(G.$star$star$tilde, G.g, s2));
    var t3$p = Curry._2(G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, c_tilde, c)), Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._2(G.$star$star$tilde, G.g, s3), Curry._3(Belenios_core__Common_types.$$Array.map2, G.$star$star$tilde, hh, ss$p)));
    var t41$p = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, a$p, c), Curry._2(G.$star$star$tilde, y, s4))), Curry._3(Belenios_core__Common_types.$$Array.map2, (function (x, s) {
                return Curry._2(G.$star$star$tilde, x.beta, s);
              }), ee$p, ss$p));
    var t42$p = Curry._3(Belenios_core__Common_types.$$Array.fold_left, G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$tilde, Curry._2(G.$star$star$tilde, b$p, c), Curry._2(G.$star$star$tilde, G.g, s4))), Curry._3(Belenios_core__Common_types.$$Array.map2, (function (x, s) {
                return Curry._2(G.$star$star$tilde, x.alpha, s);
              }), ee$p, ss$p));
    var tt$p_hat = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            var x = i === 0 ? h : Caml_array.get(cc_hat, i - 1 | 0);
            return Curry._2(G.$star$tilde, Curry._2(G.$star$tilde, Curry._1(G.invert, Curry._2(G.$star$star$tilde, Caml_array.get(cc_hat, i), c)), Curry._2(G.$star$star$tilde, G.g, Caml_array.get(ss_hat, i))), Curry._2(G.$star$star$tilde, x, Caml_array.get(ss$p, i)));
          }));
    if (Curry._2(G.compare, t1, t1$p) === 0 && Curry._2(G.compare, t2, t2$p) === 0 && Curry._2(G.compare, t3, t3$p) === 0 && Curry._2(G.compare, t41, t41$p) === 0 && Curry._2(G.compare, t42, t42$p) === 0) {
      return Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (t, t$p) {
                    return Curry._2(G.compare, t, t$p) === 0;
                  }), tt_hat, tt$p_hat);
    } else {
      return false;
    }
  };
  return {
          gen_shuffle: gen_shuffle,
          gen_shuffle_proof: gen_shuffle_proof,
          check_shuffle_proof: check_shuffle_proof
        };
}

export {
  Make ,
}
/* Belenios_core__Common Not a pure module */
