// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_core__Common from "../core/common.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

function question_length(q) {
  var match = q.q_blank;
  return q.q_answers.length + (
          match !== undefined && match ? 1 : 0
        ) | 0;
}

function Make(funarg, funarg$1) {
  var dummy_ciphertext_alpha = funarg$1.one;
  var dummy_ciphertext_beta = funarg$1.one;
  var dummy_ciphertext = {
    alpha: dummy_ciphertext_alpha,
    beta: dummy_ciphertext_beta
  };
  var eg_combine = function (c1, c2) {
    return {
            alpha: Curry._2(funarg$1.$star$tilde, c1.alpha, c2.alpha),
            beta: Curry._2(funarg$1.$star$tilde, c1.beta, c2.beta)
          };
  };
  var dummy_proof_challenge = Belenios_platform__Platform.Z.zero;
  var dummy_proof_response = Belenios_platform__Platform.Z.zero;
  var dummy_proof = {
    challenge: dummy_proof_challenge,
    response: dummy_proof_response
  };
  var fs_prove = function (gs, x, oracle) {
    var w = Curry._1(funarg.random, funarg$1.q);
    var commitments = Curry._2(Belenios_core__Common_types.$$Array.map, (function (g) {
            return Curry._2(funarg$1.$star$star$tilde, g, w);
          }), gs);
    var challenge = Curry._1(oracle, commitments);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(x, challenge)), funarg$1.q);
    return {
            challenge: challenge,
            response: response
          };
  };
  var eg_disj_prove = function (y, d, zkp, x, r, param) {
    var beta = param.beta;
    var alpha = param.alpha;
    var n = d.length;
    if (!(0 <= x && x < n)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "question_h.ml",
              85,
              4
            ],
            Error: new Error()
          };
    }
    var proofs = Caml_array.make(n, dummy_proof);
    var commitments = Caml_array.make((n << 1), funarg$1.g);
    var total_challenges = {
      contents: Belenios_platform__Platform.Z.zero
    };
    var f = function (i) {
      var challenge = Curry._1(funarg.random, funarg$1.q);
      var response = Curry._1(funarg.random, funarg$1.q);
      Caml_array.set(proofs, i, {
            challenge: challenge,
            response: response
          });
      Caml_array.set(commitments, (i << 1), Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response, Belenios_platform__Platform.Z.$star(r, challenge)), funarg$1.q)));
      Caml_array.set(commitments, (i << 1) + 1 | 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, Curry._2(funarg$1.$star$tilde, beta, Caml_array.get(d, i)), challenge)));
      total_challenges.contents = Belenios_platform__Platform.Z.$plus(total_challenges.contents, challenge);
    };
    var loop = function (_i) {
      while(true) {
        var i = _i;
        if (i < x) {
          f(i);
          _i = i + 1 | 0;
          continue ;
        }
        if (i === x) {
          _i = i + 1 | 0;
          continue ;
        }
        if (i >= n) {
          return ;
        }
        f(i);
        _i = i + 1 | 0;
        continue ;
      };
    };
    loop(0);
    total_challenges.contents = Belenios_platform__Platform.Z.$neg(funarg$1.q, Belenios_platform__Platform.Z.mod(total_challenges.contents, funarg$1.q));
    var p = fs_prove([
          funarg$1.g,
          y
        ], r, (function (commitx) {
            Curry._5(Belenios_core__Common_types.$$Array.blit, commitx, 0, commitments, (x << 1), 2);
            var prefix = Curry._3(Stdlib__Printf.sprintf(/* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "prove|",
                        _1: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* Char_literal */12,
                            _0: /* '|' */124,
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: {
                                TAG: /* Char_literal */12,
                                _0: /* ',' */44,
                                _1: {
                                  TAG: /* String */2,
                                  _0: /* No_padding */0,
                                  _1: {
                                    TAG: /* Char_literal */12,
                                    _0: /* '|' */124,
                                    _1: /* End_of_format */0
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      _1: "prove|%s|%s,%s|"
                    }), zkp, Curry._1(funarg$1.to_string, alpha), Curry._1(funarg$1.to_string, beta));
            return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(Curry._2(funarg$1.hash, prefix, commitments), total_challenges.contents), funarg$1.q);
          }));
    Caml_array.set(proofs, x, p);
    return proofs;
  };
  var eg_disj_verify = function (y, d, zkp, proofs, param) {
    var beta = param.beta;
    var alpha = param.alpha;
    if (!Curry._1(funarg$1.check, alpha)) {
      return false;
    }
    if (!Curry._1(funarg$1.check, beta)) {
      return false;
    }
    var n = d.length;
    if (n !== proofs.length) {
      return false;
    }
    var commitments = Caml_array.make((n << 1), funarg$1.g);
    var total_challenges = Belenios_platform__Platform.Z.zero;
    try {
      for(var i = 0; i < n; ++i){
        var match = Caml_array.get(proofs, i);
        var response = match.response;
        var challenge = match.challenge;
        if (Belenios_core__Common.check_modulo(funarg$1.q, challenge) && Belenios_core__Common.check_modulo(funarg$1.q, response)) {
          Caml_array.set(commitments, (i << 1), Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, response), Curry._2(funarg$1.$star$star$tilde, alpha, challenge)));
          Caml_array.set(commitments, (i << 1) + 1 | 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, Curry._2(funarg$1.$star$tilde, beta, Caml_array.get(d, i)), challenge)));
          total_challenges = Belenios_platform__Platform.Z.$plus(total_challenges, challenge);
        } else {
          throw {
                RE_EXN_ID: Stdlib.Exit,
                Error: new Error()
              };
        }
      }
      total_challenges = Belenios_platform__Platform.Z.mod(total_challenges, funarg$1.q);
      var prefix = Curry._3(Stdlib__Printf.sprintf(/* Format */{
                _0: {
                  TAG: /* String_literal */11,
                  _0: "prove|",
                  _1: {
                    TAG: /* String */2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* Char_literal */12,
                      _0: /* '|' */124,
                      _1: {
                        TAG: /* String */2,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: /* Char_literal */12,
                          _0: /* ',' */44,
                          _1: {
                            TAG: /* String */2,
                            _0: /* No_padding */0,
                            _1: {
                              TAG: /* Char_literal */12,
                              _0: /* '|' */124,
                              _1: /* End_of_format */0
                            }
                          }
                        }
                      }
                    }
                  }
                },
                _1: "prove|%s|%s,%s|"
              }), zkp, Curry._1(funarg$1.to_string, alpha), Curry._1(funarg$1.to_string, beta));
      return Belenios_platform__Platform.Z.$eq$percent(Curry._2(funarg$1.hash, prefix, commitments), total_challenges);
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.RE_EXN_ID === Stdlib.Exit) {
        return false;
      }
      throw exn;
    }
  };
  var make_blank_proof = function (y, zkp, min, max, m0, c0, r0, mS, cS, rS) {
    if (m0 === 0) {
      var challenge1 = Curry._1(funarg.random, funarg$1.q);
      var response1 = Curry._1(funarg.random, funarg$1.q);
      var commitmentA1 = Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response1, Belenios_platform__Platform.Z.$star(rS, challenge1)), funarg$1.q));
      var commitmentB1 = Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response1), Curry._2(funarg$1.$star$star$tilde, cS.beta, challenge1));
      var w = Curry._1(funarg.random, funarg$1.q);
      var commitmentA0 = Curry._2(funarg$1.$star$star$tilde, funarg$1.g, w);
      var commitmentB0 = Curry._2(funarg$1.$star$star$tilde, y, w);
      var prefix = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                _0: {
                  TAG: /* String_literal */11,
                  _0: "bproof0|",
                  _1: {
                    TAG: /* String */2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* Char_literal */12,
                      _0: /* '|' */124,
                      _1: /* End_of_format */0
                    }
                  }
                },
                _1: "bproof0|%s|"
              }), zkp);
      var h = Curry._2(funarg$1.hash, prefix, [
            commitmentA0,
            commitmentB0,
            commitmentA1,
            commitmentB1
          ]);
      var challenge0 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(h, challenge1), funarg$1.q);
      var response0 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(r0, challenge0)), funarg$1.q);
      var blank_proof = [
        {
          challenge: challenge0,
          response: response0
        },
        {
          challenge: challenge1,
          response: response1
        }
      ];
      if (!(min <= mS && mS <= max)) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "question_h.ml",
                164,
                8
              ],
              Error: new Error()
            };
      }
      var challenge0$1 = Curry._1(funarg.random, funarg$1.q);
      var response0$1 = Curry._1(funarg.random, funarg$1.q);
      var proof0 = {
        challenge: challenge0$1,
        response: response0$1
      };
      var overall_proof = Caml_array.make((max - min | 0) + 2 | 0, proof0);
      var commitments = Caml_array.make((((max - min | 0) + 2 | 0) << 1), funarg$1.g);
      var total_challenges = {
        contents: challenge0$1
      };
      Caml_array.set(commitments, 0, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response0$1, Belenios_platform__Platform.Z.$star(r0, challenge0$1)), funarg$1.q)));
      Caml_array.set(commitments, 1, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response0$1), Curry._2(funarg$1.$star$star$tilde, Curry._2(funarg$1.$star$tilde, c0.beta, Curry._1(funarg$1.invert, funarg$1.g)), challenge0$1)));
      var index_true = (mS - min | 0) + 1 | 0;
      var loop = function (_i) {
        while(true) {
          var i = _i;
          if (i >= ((max - min | 0) + 2 | 0)) {
            return ;
          }
          if (i !== index_true) {
            var challenge = Curry._1(funarg.random, funarg$1.q);
            var response = Curry._1(funarg.random, funarg$1.q);
            var g$p = ((min + i | 0) - 1 | 0) === 0 ? funarg$1.one : Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.of_int((min + i | 0) - 1 | 0));
            var nbeta = Curry._2(funarg$1.$star$tilde, cS.beta, Curry._1(funarg$1.invert, g$p));
            var j = (i << 1);
            Caml_array.set(overall_proof, i, {
                  challenge: challenge,
                  response: response
                });
            Caml_array.set(commitments, j, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response, Belenios_platform__Platform.Z.$star(rS, challenge)), funarg$1.q)));
            Caml_array.set(commitments, j + 1 | 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, nbeta, challenge)));
            total_challenges.contents = Belenios_platform__Platform.Z.$plus(total_challenges.contents, challenge);
            _i = i + 1 | 0;
            continue ;
          }
          _i = i + 1 | 0;
          continue ;
        };
      };
      loop(1);
      var w$1 = Curry._1(funarg.random, funarg$1.q);
      var j = (index_true << 1);
      Caml_array.set(commitments, j, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, w$1));
      Caml_array.set(commitments, j + 1 | 0, Curry._2(funarg$1.$star$star$tilde, y, w$1));
      var prefix$1 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                _0: {
                  TAG: /* String_literal */11,
                  _0: "bproof1|",
                  _1: {
                    TAG: /* String */2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* Char_literal */12,
                      _0: /* '|' */124,
                      _1: /* End_of_format */0
                    }
                  }
                },
                _1: "bproof1|%s|"
              }), zkp);
      var h$1 = Curry._2(funarg$1.hash, prefix$1, commitments);
      var challenge = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(h$1, total_challenges.contents), funarg$1.q);
      var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w$1, Belenios_platform__Platform.Z.$star(rS, challenge)), funarg$1.q);
      Caml_array.set(overall_proof, index_true, {
            challenge: challenge,
            response: response
          });
      return [
              overall_proof,
              blank_proof
            ];
    }
    if (mS !== 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "question_h.ml",
              206,
              8
            ],
            Error: new Error()
          };
    }
    var challenge0$2 = Curry._1(funarg.random, funarg$1.q);
    var response0$2 = Curry._1(funarg.random, funarg$1.q);
    var commitmentA0$1 = Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response0$2, Belenios_platform__Platform.Z.$star(r0, challenge0$2)), funarg$1.q));
    var commitmentB0$1 = Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response0$2), Curry._2(funarg$1.$star$star$tilde, c0.beta, challenge0$2));
    var w$2 = Curry._1(funarg.random, funarg$1.q);
    var commitmentA1$1 = Curry._2(funarg$1.$star$star$tilde, funarg$1.g, w$2);
    var commitmentB1$1 = Curry._2(funarg$1.$star$star$tilde, y, w$2);
    var prefix$2 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
              _0: {
                TAG: /* String_literal */11,
                _0: "bproof0|",
                _1: {
                  TAG: /* String */2,
                  _0: /* No_padding */0,
                  _1: {
                    TAG: /* Char_literal */12,
                    _0: /* '|' */124,
                    _1: /* End_of_format */0
                  }
                }
              },
              _1: "bproof0|%s|"
            }), zkp);
    var h$2 = Curry._2(funarg$1.hash, prefix$2, [
          commitmentA0$1,
          commitmentB0$1,
          commitmentA1$1,
          commitmentB1$1
        ]);
    var challenge1$1 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(h$2, challenge0$2), funarg$1.q);
    var response1$1 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w$2, Belenios_platform__Platform.Z.$star(rS, challenge1$1)), funarg$1.q);
    var blank_proof$1 = [
      {
        challenge: challenge0$2,
        response: response0$2
      },
      {
        challenge: challenge1$1,
        response: response1$1
      }
    ];
    if (m0 !== 1) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "question_h.ml",
              224,
              8
            ],
            Error: new Error()
          };
    }
    var nil_proof_challenge = Belenios_platform__Platform.Z.zero;
    var nil_proof_response = Belenios_platform__Platform.Z.zero;
    var nil_proof = {
      challenge: nil_proof_challenge,
      response: nil_proof_response
    };
    var overall_proof$1 = Caml_array.make((max - min | 0) + 2 | 0, nil_proof);
    var commitments$1 = Caml_array.make((((max - min | 0) + 2 | 0) << 1), funarg$1.g);
    var total_challenges$1 = {
      contents: Belenios_platform__Platform.Z.zero
    };
    var loop$1 = function (_i) {
      while(true) {
        var i = _i;
        if (i >= ((max - min | 0) + 2 | 0)) {
          return ;
        }
        var challenge = Curry._1(funarg.random, funarg$1.q);
        var response = Curry._1(funarg.random, funarg$1.q);
        var g$p = ((min + i | 0) - 1 | 0) === 0 ? funarg$1.one : Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.of_int((min + i | 0) - 1 | 0));
        var nbeta = Curry._2(funarg$1.$star$tilde, cS.beta, Curry._1(funarg$1.invert, g$p));
        var j = (i << 1);
        Caml_array.set(overall_proof$1, i, {
              challenge: challenge,
              response: response
            });
        Caml_array.set(commitments$1, j, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(response, Belenios_platform__Platform.Z.$star(rS, challenge)), funarg$1.q)));
        Caml_array.set(commitments$1, j + 1 | 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, nbeta, challenge)));
        total_challenges$1.contents = Belenios_platform__Platform.Z.$plus(total_challenges$1.contents, challenge);
        _i = i + 1 | 0;
        continue ;
      };
    };
    loop$1(1);
    var w$3 = Curry._1(funarg.random, funarg$1.q);
    Caml_array.set(commitments$1, 0, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, w$3));
    Caml_array.set(commitments$1, 1, Curry._2(funarg$1.$star$star$tilde, y, w$3));
    var prefix$3 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
              _0: {
                TAG: /* String_literal */11,
                _0: "bproof1|",
                _1: {
                  TAG: /* String */2,
                  _0: /* No_padding */0,
                  _1: {
                    TAG: /* Char_literal */12,
                    _0: /* '|' */124,
                    _1: /* End_of_format */0
                  }
                }
              },
              _1: "bproof1|%s|"
            }), zkp);
    var h$3 = Curry._2(funarg$1.hash, prefix$3, commitments$1);
    var challenge$1 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(h$3, total_challenges$1.contents), funarg$1.q);
    var response$1 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w$3, Belenios_platform__Platform.Z.$star(r0, challenge$1)), funarg$1.q);
    Caml_array.set(overall_proof$1, 0, {
          challenge: challenge$1,
          response: response$1
        });
    return [
            overall_proof$1,
            blank_proof$1
          ];
  };
  var invg = Curry._1(funarg$1.invert, funarg$1.g);
  var d01 = [
    funarg$1.one,
    invg
  ];
  var make_d = function (min, max) {
    var n = (max - min | 0) + 1 | 0;
    var g$p = min === 0 ? funarg$1.one : Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.of_int(min));
    var d = Caml_array.make(n, Curry._1(funarg$1.invert, g$p));
    for(var i = 1; i < n; ++i){
      Caml_array.set(d, i, Curry._2(funarg$1.$star$tilde, Caml_array.get(d, i - 1 | 0), invg));
    }
    return d;
  };
  var stringify_choices = function (choices) {
    return Curry._2(Belenios_core__Common.$$String.concat, ",", Curry._1(Belenios_core__Common_types.$$Array.to_list, Curry._2(Belenios_core__Common_types.$$Array.map, (function (param) {
                          return Curry._2(Stdlib__Printf.sprintf(/* Format */{
                                          _0: {
                                            TAG: /* String */2,
                                            _0: /* No_padding */0,
                                            _1: {
                                              TAG: /* Char_literal */12,
                                              _0: /* ',' */44,
                                              _1: {
                                                TAG: /* String */2,
                                                _0: /* No_padding */0,
                                                _1: /* End_of_format */0
                                              }
                                            }
                                          },
                                          _1: "%s,%s"
                                        }), Curry._1(funarg$1.to_string, param.alpha), Curry._1(funarg$1.to_string, param.beta));
                        }), choices)));
  };
  var create_answer = function (q, y, zkp, m) {
    var n = m.length;
    var r = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (param) {
            return Curry._1(funarg.random, funarg$1.q);
          }));
    var choices = Curry._3(Belenios_core__Common_types.$$Array.map2, (function (param, param$1) {
            return {
                    alpha: Curry._2(funarg$1.$star$star$tilde, funarg$1.g, param),
                    beta: Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, param), Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.of_int(param$1)))
                  };
          }), r, m);
    var individual_proofs = Belenios_core__Common_types.$$Array.map3((function (param, param$1, param$2) {
            return eg_disj_prove(y, d01, zkp, param, param$1, param$2);
          }), m, r, choices);
    var zkp$1 = zkp + ("|" + stringify_choices(choices));
    var match = q.q_blank;
    if (match !== undefined && match) {
      if (n !== (q.q_answers.length + 1 | 0)) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "question_h.ml",
                349,
                7
              ],
              Error: new Error()
            };
      }
      var choices$p = Curry._3(Belenios_core__Common_types.$$Array.sub, choices, 1, n - 1 | 0);
      var r$p = Curry._3(Belenios_core__Common_types.$$Array.sub, r, 1, n - 1 | 0);
      var m$p = Curry._3(Belenios_core__Common_types.$$Array.sub, m, 1, n - 1 | 0);
      var sumr = Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, r$p);
      var summ = Curry._3(Belenios_core__Common_types.$$Array.fold_left, (function (prim0, prim1) {
              return prim0 + prim1 | 0;
            }), 0, m$p);
      var sumc = Curry._3(Belenios_core__Common_types.$$Array.fold_left, eg_combine, dummy_ciphertext, choices$p);
      var match$1 = make_blank_proof(y, zkp$1, q.q_min, q.q_max, Caml_array.get(m, 0), Caml_array.get(choices, 0), Caml_array.get(r, 0), summ, sumc, sumr);
      var blank_proof = match$1[1];
      return {
              choices: choices,
              individual_proofs: individual_proofs,
              overall_proof: match$1[0],
              blank_proof: blank_proof
            };
    }
    if (n !== q.q_answers.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "question_h.ml",
              364,
              7
            ],
            Error: new Error()
          };
    }
    var sumr$1 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, r);
    var summ$1 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, (function (prim0, prim1) {
            return prim0 + prim1 | 0;
          }), 0, m);
    var sumc$1 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, eg_combine, dummy_ciphertext, choices);
    if (!(q.q_min <= summ$1 && summ$1 <= q.q_max)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "question_h.ml",
              368,
              7
            ],
            Error: new Error()
          };
    }
    var d = make_d(q.q_min, q.q_max);
    var overall_proof = eg_disj_prove(y, d, zkp$1, summ$1 - q.q_min | 0, sumr$1, sumc$1);
    return {
            choices: choices,
            individual_proofs: individual_proofs,
            overall_proof: overall_proof,
            blank_proof: undefined
          };
  };
  var verify_answer = function (q, y, zkp, a) {
    var n = a.choices.length;
    if (n !== a.individual_proofs.length) {
      return false;
    }
    if (!Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (param, param$1) {
              return eg_disj_verify(y, d01, zkp, param, param$1);
            }), a.individual_proofs, a.choices)) {
      return false;
    }
    var zkp$1 = zkp + ("|" + stringify_choices(a.choices));
    var match = q.q_blank;
    var match$1 = a.blank_proof;
    if (match !== undefined && match && match$1 !== undefined) {
      if (n !== (q.q_answers.length + 1 | 0)) {
        return false;
      }
      var c = Curry._3(Belenios_core__Common_types.$$Array.sub, a.choices, 1, n - 1 | 0);
      var sumc = Curry._3(Belenios_core__Common_types.$$Array.fold_left, eg_combine, dummy_ciphertext, c);
      var min = q.q_min;
      var max = q.q_max;
      var c0 = Caml_array.get(a.choices, 0);
      var overall_proof = a.overall_proof;
      if (!Curry._1(funarg$1.check, c0.alpha)) {
        return false;
      }
      if (!Curry._1(funarg$1.check, c0.beta)) {
        return false;
      }
      if (!Curry._1(funarg$1.check, sumc.alpha)) {
        return false;
      }
      if (!Curry._1(funarg$1.check, sumc.beta)) {
        return false;
      }
      if (match$1.length !== 2) {
        return false;
      }
      var tmp;
      try {
        var commitments = Caml_array.make(4, funarg$1.g);
        var total_challenges = Belenios_platform__Platform.Z.zero;
        var match$2 = Caml_array.get(match$1, 0);
        var response = match$2.response;
        var challenge = match$2.challenge;
        if (!(Belenios_core__Common.check_modulo(funarg$1.q, challenge) && Belenios_core__Common.check_modulo(funarg$1.q, response))) {
          throw {
                RE_EXN_ID: Stdlib.Exit,
                Error: new Error()
              };
        }
        Caml_array.set(commitments, 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, response), Curry._2(funarg$1.$star$star$tilde, c0.alpha, challenge)));
        Caml_array.set(commitments, 1, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, c0.beta, challenge)));
        total_challenges = Belenios_platform__Platform.Z.$plus(total_challenges, challenge);
        var match$3 = Caml_array.get(match$1, 1);
        var response$1 = match$3.response;
        var challenge$1 = match$3.challenge;
        if (!(Belenios_core__Common.check_modulo(funarg$1.q, challenge$1) && Belenios_core__Common.check_modulo(funarg$1.q, response$1))) {
          throw {
                RE_EXN_ID: Stdlib.Exit,
                Error: new Error()
              };
        }
        Caml_array.set(commitments, 2, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, response$1), Curry._2(funarg$1.$star$star$tilde, sumc.alpha, challenge$1)));
        Caml_array.set(commitments, 3, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response$1), Curry._2(funarg$1.$star$star$tilde, sumc.beta, challenge$1)));
        total_challenges = Belenios_platform__Platform.Z.$plus(total_challenges, challenge$1);
        var prefix = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* String_literal */11,
                    _0: "bproof0|",
                    _1: {
                      TAG: /* String */2,
                      _0: /* No_padding */0,
                      _1: {
                        TAG: /* Char_literal */12,
                        _0: /* '|' */124,
                        _1: /* End_of_format */0
                      }
                    }
                  },
                  _1: "bproof0|%s|"
                }), zkp$1);
        var h = Curry._2(funarg$1.hash, prefix, commitments);
        var total_challenges$1 = Belenios_platform__Platform.Z.mod(total_challenges, funarg$1.q);
        tmp = Belenios_platform__Platform.Z.$eq$percent(h, total_challenges$1);
      }
      catch (raw_exn){
        var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
        if (exn.RE_EXN_ID === Stdlib.Exit) {
          tmp = false;
        } else {
          throw exn;
        }
      }
      if (!tmp) {
        return false;
      }
      if (overall_proof.length !== ((max - min | 0) + 2 | 0)) {
        return false;
      }
      try {
        var commitments$1 = Caml_array.make((((max - min | 0) + 2 | 0) << 1), funarg$1.g);
        var total_challenges$2 = {
          contents: Belenios_platform__Platform.Z.zero
        };
        var match$4 = Caml_array.get(overall_proof, 0);
        var response$2 = match$4.response;
        var challenge$2 = match$4.challenge;
        if (!(Belenios_core__Common.check_modulo(funarg$1.q, challenge$2) && Belenios_core__Common.check_modulo(funarg$1.q, response$2))) {
          throw {
                RE_EXN_ID: Stdlib.Exit,
                Error: new Error()
              };
        }
        Caml_array.set(commitments$1, 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, response$2), Curry._2(funarg$1.$star$star$tilde, c0.alpha, challenge$2)));
        Caml_array.set(commitments$1, 1, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response$2), Curry._2(funarg$1.$star$star$tilde, Curry._2(funarg$1.$star$tilde, c0.beta, Curry._1(funarg$1.invert, funarg$1.g)), challenge$2)));
        total_challenges$2.contents = Belenios_platform__Platform.Z.$plus(total_challenges$2.contents, challenge$2);
        var loop = function (_i) {
          while(true) {
            var i = _i;
            if (i >= ((max - min | 0) + 2 | 0)) {
              return ;
            }
            var match = Caml_array.get(overall_proof, i);
            var response = match.response;
            var challenge = match.challenge;
            if (!(Belenios_core__Common.check_modulo(funarg$1.q, challenge) && Belenios_core__Common.check_modulo(funarg$1.q, response))) {
              throw {
                    RE_EXN_ID: Stdlib.Exit,
                    Error: new Error()
                  };
            }
            var g$p = ((min + i | 0) - 1 | 0) === 0 ? funarg$1.one : Curry._2(funarg$1.$star$star$tilde, funarg$1.g, Belenios_platform__Platform.Z.of_int((min + i | 0) - 1 | 0));
            var nbeta = Curry._2(funarg$1.$star$tilde, sumc.beta, Curry._1(funarg$1.invert, g$p));
            var j = (i << 1);
            Caml_array.set(commitments$1, j, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, funarg$1.g, response), Curry._2(funarg$1.$star$star$tilde, sumc.alpha, challenge)));
            Caml_array.set(commitments$1, j + 1 | 0, Curry._2(funarg$1.$star$tilde, Curry._2(funarg$1.$star$star$tilde, y, response), Curry._2(funarg$1.$star$star$tilde, nbeta, challenge)));
            total_challenges$2.contents = Belenios_platform__Platform.Z.$plus(total_challenges$2.contents, challenge);
            _i = i + 1 | 0;
            continue ;
          };
        };
        loop(1);
        var prefix$1 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* String_literal */11,
                    _0: "bproof1|",
                    _1: {
                      TAG: /* String */2,
                      _0: /* No_padding */0,
                      _1: {
                        TAG: /* Char_literal */12,
                        _0: /* '|' */124,
                        _1: /* End_of_format */0
                      }
                    }
                  },
                  _1: "bproof1|%s|"
                }), zkp$1);
        var h$1 = Curry._2(funarg$1.hash, prefix$1, commitments$1);
        var total_challenges$3 = Belenios_platform__Platform.Z.mod(total_challenges$2.contents, funarg$1.q);
        return Belenios_platform__Platform.Z.$eq$percent(h$1, total_challenges$3);
      }
      catch (raw_exn$1){
        var exn$1 = Caml_js_exceptions.internalToOCamlException(raw_exn$1);
        if (exn$1.RE_EXN_ID === Stdlib.Exit) {
          return false;
        }
        throw exn$1;
      }
    }
    if (match$1 !== undefined) {
      return false;
    }
    if (n !== q.q_answers.length) {
      return false;
    }
    var sumc$1 = Curry._3(Belenios_core__Common_types.$$Array.fold_left, eg_combine, dummy_ciphertext, a.choices);
    var d = make_d(q.q_min, q.q_max);
    return eg_disj_verify(y, d, zkp$1, a.overall_proof, sumc$1);
  };
  var extract_ciphertexts = function (param, a) {
    return {
            NAME: "Array",
            VAL: Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                    return {
                            NAME: "Atomic",
                            VAL: x
                          };
                  }), a.choices)
          };
  };
  var process_ciphertexts = function (q, es) {
    var neutral_1 = Caml_array.make(question_length(q), {
          NAME: "Atomic",
          VAL: dummy_ciphertext
        });
    var neutral = {
      NAME: "Array",
      VAL: neutral_1
    };
    var $star = function (param, param$1) {
      return Belenios_core__Common_types.Shape.map2(eg_combine, param, param$1);
    };
    var power = function (b, n) {
      if (Belenios_platform__Platform.Z.compare(n, Belenios_platform__Platform.Z.zero) <= 0) {
        return neutral;
      }
      var x = power(b, Belenios_platform__Platform.Z.shift_right(n, 1));
      return $star($star(Belenios_platform__Platform.Z.compare(Belenios_platform__Platform.Z.logand(n, Belenios_platform__Platform.Z.one), Belenios_platform__Platform.Z.one) === 0 ? b : neutral, x), x);
    };
    var total = Curry._3(Belenios_core__Common.List.fold_left, (function (a, param) {
            return Belenios_core__Common_types.Weight.$plus(a, param[0]);
          }), Belenios_core__Common_types.Weight.zero, es);
    var es$1 = Curry._2(Belenios_core__Common.List.map, (function (param) {
            return power(param[1], Belenios_core__Common_types.Weight.expand(total, param[0]));
          }), es);
    return Curry._3(Belenios_core__Common.List.fold_left, (function (param, param$1) {
                  return Belenios_core__Common_types.Shape.map2(eg_combine, param, param$1);
                }), neutral, es$1);
  };
  var compute_result = function (total) {
    var num_tallied = Belenios_core__Common_types.Weight.expand(total, total);
    var X = Belenios_core__Common.BabyStepGiantStep(funarg$1);
    var log = Curry._2(X.log, funarg$1.g, num_tallied);
    var log$1 = function (x) {
      var x$1 = Curry._1(log, x);
      if (x$1 !== undefined) {
        return Caml_option.valFromOption(x$1);
      } else {
        return Stdlib.invalid_arg("Cannot compute result");
      }
    };
    return function (x) {
      return Curry._2(Belenios_core__Common_types.$$Array.map, (function (i) {
                    return Belenios_core__Common_types.Weight.reduce(total, log$1(i));
                  }), Belenios_core__Common_types.Shape.to_array(x));
    };
  };
  var check_result = function (num_tallied, x, r) {
    return Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (x, r) {
                  var r$1 = Belenios_core__Common_types.Weight.expand(num_tallied, r);
                  var g$p = Belenios_platform__Platform.Z.compare(r$1, Belenios_platform__Platform.Z.zero) === 0 ? funarg$1.one : Curry._2(funarg$1.$star$star$tilde, funarg$1.g, r$1);
                  return Curry._2(funarg$1.$eq$tilde, x, g$p);
                }), Belenios_core__Common_types.Shape.to_array(x), r);
  };
  return {
          create_answer: create_answer,
          verify_answer: verify_answer,
          extract_ciphertexts: extract_ciphertexts,
          process_ciphertexts: process_ciphertexts,
          compute_result: compute_result,
          check_result: check_result
        };
}

export {
  Make ,
}
/* Belenios_core__Common Not a pure module */
