// Generated by Melange

import * as Atdgen_runtime from "../../../../bs-atdgen-codec-runtime/src/atdgen_runtime.js";
import * as Atdgen_codec_decode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_decode.js";
import * as Atdgen_codec_encode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_encode.js";
import * as Belenios_core__Question from "../core/question.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_core__Serializable_core_bs from "../core/serializable_core_bs.js";

function write__x_902386e(param) {
  return Atdgen_codec_encode.contramap(Belenios_core__Common_types.Uuid.unwrap, Atdgen_codec_encode.string, param);
}

function read__x_902386e(param) {
  return Atdgen_codec_decode.map(Belenios_core__Common_types.Uuid.wrap, Atdgen_codec_decode.string, param);
}

function string_of_uuid(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_902386e, x));
}

function uuid_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_902386e, JSON.parse(s));
}

function string_of_proof(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(Belenios_core__Serializable_core_bs.write_proof, x));
}

function proof_of_string(s) {
  return Atdgen_codec_decode.decode(Belenios_core__Serializable_core_bs.read_proof, JSON.parse(s));
}

var write_signature = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "hash", t.s_hash),
                  tl: {
                    hd: Atdgen_codec_encode.field(undefined, Belenios_core__Serializable_core_bs.write_proof, "proof", t.s_proof),
                    tl: /* [] */0
                  }
                });
    });

function string_of_signature(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_signature, x));
}

var read_signature = Atdgen_codec_decode.make(function (json) {
      return {
              s_hash: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("hash", Atdgen_codec_decode.string, param);
                    }), json),
              s_proof: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("proof", Belenios_core__Serializable_core_bs.read_proof, param);
                    }), json)
            };
    });

function signature_of_string(s) {
  return Atdgen_codec_decode.decode(read_signature, JSON.parse(s));
}

function write__x_bf6ca8f(param) {
  return Atdgen_codec_encode.contramap(Belenios_core__Question.unwrap, Atdgen_runtime.jsont_of_json, param);
}

function read__x_bf6ca8f(param) {
  return Atdgen_codec_decode.map(Belenios_core__Question.wrap, Atdgen_runtime.json_of_jsont, param);
}

function string_of_question(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_bf6ca8f, x));
}

function question_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_bf6ca8f, JSON.parse(s));
}

function write__x_a355eac(param) {
  return Atdgen_codec_encode.array(write__x_bf6ca8f, param);
}

function read__x_a355eac(param) {
  return Atdgen_codec_decode.array(read__x_bf6ca8f, param);
}

Atdgen_codec_decode.option_as_constr(Atdgen_codec_decode.string);

function write_params(write__a) {
  return Atdgen_codec_encode.make(function (t) {
              return Atdgen_codec_encode.obj({
                          hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.$$int, "version", t.e_version),
                          tl: {
                            hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "description", t.e_description),
                            tl: {
                              hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "name", t.e_name),
                              tl: {
                                hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "group", t.e_group),
                                tl: {
                                  hd: Atdgen_codec_encode.field(undefined, write__a, "public_key", t.e_public_key),
                                  tl: {
                                    hd: Atdgen_codec_encode.field(undefined, write__x_a355eac, "questions", t.e_questions),
                                    tl: {
                                      hd: Atdgen_codec_encode.field(undefined, write__x_902386e, "uuid", t.e_uuid),
                                      tl: {
                                        hd: Atdgen_codec_encode.field_o(undefined, Atdgen_codec_encode.string, "administrator", t.e_administrator),
                                        tl: {
                                          hd: Atdgen_codec_encode.field_o(undefined, Atdgen_codec_encode.string, "credential_authority", t.e_credential_authority),
                                          tl: /* [] */0
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        });
            });
}

function string_of_params(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_params(write__a), x));
}

function read_params(read__a) {
  return Atdgen_codec_decode.make(function (json) {
              return {
                      e_version: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("version", Atdgen_codec_decode.$$int, param);
                            }), json),
                      e_description: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("description", Atdgen_codec_decode.string, param);
                            }), json),
                      e_name: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("name", Atdgen_codec_decode.string, param);
                            }), json),
                      e_group: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("group", Atdgen_codec_decode.string, param);
                            }), json),
                      e_public_key: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("public_key", read__a, param);
                            }), json),
                      e_questions: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("questions", read__x_a355eac, param);
                            }), json),
                      e_uuid: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("uuid", read__x_902386e, param);
                            }), json),
                      e_administrator: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.fieldOptional("administrator", Atdgen_codec_decode.string, param);
                            }), json),
                      e_credential_authority: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.fieldOptional("credential_authority", Atdgen_codec_decode.string, param);
                            }), json)
                    };
            });
}

function params_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(read_params(read__a), JSON.parse(s));
}

function write__x_67cdf8a(param) {
  return Atdgen_codec_encode.contramap(Belenios_core__Common_types.$$Number.unwrap, Atdgen_codec_encode.string, param);
}

function read__x_67cdf8a(param) {
  return Atdgen_codec_decode.map(Belenios_core__Common_types.$$Number.wrap, Atdgen_codec_decode.string, param);
}

function string_of_number(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_67cdf8a, x));
}

function number_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_67cdf8a, JSON.parse(s));
}

function write__x_aa1b1a8(param) {
  return Atdgen_codec_encode.array(Atdgen_runtime.jsont_of_json, param);
}

function read__x_aa1b1a8(param) {
  return Atdgen_codec_decode.array(Atdgen_runtime.json_of_jsont, param);
}

Atdgen_codec_decode.option_as_constr(read_signature);

function write_ballot(write__a) {
  return Atdgen_codec_encode.make(function (t) {
              return Atdgen_codec_encode.obj({
                          hd: Atdgen_codec_encode.field(undefined, write__x_902386e, "election_uuid", t.election_uuid),
                          tl: {
                            hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "election_hash", t.election_hash),
                            tl: {
                              hd: Atdgen_codec_encode.field(undefined, write__a, "credential", t.credential),
                              tl: {
                                hd: Atdgen_codec_encode.field(undefined, write__x_aa1b1a8, "answers", t.answers),
                                tl: {
                                  hd: Atdgen_codec_encode.field_o(undefined, write_signature, "signature", t.signature),
                                  tl: /* [] */0
                                }
                              }
                            }
                          }
                        });
            });
}

function string_of_ballot(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_ballot(write__a), x));
}

function read_ballot(read__a) {
  return Atdgen_codec_decode.make(function (json) {
              return {
                      election_uuid: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("election_uuid", read__x_902386e, param);
                            }), json),
                      election_hash: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("election_hash", Atdgen_codec_decode.string, param);
                            }), json),
                      credential: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("credential", read__a, param);
                            }), json),
                      answers: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("answers", read__x_aa1b1a8, param);
                            }), json),
                      signature: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.fieldOptional("signature", read_signature, param);
                            }), json)
                    };
            });
}

function ballot_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(read_ballot(read__a), JSON.parse(s));
}

var read_uuid = read__x_902386e;

var write_uuid = write__x_902386e;

var read_proof = Belenios_core__Serializable_core_bs.read_proof;

var write_proof = Belenios_core__Serializable_core_bs.write_proof;

var read_question = read__x_bf6ca8f;

var write_question = write__x_bf6ca8f;

var read_number = read__x_67cdf8a;

var write_number = write__x_67cdf8a;

export {
  read_uuid ,
  uuid_of_string ,
  write_uuid ,
  string_of_uuid ,
  read_proof ,
  proof_of_string ,
  write_proof ,
  string_of_proof ,
  read_signature ,
  signature_of_string ,
  write_signature ,
  string_of_signature ,
  read_question ,
  question_of_string ,
  write_question ,
  string_of_question ,
  read_params ,
  params_of_string ,
  write_params ,
  string_of_params ,
  read_number ,
  number_of_string ,
  write_number ,
  string_of_number ,
  read_ballot ,
  ballot_of_string ,
  write_ballot ,
  string_of_ballot ,
}
/* write_signature Not a pure module */
