// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_string from "melange.runtime/caml_string.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Caml_exceptions from "melange.runtime/caml_exceptions.js";
import * as Belenios_core__Util from "../core/util.js";
import * as Belenios_core__Common from "../core/common.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";
import * as Belenios_core__Serializable_j from "../core/serializable_j.js";

var PedersenFailure = /* @__PURE__ */Caml_exceptions.create("Belenios_v1.Trustees.PedersenFailure");

function MakeChannels(G, M, P) {
  var send = function (sk, c_recipient, c_message) {
    var msg = {
      c_recipient: c_recipient,
      c_message: c_message
    };
    var msg$1 = Belenios_core__Serializable_j.string_of_channel_msg((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), msg);
    var msg$2 = Curry._2(P.sign, sk, msg$1);
    return Curry._2(P.encrypt, c_recipient, Belenios_core__Serializable_j.string_of_signed_msg(msg$2));
  };
  var recv = function (dk, vk, msg) {
    var msg$1 = Belenios_core__Serializable_j.signed_msg_of_string(Curry._2(P.decrypt, dk, msg));
    if (!Curry._2(P.verify, vk, msg$1)) {
      Stdlib.failwith("invalid signature on received message");
    }
    var msg$2 = Belenios_core__Serializable_j.channel_msg_of_string((function (param) {
            return Belenios_core__Common.sread(G.of_string, param);
          }), msg$1.s_message);
    if (!Curry._2(G.$eq$tilde, msg$2.c_recipient, Curry._2(G.$star$star$tilde, G.g, dk))) {
      Stdlib.failwith("invalid recipient on received message");
    }
    return msg$2.c_message;
  };
  return {
          send: send,
          recv: recv
        };
}

function MakeSimple(funarg, funarg$1) {
  var fs_prove = function (gs, x, oracle) {
    var w = Curry._1(funarg$1.random, funarg.q);
    var commitments = Curry._2(Belenios_core__Common_types.$$Array.map, (function (g) {
            return Curry._2(funarg.$star$star$tilde, g, w);
          }), gs);
    var challenge = Curry._1(oracle, commitments);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(x, challenge)), funarg.q);
    return {
            challenge: challenge,
            response: response
          };
  };
  var generate = function (param) {
    return Curry._1(funarg$1.random, funarg.q);
  };
  var prove = function (x) {
    var trustee_public_key = Curry._2(funarg.$star$star$tilde, funarg.g, x);
    var zkp = "pok|" + (funarg.description + ("|" + (Curry._1(funarg.to_string, trustee_public_key) + "|")));
    var trustee_pok = fs_prove([funarg.g], x, Curry._1(funarg.hash, zkp));
    return {
            trustee_pok: trustee_pok,
            trustee_public_key: trustee_public_key,
            trustee_name: undefined
          };
  };
  return {
          generate: generate,
          prove: prove
        };
}

function MakePKI(funarg, funarg$1) {
  var genkey = function (param) {
    var z58 = Belenios_platform__Platform.Z.of_int(58);
    return Curry._2(Belenios_core__Common.$$String.init, 22, (function (param) {
                  var x = Curry._1(funarg$1.random, z58);
                  return Caml_string.get("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz", Belenios_platform__Platform.Z.to_int(x));
                }));
  };
  var derive_sk = function (p) {
    return Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex("sk|" + p));
  };
  var derive_dk = function (p) {
    return Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex("dk|" + p));
  };
  var sign = function (sk, s_message) {
    var w = Curry._1(funarg$1.random, funarg.q);
    var commitment = Curry._2(funarg.$star$star$tilde, funarg.g, w);
    var prefix = "sigmsg|" + (s_message + "|");
    var challenge = Curry._2(funarg.hash, prefix, [commitment]);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(sk, challenge)), funarg.q);
    var s_signature = {
      challenge: challenge,
      response: response
    };
    return {
            s_message: s_message,
            s_signature: s_signature
          };
  };
  var encrypt = function (y, plaintext) {
    var r = Curry._1(funarg$1.random, funarg.q);
    var key = Curry._1(funarg$1.random, funarg.q);
    var key$1 = Curry._2(funarg.$star$star$tilde, funarg.g, key);
    var y_alpha = Curry._2(funarg.$star$star$tilde, funarg.g, r);
    var y_beta = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, y, r), key$1);
    var key$2 = Belenios_platform__Platform.sha256_hex("key|" + Curry._1(funarg.to_string, key$1));
    var iv = Belenios_platform__Platform.sha256_hex("iv|" + Curry._1(funarg.to_string, y_alpha));
    var y_data = Belenios_platform__Platform.encrypt(key$2, iv, plaintext);
    return {
            y_alpha: y_alpha,
            y_beta: y_beta,
            y_data: y_data
          };
  };
  var decrypt = function (x, param) {
    var y_alpha = param.y_alpha;
    var key = Belenios_platform__Platform.sha256_hex("key|" + Curry._1(funarg.to_string, Curry._2(funarg.$star$tilde, param.y_beta, Curry._1(funarg.invert, Curry._2(funarg.$star$star$tilde, y_alpha, x)))));
    var iv = Belenios_platform__Platform.sha256_hex("iv|" + Curry._1(funarg.to_string, y_alpha));
    return Belenios_platform__Platform.decrypt(key, iv, param.y_data);
  };
  var make_cert = function (sk, dk) {
    var cert_keys_cert_verification = Curry._2(funarg.$star$star$tilde, funarg.g, sk);
    var cert_keys_cert_encryption = Curry._2(funarg.$star$star$tilde, funarg.g, dk);
    var cert_keys = {
      cert_verification: cert_keys_cert_verification,
      cert_encryption: cert_keys_cert_encryption
    };
    var cert = Belenios_core__Serializable_j.string_of_cert_keys((function (param) {
            return Belenios_core__Common.swrite(funarg.to_string, param);
          }), cert_keys);
    return sign(sk, cert);
  };
  var verify = function (vk, param) {
    var match = param.s_signature;
    var response = match.response;
    var challenge = match.challenge;
    if (!Belenios_core__Common.check_modulo(funarg.q, challenge)) {
      return false;
    }
    if (!Belenios_core__Common.check_modulo(funarg.q, response)) {
      return false;
    }
    var commitment = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, response), Curry._2(funarg.$star$star$tilde, vk, challenge));
    var prefix = "sigmsg|" + (param.s_message + "|");
    return Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(funarg.hash, prefix, [commitment]));
  };
  var verify_cert = function (x) {
    var keys = Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
            return Belenios_core__Common.sread(funarg.of_string, param);
          }), x.s_message);
    return verify(keys.cert_verification, x);
  };
  return {
          genkey: genkey,
          derive_sk: derive_sk,
          derive_dk: derive_dk,
          sign: sign,
          verify: verify,
          encrypt: encrypt,
          decrypt: decrypt,
          make_cert: make_cert,
          verify_cert: verify_cert
        };
}

function MakePedersen(funarg, funarg$1, funarg$2, funarg$3) {
  var fs_prove = function (gs, x, oracle) {
    var w = Curry._1(funarg$1.random, funarg.q);
    var commitments = Curry._2(Belenios_core__Common_types.$$Array.map, (function (g) {
            return Curry._2(funarg.$star$star$tilde, g, w);
          }), gs);
    var challenge = Curry._1(oracle, commitments);
    var response = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(w, Belenios_platform__Platform.Z.$star(x, challenge)), funarg.q);
    return {
            challenge: challenge,
            response: response
          };
  };
  var prove = function (x) {
    var trustee_public_key = Curry._2(funarg.$star$star$tilde, funarg.g, x);
    var zkp = "pok|" + (funarg.description + ("|" + (Curry._1(funarg.to_string, trustee_public_key) + "|")));
    var trustee_pok = fs_prove([funarg.g], x, Curry._1(funarg.hash, zkp));
    return {
            trustee_pok: trustee_pok,
            trustee_public_key: trustee_public_key,
            trustee_name: undefined
          };
  };
  var compute_verification_keys = function (coefexps) {
    var n = coefexps.length;
    if (n <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              47,
              4
            ],
            Error: new Error()
          };
    }
    var threshold = Caml_array.get(coefexps, 0).length;
    if (threshold <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              49,
              4
            ],
            Error: new Error()
          };
    }
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (j) {
                  var jj = Belenios_platform__Platform.Z.of_int(j + 1 | 0);
                  var _i = 0;
                  var _vk = funarg.one;
                  while(true) {
                    var vk = _vk;
                    var i = _i;
                    if (i >= n) {
                      return vk;
                    }
                    var c = Caml_array.get(coefexps, i);
                    if (threshold !== c.length) {
                      throw {
                            RE_EXN_ID: "Assert_failure",
                            _1: [
                              "trustees.ml",
                              55,
                              12
                            ],
                            Error: new Error()
                          };
                    }
                    var loop = (function(c){
                    return function loop(_k, _jk, _accu) {
                      while(true) {
                        var accu = _accu;
                        var jk = _jk;
                        var k = _k;
                        if (k >= threshold) {
                          return accu;
                        }
                        _accu = Curry._2(funarg.$star$tilde, accu, Curry._2(funarg.$star$star$tilde, Caml_array.get(c, k), jk));
                        _jk = Belenios_platform__Platform.Z.$star(jk, jj);
                        _k = k + 1 | 0;
                        continue ;
                      };
                    }
                    }(c));
                    var computed_gsij = loop(0, Belenios_platform__Platform.Z.one, funarg.one);
                    _vk = Curry._2(funarg.$star$tilde, vk, computed_gsij);
                    _i = i + 1 | 0;
                    continue ;
                  };
                }));
  };
  var verify = function (vk, param) {
    var match = param.s_signature;
    var response = match.response;
    var challenge = match.challenge;
    if (!Belenios_core__Common.check_modulo(funarg.q, challenge)) {
      return false;
    }
    if (!Belenios_core__Common.check_modulo(funarg.q, response)) {
      return false;
    }
    var commitment = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, response), Curry._2(funarg.$star$star$tilde, vk, challenge));
    var prefix = "sigmsg|" + (param.s_message + "|");
    return Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(funarg.hash, prefix, [commitment]));
  };
  var verify_cert = function (x) {
    var keys = Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
            return Belenios_core__Common.sread(funarg.of_string, param);
          }), x.s_message);
    return verify(keys.cert_verification, x);
  };
  var compute_verification_keys$1 = function (coefexps) {
    var n = coefexps.length;
    if (n <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              47,
              4
            ],
            Error: new Error()
          };
    }
    var threshold = Caml_array.get(coefexps, 0).length;
    if (threshold <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              49,
              4
            ],
            Error: new Error()
          };
    }
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (j) {
                  var jj = Belenios_platform__Platform.Z.of_int(j + 1 | 0);
                  var _i = 0;
                  var _vk = funarg.one;
                  while(true) {
                    var vk = _vk;
                    var i = _i;
                    if (i >= n) {
                      return vk;
                    }
                    var c = Caml_array.get(coefexps, i);
                    if (threshold !== c.length) {
                      throw {
                            RE_EXN_ID: "Assert_failure",
                            _1: [
                              "trustees.ml",
                              55,
                              12
                            ],
                            Error: new Error()
                          };
                    }
                    var loop = (function(c){
                    return function loop(_k, _jk, _accu) {
                      while(true) {
                        var accu = _accu;
                        var jk = _jk;
                        var k = _k;
                        if (k >= threshold) {
                          return accu;
                        }
                        _accu = Curry._2(funarg.$star$tilde, accu, Curry._2(funarg.$star$star$tilde, Caml_array.get(c, k), jk));
                        _jk = Belenios_platform__Platform.Z.$star(jk, jj);
                        _k = k + 1 | 0;
                        continue ;
                      };
                    }
                    }(c));
                    var computed_gsij = loop(0, Belenios_platform__Platform.Z.one, funarg.one);
                    _vk = Curry._2(funarg.$star$tilde, vk, computed_gsij);
                    _i = i + 1 | 0;
                    continue ;
                  };
                }));
  };
  var check_single = function (param) {
    var y = param.trustee_public_key;
    var trustee_pok = param.trustee_pok;
    if (!Curry._1(funarg.check, y)) {
      return false;
    }
    var response = trustee_pok.response;
    var challenge = trustee_pok.challenge;
    if (!Belenios_core__Common.check_modulo(funarg.q, challenge)) {
      return false;
    }
    if (!Belenios_core__Common.check_modulo(funarg.q, response)) {
      return false;
    }
    var commitment = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, response), Curry._2(funarg.$star$star$tilde, y, challenge));
    var zkp = "pok|" + (funarg.description + ("|" + (Curry._1(funarg.to_string, y) + "|")));
    return Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(funarg.hash, zkp, [commitment]));
  };
  var check = function (trustees) {
    return Curry._2(Belenios_core__Common.List.for_all, (function (param) {
                  if (param.NAME === "Pedersen") {
                    var t = param.VAL;
                    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, verify_cert, t.t_certs)) {
                      return false;
                    }
                    var certs = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                                          return Belenios_core__Common.sread(funarg.of_string, param);
                                        }), x.s_message);
                          }), t.t_certs);
                    if (!Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (cert, x) {
                              return verify(cert.cert_verification, x);
                            }), certs, t.t_coefexps)) {
                      return false;
                    }
                    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                            return Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                                          return Belenios_core__Common.sread(funarg.of_string, param);
                                        }), x.s_message).coefexps;
                          }), t.t_coefexps);
                    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, check_single, t.t_verification_keys)) {
                      return false;
                    }
                    var computed_vks = compute_verification_keys$1(coefexps);
                    if (t.t_threshold === Caml_array.get(coefexps, 0).length) {
                      return Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (vk, computed_vk) {
                                    return Curry._2(funarg.$eq$tilde, vk.trustee_public_key, computed_vk);
                                  }), t.t_verification_keys, computed_vks);
                    } else {
                      return false;
                    }
                  } else {
                    return check_single(param.VAL);
                  }
                }), trustees);
  };
  var step1 = function (param) {
    var seed = Curry._1(funarg$2.genkey, undefined);
    var sk = Curry._1(funarg$2.derive_sk, seed);
    var dk = Curry._1(funarg$2.derive_dk, seed);
    var cert = Curry._2(funarg$2.make_cert, sk, dk);
    return [
            seed,
            cert
          ];
  };
  var step1_check = function (cert) {
    return Curry._1(funarg$2.verify_cert, cert);
  };
  var step2 = function (param) {
    Curry._2(Belenios_core__Common_types.$$Array.iteri, (function (i, cert) {
            if (Curry._1(funarg$2.verify_cert, cert)) {
              return ;
            }
            var msg = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "certificate ",
                        _1: {
                          TAG: /* Int */4,
                          _0: /* Int_d */0,
                          _1: /* No_padding */0,
                          _2: /* No_precision */0,
                          _3: {
                            TAG: /* String_literal */11,
                            _0: " does not validate",
                            _1: /* End_of_format */0
                          }
                        }
                      },
                      _1: "certificate %d does not validate"
                    }), i + 1 | 0);
            throw {
                  RE_EXN_ID: PedersenFailure,
                  _1: msg,
                  Error: new Error()
                };
          }), param.certs);
  };
  var eval_poly = function (polynomial, x) {
    var cur = Belenios_platform__Platform.Z.one;
    var res = Belenios_platform__Platform.Z.zero;
    for(var i = 0 ,i_finish = polynomial.length; i < i_finish; ++i){
      res = Belenios_platform__Platform.Z.$plus(res, Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$star(cur, Caml_array.get(polynomial, i)), funarg.q));
      cur = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$star(cur, x), funarg.q);
    }
    return res;
  };
  var step3 = function (certs, seed, threshold) {
    var n = certs.certs.length;
    step2(certs);
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), certs.certs);
    var sk = Curry._1(funarg$2.derive_sk, seed);
    var dk = Curry._1(funarg$2.derive_dk, seed);
    var vk = Curry._2(funarg.$star$star$tilde, funarg.g, sk);
    var ek = Curry._2(funarg.$star$star$tilde, funarg.g, dk);
    var i = Belenios_core__Common_types.$$Array.findi((function (i, cert) {
            if (Curry._2(funarg.$eq$tilde, cert.cert_verification, vk) && Curry._2(funarg.$eq$tilde, cert.cert_encryption, ek)) {
              return i + 1 | 0;
            }
            
          }), certs$1);
    if (i === undefined) {
      throw {
            RE_EXN_ID: PedersenFailure,
            _1: "could not find my certificate",
            Error: new Error()
          };
    }
    var polynomial = Caml_array.make(threshold, Belenios_platform__Platform.Z.zero);
    var fill_polynomial = function (_i) {
      while(true) {
        var i = _i;
        if (i >= threshold) {
          return ;
        }
        var a = Curry._1(funarg$1.random, funarg.q);
        Caml_array.set(polynomial, i, a);
        _i = i + 1 | 0;
        continue ;
      };
    };
    fill_polynomial(0);
    var x = Curry._3(funarg$3.send, sk, ek, Belenios_core__Serializable_j.string_of_raw_polynomial({
              polynomial: polynomial
            }));
    var p_polynomial = Belenios_core__Serializable_j.string_of_encrypted_msg((function (param) {
            return Belenios_core__Common.swrite(funarg.to_string, param);
          }), x);
    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Curry._2(funarg.$star$star$tilde, funarg.g, x);
          }), polynomial);
    var coefexps$1 = Belenios_core__Serializable_j.string_of_raw_coefexps((function (param) {
            return Belenios_core__Common.swrite(funarg.to_string, param);
          }), {
          coefexps: coefexps
        });
    var p_coefexps = Curry._2(funarg$2.sign, sk, coefexps$1);
    var p_secrets = Caml_array.make(n, "");
    var fill_secrets = function (_j) {
      while(true) {
        var j = _j;
        if (j >= n) {
          return ;
        }
        var secret = eval_poly(polynomial, Belenios_platform__Platform.Z.of_int(j + 1 | 0));
        var secret$1 = Belenios_core__Serializable_j.string_of_secret({
              secret: secret
            });
        var x = Curry._3(funarg$3.send, sk, Caml_array.get(certs$1, j).cert_encryption, secret$1);
        Caml_array.set(p_secrets, j, Belenios_core__Serializable_j.string_of_encrypted_msg((function (param) {
                    return Belenios_core__Common.swrite(funarg.to_string, param);
                  }), x));
        _j = j + 1 | 0;
        continue ;
      };
    };
    fill_secrets(0);
    return {
            p_polynomial: p_polynomial,
            p_secrets: p_secrets,
            p_coefexps: p_coefexps
          };
  };
  var step3_check = function (certs, i, polynomial) {
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), certs.certs);
    return Curry._2(funarg$2.verify, Caml_array.get(certs$1, i).cert_verification, polynomial.p_coefexps);
  };
  var step4 = function (certs, polynomials) {
    var n = certs.certs.length;
    step2(certs);
    if (n !== polynomials.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              344,
              4
            ],
            Error: new Error()
          };
    }
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), certs.certs);
    var vi_coefexps = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return x.p_coefexps;
          }), polynomials);
    Curry._2(Belenios_core__Common_types.$$Array.iteri, (function (i, x) {
            if (Curry._2(funarg$2.verify, Caml_array.get(certs$1, i).cert_verification, x)) {
              return ;
            }
            var msg = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "coefexps ",
                        _1: {
                          TAG: /* Int */4,
                          _0: /* Int_d */0,
                          _1: /* No_padding */0,
                          _2: /* No_precision */0,
                          _3: {
                            TAG: /* String_literal */11,
                            _0: " does not validate",
                            _1: /* End_of_format */0
                          }
                        }
                      },
                      _1: "coefexps %d does not validate"
                    }), i + 1 | 0);
            throw {
                  RE_EXN_ID: PedersenFailure,
                  _1: msg,
                  Error: new Error()
                };
          }), vi_coefexps);
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (j) {
                  var vi_polynomial = Caml_array.get(polynomials, j).p_polynomial;
                  var vi_secrets = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
                          return Caml_array.get(Caml_array.get(polynomials, i).p_secrets, j);
                        }));
                  return {
                          vi_polynomial: vi_polynomial,
                          vi_secrets: vi_secrets,
                          vi_coefexps: vi_coefexps
                        };
                }));
  };
  var step5 = function (certs, seed, vinput) {
    var n = certs.certs.length;
    step2(certs);
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), certs.certs);
    var sk = Curry._1(funarg$2.derive_sk, seed);
    var dk = Curry._1(funarg$2.derive_dk, seed);
    var vk = Curry._2(funarg.$star$star$tilde, funarg.g, sk);
    var ek = Curry._2(funarg.$star$star$tilde, funarg.g, dk);
    var j = Belenios_core__Common_types.$$Array.findi((function (i, cert) {
            if (Curry._2(funarg.$eq$tilde, cert.cert_verification, vk) && Curry._2(funarg.$eq$tilde, cert.cert_encryption, ek)) {
              return i + 1 | 0;
            }
            
          }), certs$1);
    var j$1;
    if (j !== undefined) {
      j$1 = Belenios_platform__Platform.Z.of_int(j);
    } else {
      throw {
            RE_EXN_ID: PedersenFailure,
            _1: "could not find my certificate",
            Error: new Error()
          };
    }
    var match = Belenios_core__Serializable_j.raw_polynomial_of_string(Curry._3(funarg$3.recv, dk, vk, Belenios_core__Serializable_j.encrypted_msg_of_string((function (param) {
                    return Belenios_core__Common.sread(funarg.of_string, param);
                  }), vinput.vi_polynomial)));
    var threshold = match.polynomial.length;
    if (n !== vinput.vi_secrets.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              382,
              4
            ],
            Error: new Error()
          };
    }
    var secrets = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            return Belenios_core__Serializable_j.secret_of_string(Curry._3(funarg$3.recv, dk, Caml_array.get(certs$1, i).cert_verification, Belenios_core__Serializable_j.encrypted_msg_of_string((function (param) {
                                  return Belenios_core__Common.sread(funarg.of_string, param);
                                }), Caml_array.get(vinput.vi_secrets, i)))).secret;
          }));
    if (n !== vinput.vi_coefexps.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              392,
              4
            ],
            Error: new Error()
          };
    }
    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            var x = Caml_array.get(vinput.vi_coefexps, i);
            if (!Curry._2(funarg$2.verify, Caml_array.get(certs$1, i).cert_verification, x)) {
              throw {
                    RE_EXN_ID: PedersenFailure,
                    _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "coefexps ",
                                _1: {
                                  TAG: /* Int */4,
                                  _0: /* Int_d */0,
                                  _1: /* No_padding */0,
                                  _2: /* No_precision */0,
                                  _3: {
                                    TAG: /* String_literal */11,
                                    _0: " does not validate",
                                    _1: /* End_of_format */0
                                  }
                                }
                              },
                              _1: "coefexps %d does not validate"
                            }), i + 1 | 0),
                    Error: new Error()
                  };
            }
            var res = Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                    return Belenios_core__Common.sread(funarg.of_string, param);
                  }), x.s_message).coefexps;
            if (res.length !== threshold) {
              throw {
                    RE_EXN_ID: "Assert_failure",
                    _1: [
                      "trustees.ml",
                      399,
                      10
                    ],
                    Error: new Error()
                  };
            }
            return res;
          }));
    for(var i = 0; i < n; ++i){
      var c = Caml_array.get(coefexps, i);
      var loop = (function(c){
      return function loop(_k, _jk, _accu) {
        while(true) {
          var accu = _accu;
          var jk = _jk;
          var k = _k;
          if (k >= threshold) {
            return accu;
          }
          _accu = Curry._2(funarg.$star$tilde, accu, Curry._2(funarg.$star$star$tilde, Caml_array.get(c, k), jk));
          _jk = Belenios_platform__Platform.Z.$star(jk, j$1);
          _k = k + 1 | 0;
          continue ;
        };
      }
      }(c));
      var computed_gsij = loop(0, Belenios_platform__Platform.Z.one, funarg.one);
      if (!Curry._2(funarg.$eq$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, Caml_array.get(secrets, i)), computed_gsij)) {
        throw {
              RE_EXN_ID: PedersenFailure,
              _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String_literal */11,
                          _0: "secret ",
                          _1: {
                            TAG: /* Int */4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: /* String_literal */11,
                              _0: " does not validate",
                              _1: /* End_of_format */0
                            }
                          }
                        },
                        _1: "secret %d does not validate"
                      }), i + 1 | 0),
              Error: new Error()
            };
      }
      
    }
    var pdk_decryption_key = Curry._3(Belenios_core__Common_types.$$Array.fold_left, Belenios_platform__Platform.Z.$plus, Belenios_platform__Platform.Z.zero, secrets);
    var pdk = Belenios_core__Serializable_j.string_of_partial_decryption_key({
          pdk_decryption_key: pdk_decryption_key
        });
    var vo_public_key = prove(pdk_decryption_key);
    var private_key = Curry._3(funarg$3.send, sk, ek, pdk);
    var vo_private_key = Belenios_core__Serializable_j.string_of_encrypted_msg((function (param) {
            return Belenios_core__Common.swrite(funarg.to_string, param);
          }), private_key);
    return {
            vo_private_key: vo_private_key,
            vo_public_key: vo_public_key
          };
  };
  var step5_check = function (certs, i, polynomials, voutput) {
    var n = certs.certs.length;
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), certs.certs);
    if (n !== polynomials.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              424,
              4
            ],
            Error: new Error()
          };
    }
    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            var x = Caml_array.get(polynomials, i).p_coefexps;
            if (!Curry._2(funarg$2.verify, Caml_array.get(certs$1, i).cert_verification, x)) {
              throw {
                    RE_EXN_ID: PedersenFailure,
                    _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "coefexps ",
                                _1: {
                                  TAG: /* Int */4,
                                  _0: /* Int_d */0,
                                  _1: /* No_padding */0,
                                  _2: /* No_precision */0,
                                  _3: {
                                    TAG: /* String_literal */11,
                                    _0: " does not validate",
                                    _1: /* End_of_format */0
                                  }
                                }
                              },
                              _1: "coefexps %d does not validate"
                            }), i + 1 | 0),
                    Error: new Error()
                  };
            }
            return Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message).coefexps;
          }));
    var computed_vk = Caml_array.get(compute_verification_keys(coefexps), i);
    if (check({
            hd: {
              NAME: "Single",
              VAL: voutput.vo_public_key
            },
            tl: /* [] */0
          })) {
      return Curry._2(funarg.$eq$tilde, voutput.vo_public_key.trustee_public_key, computed_vk);
    } else {
      return false;
    }
  };
  var step6 = function (certs, polynomials, voutputs) {
    var n = certs.certs.length;
    step2(certs);
    var t_certs = certs.certs;
    var certs$1 = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message);
          }), t_certs);
    if (n !== polynomials.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              442,
              4
            ],
            Error: new Error()
          };
    }
    if (n !== voutputs.length) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              443,
              4
            ],
            Error: new Error()
          };
    }
    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (i) {
            var x = Caml_array.get(polynomials, i).p_coefexps;
            if (!Curry._2(funarg$2.verify, Caml_array.get(certs$1, i).cert_verification, x)) {
              throw {
                    RE_EXN_ID: PedersenFailure,
                    _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "coefexps ",
                                _1: {
                                  TAG: /* Int */4,
                                  _0: /* Int_d */0,
                                  _1: /* No_padding */0,
                                  _2: /* No_precision */0,
                                  _3: {
                                    TAG: /* String_literal */11,
                                    _0: " does not validate",
                                    _1: /* End_of_format */0
                                  }
                                }
                              },
                              _1: "coefexps %d does not validate"
                            }), i + 1 | 0),
                    Error: new Error()
                  };
            }
            return Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                          return Belenios_core__Common.sread(funarg.of_string, param);
                        }), x.s_message).coefexps;
          }));
    var computed_vks = compute_verification_keys(coefexps);
    for(var j = 0; j < n; ++j){
      var voutput = Caml_array.get(voutputs, j);
      if (!check({
              hd: {
                NAME: "Single",
                VAL: voutput.vo_public_key
              },
              tl: /* [] */0
            })) {
        throw {
              RE_EXN_ID: PedersenFailure,
              _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String_literal */11,
                          _0: "pok ",
                          _1: {
                            TAG: /* Int */4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: /* String_literal */11,
                              _0: " does not validate",
                              _1: /* End_of_format */0
                            }
                          }
                        },
                        _1: "pok %d does not validate"
                      }), j + 1 | 0),
              Error: new Error()
            };
      }
      if (!Curry._2(funarg.$eq$tilde, voutput.vo_public_key.trustee_public_key, Caml_array.get(computed_vks, j))) {
        throw {
              RE_EXN_ID: PedersenFailure,
              _1: Curry._1(Stdlib__Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String_literal */11,
                          _0: "verification key ",
                          _1: {
                            TAG: /* Int */4,
                            _0: /* Int_d */0,
                            _1: /* No_padding */0,
                            _2: /* No_precision */0,
                            _3: {
                              TAG: /* String_literal */11,
                              _0: " is incorrect",
                              _1: /* End_of_format */0
                            }
                          }
                        },
                        _1: "verification key %d is incorrect"
                      }), j + 1 | 0),
              Error: new Error()
            };
      }
      
    }
    return {
            t_threshold: Caml_array.get(coefexps, 0).length,
            t_certs: t_certs,
            t_coefexps: Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                    return x.p_coefexps;
                  }), polynomials),
            t_verification_keys: Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                    return x.vo_public_key;
                  }), voutputs)
          };
  };
  return {
          step1: step1,
          step1_check: step1_check,
          step2: step2,
          step3: step3,
          step3_check: step3_check,
          step4: step4,
          step5: step5,
          step5_check: step5_check,
          step6: step6
        };
}

function MakeCombinator(funarg) {
  var verify = function (vk, param) {
    var match = param.s_signature;
    var response = match.response;
    var challenge = match.challenge;
    if (!Belenios_core__Common.check_modulo(funarg.q, challenge)) {
      return false;
    }
    if (!Belenios_core__Common.check_modulo(funarg.q, response)) {
      return false;
    }
    var commitment = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, response), Curry._2(funarg.$star$star$tilde, vk, challenge));
    var prefix = "sigmsg|" + (param.s_message + "|");
    return Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(funarg.hash, prefix, [commitment]));
  };
  var verify_cert = function (x) {
    var keys = Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
            return Belenios_core__Common.sread(funarg.of_string, param);
          }), x.s_message);
    return verify(keys.cert_verification, x);
  };
  var compute_verification_keys = function (coefexps) {
    var n = coefexps.length;
    if (n <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              47,
              4
            ],
            Error: new Error()
          };
    }
    var threshold = Caml_array.get(coefexps, 0).length;
    if (threshold <= 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "trustees.ml",
              49,
              4
            ],
            Error: new Error()
          };
    }
    return Curry._2(Belenios_core__Common_types.$$Array.init, n, (function (j) {
                  var jj = Belenios_platform__Platform.Z.of_int(j + 1 | 0);
                  var _i = 0;
                  var _vk = funarg.one;
                  while(true) {
                    var vk = _vk;
                    var i = _i;
                    if (i >= n) {
                      return vk;
                    }
                    var c = Caml_array.get(coefexps, i);
                    if (threshold !== c.length) {
                      throw {
                            RE_EXN_ID: "Assert_failure",
                            _1: [
                              "trustees.ml",
                              55,
                              12
                            ],
                            Error: new Error()
                          };
                    }
                    var loop = (function(c){
                    return function loop(_k, _jk, _accu) {
                      while(true) {
                        var accu = _accu;
                        var jk = _jk;
                        var k = _k;
                        if (k >= threshold) {
                          return accu;
                        }
                        _accu = Curry._2(funarg.$star$tilde, accu, Curry._2(funarg.$star$star$tilde, Caml_array.get(c, k), jk));
                        _jk = Belenios_platform__Platform.Z.$star(jk, jj);
                        _k = k + 1 | 0;
                        continue ;
                      };
                    }
                    }(c));
                    var computed_gsij = loop(0, Belenios_platform__Platform.Z.one, funarg.one);
                    _vk = Curry._2(funarg.$star$tilde, vk, computed_gsij);
                    _i = i + 1 | 0;
                    continue ;
                  };
                }));
  };
  var check_single = function (param) {
    var y = param.trustee_public_key;
    var trustee_pok = param.trustee_pok;
    if (!Curry._1(funarg.check, y)) {
      return false;
    }
    var response = trustee_pok.response;
    var challenge = trustee_pok.challenge;
    if (!Belenios_core__Common.check_modulo(funarg.q, challenge)) {
      return false;
    }
    if (!Belenios_core__Common.check_modulo(funarg.q, response)) {
      return false;
    }
    var commitment = Curry._2(funarg.$star$tilde, Curry._2(funarg.$star$star$tilde, funarg.g, response), Curry._2(funarg.$star$star$tilde, y, challenge));
    var zkp = "pok|" + (funarg.description + ("|" + (Curry._1(funarg.to_string, y) + "|")));
    return Belenios_platform__Platform.Z.$eq$percent(challenge, Curry._2(funarg.hash, zkp, [commitment]));
  };
  var check = function (trustees) {
    return Curry._2(Belenios_core__Common.List.for_all, (function (param) {
                  if (param.NAME === "Pedersen") {
                    var t = param.VAL;
                    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, verify_cert, t.t_certs)) {
                      return false;
                    }
                    var certs = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                            return Belenios_core__Serializable_j.cert_keys_of_string((function (param) {
                                          return Belenios_core__Common.sread(funarg.of_string, param);
                                        }), x.s_message);
                          }), t.t_certs);
                    if (!Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (cert, x) {
                              return verify(cert.cert_verification, x);
                            }), certs, t.t_coefexps)) {
                      return false;
                    }
                    var coefexps = Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                            return Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                                          return Belenios_core__Common.sread(funarg.of_string, param);
                                        }), x.s_message).coefexps;
                          }), t.t_coefexps);
                    if (!Curry._2(Belenios_core__Common_types.$$Array.for_all, check_single, t.t_verification_keys)) {
                      return false;
                    }
                    var computed_vks = compute_verification_keys(coefexps);
                    if (t.t_threshold === Caml_array.get(coefexps, 0).length) {
                      return Curry._3(Belenios_core__Common_types.$$Array.for_all2, (function (vk, computed_vk) {
                                    return Curry._2(funarg.$eq$tilde, vk.trustee_public_key, computed_vk);
                                  }), t.t_verification_keys, computed_vks);
                    } else {
                      return false;
                    }
                  } else {
                    return check_single(param.VAL);
                  }
                }), trustees);
  };
  var combine_keys = function (trustees) {
    return Curry._3(Belenios_core__Common.List.fold_left, funarg.$star$tilde, funarg.one, Curry._2(Belenios_core__Common.List.map, (function (param) {
                      if (param.NAME === "Pedersen") {
                        return Curry._3(Belenios_core__Common_types.$$Array.fold_left, (function (accu, x) {
                                      return Curry._2(funarg.$star$tilde, accu, Caml_array.get(x, 0));
                                    }), funarg.one, Curry._2(Belenios_core__Common_types.$$Array.map, (function (x) {
                                          return Belenios_core__Serializable_j.raw_coefexps_of_string((function (param) {
                                                        return Belenios_core__Common.sread(funarg.of_string, param);
                                                      }), x.s_message).coefexps;
                                        }), param.VAL.t_coefexps));
                      } else {
                        return param.VAL.trustee_public_key;
                      }
                    }), trustees));
  };
  var lagrange = function (indexes, j) {
    return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, k) {
                  var kj = k - j | 0;
                  if (kj === 0) {
                    return accu;
                  } else {
                    return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$star(Belenios_platform__Platform.Z.$star(accu, Belenios_platform__Platform.Z.of_int(k)), Belenios_platform__Platform.Z.invert(Belenios_platform__Platform.Z.of_int(kj), funarg.q)), funarg.q);
                  }
                }), Belenios_platform__Platform.Z.one, indexes);
  };
  var combine_factors = function (trustees, check, partial_decryptions) {
    var dummy = partial_decryptions ? Belenios_core__Common_types.Shape.map((function (param) {
              return funarg.one;
            }), partial_decryptions.hd.owned_payload.decryption_factors) : Stdlib.failwith("no partial decryptions");
    var fold = function (pds_with_ids) {
      var indexes = Curry._2(Belenios_core__Common.List.map, (function (prim) {
              return prim[0];
            }), pds_with_ids);
      return Curry._3(Belenios_core__Common.List.fold_left, (function (a, param) {
                    var l = lagrange(indexes, param[0]);
                    return Belenios_core__Common_types.Shape.map2((function (x, y) {
                                  return Curry._2(funarg.$star$tilde, x, Curry._2(funarg.$star$star$tilde, y, l));
                                }), a, param[1].decryption_factors);
                  }), dummy, pds_with_ids);
    };
    var r = Belenios_core__Util.compute_synthetic_factors(trustees, check, partial_decryptions, fold);
    if (r.TAG === /* Ok */0) {
      return {
              TAG: /* Ok */0,
              _0: Curry._3(Belenios_core__Common.List.fold_left, (function (a, b) {
                      return Belenios_core__Common_types.Shape.map2(funarg.$star$tilde, a, b);
                    }), dummy, r._0)
            };
    } else {
      return r;
    }
  };
  return {
          check: check,
          combine_keys: combine_keys,
          combine_factors: combine_factors
        };
}

export {
  MakeSimple ,
  MakePKI ,
  MakeChannels ,
  PedersenFailure ,
  MakePedersen ,
  MakeCombinator ,
}
/* Belenios_core__Common Not a pure module */
