// Generated by Melange

import * as Caml from "melange.runtime/caml.js";
import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_bytes from "melange.runtime/caml_bytes.js";
import * as Caml_int64 from "melange.runtime/caml_int64.js";
import * as Caml_format from "melange.runtime/caml_format.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Sys from "melange/./sys.js";
import * as Stdlib__Bytes from "melange/./bytes.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_core__Common_types from "./common_types.js";
import * as Belenios_core__Serializable_j from "./serializable_j.js";

var block_sizeL = [
  0,
  512
];

function write_to_bytes(buffer, pos, str) {
  Stdlib__Bytes.blit_string(str, 0, buffer, pos, str.length);
}

function compute_checksum(x) {
  var sum = 0;
  for(var i = 0 ,i_finish = x.length; i < i_finish; ++i){
    sum = sum + Caml_bytes.get(x, i) | 0;
  }
  return Curry._1(Stdlib__Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* Int */4,
                    _0: /* Int_o */10,
                    _1: {
                      TAG: /* Lit_padding */0,
                      _0: /* Zeros */2,
                      _1: 6
                    },
                    _2: /* No_precision */0,
                    _3: {
                      TAG: /* String_literal */11,
                      _0: "\0 ",
                      _1: /* End_of_format */0
                    }
                  },
                  _1: "%06o\0 "
                }), sum);
}

var block_size = 512;

function MakeReader(funarg) {
  var let$star = funarg.bind;
  var raw_read_header = function (f, buffer) {
    return Curry._2(let$star, Curry._2(funarg.read_block, f, buffer), (function (param) {
                  var j = Stdlib__Bytes.index_from(buffer, 0, /* '\000' */0);
                  var filename = Stdlib__Bytes.sub_string(buffer, 0, j - 0 | 0);
                  var x = Stdlib__Bytes.sub_string(buffer, 124, 11);
                  var length = Caml_format.caml_int64_of_string("0o" + x);
                  return Curry._1(funarg.$$return, [
                              filename,
                              length
                            ]);
                }));
  };
  var raw_read_body = function (f, buffer, length) {
    if (!Caml.i64_le(length, Caml_int64.of_int32(Stdlib__Sys.max_string_length))) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "archive.ml",
              70,
              4
            ],
            Error: new Error()
          };
    }
    var length$1 = Caml_int64.to_int32(length);
    var result = Caml_bytes.caml_create_bytes(length$1);
    var loop = function (offset, length) {
      if (length > 512) {
        return Curry._2(let$star, Curry._2(funarg.read_block, f, buffer), (function (param) {
                      Stdlib__Bytes.blit(buffer, 0, result, offset, 512);
                      return loop(offset + 512 | 0, length - 512 | 0);
                    }));
      } else if (length > 0) {
        return Curry._2(let$star, Curry._2(funarg.read_block, f, buffer), (function (param) {
                      Stdlib__Bytes.blit(buffer, 0, result, offset, length);
                      return Curry._1(funarg.$$return, Stdlib__Bytes.to_string(result));
                    }));
      } else {
        return Curry._1(funarg.$$return, Stdlib__Bytes.to_string(result));
      }
    };
    return loop(0, length$1);
  };
  var read_header = function (f) {
    var buffer = Caml_bytes.caml_create_bytes(512);
    return Curry._2(let$star, raw_read_header(f, buffer), (function (param) {
                  var filename = param[0];
                  return Curry._2(let$star, raw_read_body(f, buffer, param[1]), (function (header) {
                                if (filename !== "BELENIOS") {
                                  return Curry._1(funarg.fail, {
                                              RE_EXN_ID: Stdlib.Failure,
                                              _1: "ill-formed archive header found"
                                            });
                                }
                                var header$1 = Belenios_core__Serializable_j.archive_header_of_string(header);
                                if (header$1.version === 1) {
                                  return Curry._1(funarg.$$return, header$1);
                                } else {
                                  return Curry._1(funarg.fail, {
                                              RE_EXN_ID: Stdlib.Failure,
                                              _1: "unsupported archive header"
                                            });
                                }
                              }));
                }));
  };
  var read_record = function (f) {
    var buffer = Caml_bytes.caml_create_bytes(512);
    return Curry._2(let$star, raw_read_header(f, buffer), (function (param) {
                  var location_length = param[1];
                  var filename = param[0];
                  return Curry._2(let$star, Curry._1(funarg.get_pos, f), (function (location_offset) {
                                var j = Curry._3(Belenios_core__Common.$$String.index_from, filename, 0, /* '.' */46) + 1 | 0;
                                var k = Curry._3(Belenios_core__Common.$$String.index_from, filename, j, /* '.' */46) + 1 | 0;
                                var match = Curry._3(Belenios_core__Common.$$String.sub, filename, j, (k - j | 0) - 1 | 0);
                                var typ;
                                switch (match) {
                                  case "data" :
                                      typ = "Data";
                                      break;
                                  case "event" :
                                      typ = "Event";
                                      break;
                                  default:
                                    throw {
                                          RE_EXN_ID: "Assert_failure",
                                          _1: [
                                            "archive.ml",
                                            109,
                                            15
                                          ],
                                          Error: new Error()
                                        };
                                }
                                var hash = Belenios_core__Common_types.Hash.of_hex(Curry._3(Belenios_core__Common.$$String.sub, filename, 0, (j - 0 | 0) - 1 | 0));
                                var $$location = {
                                  location_offset: location_offset,
                                  location_length: location_length
                                };
                                var tmp;
                                if (typ === "Data") {
                                  var q = Caml_int64.div(location_length, block_sizeL);
                                  var r = Caml_int64.mod_(location_length, block_sizeL);
                                  var blocks = Caml_int64.add(q, Caml.i64_eq(r, Caml_int64.zero) ? Caml_int64.zero : Caml_int64.one);
                                  var new_pos = Caml_int64.add(location_offset, Caml_int64.mul(blocks, block_sizeL));
                                  tmp = Curry._2(let$star, Curry._2(funarg.set_pos, f, new_pos), (function (param) {
                                          return Curry._1(funarg.$$return, /* Data */0);
                                        }));
                                } else {
                                  tmp = Curry._2(let$star, raw_read_body(f, buffer, location_length), (function (body) {
                                          return Curry._1(funarg.$$return, /* Event */{
                                                      _0: Belenios_core__Serializable_j.event_of_string(body)
                                                    });
                                        }));
                                }
                                return Curry._2(let$star, tmp, (function (typ) {
                                              return Curry._1(funarg.$$return, {
                                                          typ: typ,
                                                          hash: hash,
                                                          location: $$location
                                                        });
                                            }));
                              }));
                }));
  };
  return {
          read_header: read_header,
          read_record: read_record
        };
}

function MakeWriter(funarg) {
  var let$star = funarg.bind;
  var raw_write_header = function (f, buffer, filename, length, timestamp) {
    write_to_bytes(buffer, 0, filename);
    write_to_bytes(buffer, 100, "0000644");
    write_to_bytes(buffer, 108, "0000000");
    write_to_bytes(buffer, 116, "0000000");
    write_to_bytes(buffer, 124, Curry._1(Stdlib__Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* Int64 */7,
                    _0: /* Int_o */10,
                    _1: {
                      TAG: /* Lit_padding */0,
                      _0: /* Zeros */2,
                      _1: 11
                    },
                    _2: /* No_precision */0,
                    _3: /* End_of_format */0
                  },
                  _1: "%011Lo"
                }), length));
    write_to_bytes(buffer, 136, Curry._1(Stdlib__Printf.sprintf(/* Format */{
                  _0: {
                    TAG: /* Int64 */7,
                    _0: /* Int_o */10,
                    _1: {
                      TAG: /* Lit_padding */0,
                      _0: /* Zeros */2,
                      _1: 11
                    },
                    _2: /* No_precision */0,
                    _3: /* End_of_format */0
                  },
                  _1: "%011Lo"
                }), timestamp));
    write_to_bytes(buffer, 148, "        ");
    write_to_bytes(buffer, 156, "0");
    write_to_bytes(buffer, 148, compute_checksum(buffer));
    return Curry._2(funarg.write_block, f, buffer);
  };
  var raw_write_body = function (f, buffer, body) {
    var loop = function (offset, length) {
      if (length > 512) {
        Stdlib__Bytes.blit_string(body, offset, buffer, 0, 512);
        return Curry._2(let$star, Curry._2(funarg.write_block, f, buffer), (function (param) {
                      return loop(offset + 512 | 0, length - 512 | 0);
                    }));
      }
      if (length <= 0) {
        return Curry._1(funarg.$$return, undefined);
      }
      Stdlib__Bytes.blit_string(body, offset, buffer, 0, length);
      for(var i = length; i <= 511; ++i){
        Caml_bytes.set(buffer, i, /* '\000' */0);
      }
      return Curry._2(funarg.write_block, f, buffer);
    };
    return loop(0, body.length);
  };
  var write_header = function (f, header) {
    var buffer = Stdlib__Bytes.make(512, /* '\000' */0);
    var header_s = Belenios_core__Serializable_j.string_of_archive_header(header);
    var header_n = Caml_int64.of_int32(header_s.length);
    return Curry._2(let$star, raw_write_header(f, buffer, "BELENIOS", header_n, header.timestamp), (function (param) {
                  return raw_write_body(f, buffer, header_s);
                }));
  };
  var write_record = function (f, timestamp, typ, payload) {
    var location_length = Caml_int64.of_int32(payload.length);
    var hash = Belenios_core__Common_types.Hash.hash_string(payload);
    var typ$1 = typ ? "event" : "data";
    var filename = Curry._2(Stdlib__Printf.sprintf(/* Format */{
              _0: {
                TAG: /* String */2,
                _0: /* No_padding */0,
                _1: {
                  TAG: /* Char_literal */12,
                  _0: /* '.' */46,
                  _1: {
                    TAG: /* String */2,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* String_literal */11,
                      _0: ".json",
                      _1: /* End_of_format */0
                    }
                  }
                }
              },
              _1: "%s.%s.json"
            }), Belenios_core__Common_types.Hash.to_hex(hash), typ$1);
    var buffer = Stdlib__Bytes.make(512, /* '\000' */0);
    return Curry._2(let$star, raw_write_header(f, buffer, filename, location_length, timestamp), (function (param) {
                  return Curry._2(let$star, Curry._1(funarg.get_pos, f), (function (location_offset) {
                                return Curry._2(let$star, raw_write_body(f, buffer, payload), (function (param) {
                                              var $$location = {
                                                location_offset: location_offset,
                                                location_length: location_length
                                              };
                                              return Curry._1(funarg.$$return, {
                                                          typ: typ,
                                                          hash: hash,
                                                          location: $$location
                                                        });
                                            }));
                              }));
                }));
  };
  return {
          write_header: write_header,
          write_record: write_record
        };
}

function MakeArchiver(funarg, funarg$1) {
  var let$star = funarg.bind;
  var get_hash = function (hash) {
    return Curry._2(let$star, Curry._1(funarg.get_hash, hash), (function (x) {
                  if (x !== undefined) {
                    var actual_hash = Belenios_core__Common_types.Hash.hash_string(x);
                    if (Caml_obj.caml_equal(hash, actual_hash)) {
                      return Curry._1(funarg.$$return, x);
                    }
                    var msg = Curry._2(Stdlib__Printf.sprintf(/* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "hash ",
                                _1: {
                                  TAG: /* String */2,
                                  _0: /* No_padding */0,
                                  _1: {
                                    TAG: /* String_literal */11,
                                    _0: " found instead of ",
                                    _1: {
                                      TAG: /* String */2,
                                      _0: /* No_padding */0,
                                      _1: /* End_of_format */0
                                    }
                                  }
                                }
                              },
                              _1: "hash %s found instead of %s"
                            }), Belenios_core__Common_types.Hash.to_hex(actual_hash), Belenios_core__Common_types.Hash.to_hex(hash));
                    return Curry._1(funarg.fail, {
                                RE_EXN_ID: Stdlib.Failure,
                                _1: msg
                              });
                  }
                  var msg$1 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                            _0: {
                              TAG: /* String_literal */11,
                              _0: "hash ",
                              _1: {
                                TAG: /* String */2,
                                _0: /* No_padding */0,
                                _1: {
                                  TAG: /* String_literal */11,
                                  _0: " not found",
                                  _1: /* End_of_format */0
                                }
                              }
                            },
                            _1: "hash %s not found"
                          }), Belenios_core__Common_types.Hash.to_hex(hash));
                  return Curry._1(funarg.fail, {
                              RE_EXN_ID: Stdlib.Failure,
                              _1: msg$1
                            });
                }));
  };
  var get_payload = function ($$event) {
    var hash = $$event.event_payload;
    if (hash !== undefined) {
      return get_hash(Caml_option.valFromOption(hash));
    }
    var msg = Curry._1(Stdlib__Printf.sprintf(/* Format */{
              _0: {
                TAG: /* String_literal */11,
                _0: "missing payload in event ",
                _1: {
                  TAG: /* String */2,
                  _0: /* No_padding */0,
                  _1: /* End_of_format */0
                }
              },
              _1: "missing payload in event %s"
            }), Belenios_core__Serializable_j.string_of_event_type($$event.event_typ));
    return Curry._1(funarg.fail, {
                RE_EXN_ID: Stdlib.Failure,
                _1: msg
              });
  };
  var write_archive = function (archive, header, last) {
    var timestamp = header.timestamp;
    return Curry._2(let$star, Curry._2(funarg$1.write_header, archive, header), (function (param) {
                  var loop = function (last, accu) {
                    var parent = last.event_parent;
                    if (parent !== undefined) {
                      return Curry._2(let$star, get_hash(Caml_option.valFromOption(parent)), (function (previous) {
                                    var previous$1 = Belenios_core__Serializable_j.event_of_string(previous);
                                    return loop(previous$1, {
                                                hd: previous$1,
                                                tl: accu
                                              });
                                  }));
                    } else {
                      return Curry._1(funarg.$$return, accu);
                    }
                  };
                  return Curry._2(let$star, loop(last, {
                                  hd: last,
                                  tl: /* [] */0
                                }), (function (events) {
                                var loop = function (height, parent, param) {
                                  if (!param) {
                                    return Curry._1(funarg.$$return, undefined);
                                  }
                                  var events = param.tl;
                                  var $$event = param.hd;
                                  var event_s = Belenios_core__Serializable_j.string_of_event($$event);
                                  var event_h = Belenios_core__Common_types.Hash.hash_string(event_s);
                                  if (Caml_obj.caml_equal($$event.event_parent, parent) && $$event.event_height === height) {
                                    var match = $$event.event_typ;
                                    var tmp;
                                    if (match === "EncryptedTally") {
                                      tmp = Curry._2(let$star, get_payload($$event), (function (payload) {
                                              var sized_et = Belenios_core__Serializable_j.sized_encrypted_tally_of_string(Belenios_core__Serializable_j.read_hash, payload);
                                              var et_h = sized_et.sized_encrypted_tally;
                                              return Curry._2(let$star, get_hash(et_h), (function (et_s) {
                                                            return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, et_s), (function (param) {
                                                                          return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, payload), (function (param) {
                                                                                        return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Event */{
                                                                                                        _0: $$event
                                                                                                      }, event_s), (function (param) {
                                                                                                      return Curry._1(funarg.$$return, undefined);
                                                                                                    }));
                                                                                      }));
                                                                        }));
                                                          }));
                                            }));
                                    } else if (match === "Shuffle" || match === "PartialDecryption") {
                                      tmp = Curry._2(let$star, get_payload($$event), (function (payload) {
                                              var owned = Belenios_core__Serializable_j.owned_of_string(Belenios_core__Serializable_j.read_hash, payload);
                                              var it_h = owned.owned_payload;
                                              return Curry._2(let$star, get_hash(it_h), (function (it_s) {
                                                            return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, it_s), (function (param) {
                                                                          return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, payload), (function (param) {
                                                                                        return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Event */{
                                                                                                        _0: $$event
                                                                                                      }, event_s), (function (param) {
                                                                                                      return Curry._1(funarg.$$return, undefined);
                                                                                                    }));
                                                                                      }));
                                                                        }));
                                                          }));
                                            }));
                                    } else if (match === "Result" || match === "Ballot") {
                                      tmp = Curry._2(let$star, get_payload($$event), (function (payload) {
                                              return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, payload), (function (param) {
                                                            return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Event */{
                                                                            _0: $$event
                                                                          }, event_s), (function (param) {
                                                                          return Curry._1(funarg.$$return, undefined);
                                                                        }));
                                                          }));
                                            }));
                                    } else if (match === "Setup") {
                                      tmp = Curry._2(let$star, get_payload($$event), (function (payload) {
                                              var setup_data = Belenios_core__Serializable_j.setup_data_of_string(payload);
                                              return Curry._2(let$star, get_hash(setup_data.setup_election), (function (election) {
                                                            return Curry._2(let$star, get_hash(setup_data.setup_trustees), (function (trustees) {
                                                                          return Curry._2(let$star, get_hash(setup_data.setup_credentials), (function (credentials) {
                                                                                        return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, election), (function (param) {
                                                                                                      return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, trustees), (function (param) {
                                                                                                                    return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, credentials), (function (param) {
                                                                                                                                  return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Data */0, payload), (function (param) {
                                                                                                                                                return Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Event */{
                                                                                                                                                                _0: $$event
                                                                                                                                                              }, event_s), (function (param) {
                                                                                                                                                              return Curry._1(funarg.$$return, undefined);
                                                                                                                                                            }));
                                                                                                                                              }));
                                                                                                                                }));
                                                                                                                  }));
                                                                                                    }));
                                                                                      }));
                                                                        }));
                                                          }));
                                            }));
                                    } else if ($$event.event_payload === undefined) {
                                      tmp = Curry._2(let$star, Curry._4(funarg$1.write_record, archive, timestamp, /* Event */{
                                                _0: $$event
                                              }, event_s), (function (param) {
                                              return Curry._1(funarg.$$return, undefined);
                                            }));
                                    } else {
                                      var msg = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                                                _0: {
                                                  TAG: /* String_literal */11,
                                                  _0: "extra payload found at height ",
                                                  _1: {
                                                    TAG: /* Int */4,
                                                    _0: /* Int_d */0,
                                                    _1: /* No_padding */0,
                                                    _2: /* No_precision */0,
                                                    _3: /* End_of_format */0
                                                  }
                                                },
                                                _1: "extra payload found at height %d"
                                              }), height);
                                      tmp = Curry._1(funarg.fail, {
                                            RE_EXN_ID: Stdlib.Failure,
                                            _1: msg
                                          });
                                    }
                                    return Curry._2(let$star, tmp, (function (param) {
                                                  return loop(height + 1 | 0, Caml_option.some(event_h), events);
                                                }));
                                  }
                                  var msg$1 = Curry._1(Stdlib__Printf.sprintf(/* Format */{
                                            _0: {
                                              TAG: /* String_literal */11,
                                              _0: "inconsistency at height ",
                                              _1: {
                                                TAG: /* Int */4,
                                                _0: /* Int_d */0,
                                                _1: /* No_padding */0,
                                                _2: /* No_precision */0,
                                                _3: /* End_of_format */0
                                              }
                                            },
                                            _1: "inconsistency at height %d"
                                          }), height);
                                  return Curry._1(funarg.fail, {
                                              RE_EXN_ID: Stdlib.Failure,
                                              _1: msg$1
                                            });
                                };
                                return loop(0, undefined, events);
                              }));
                }));
  };
  return {
          write_archive: write_archive
        };
}

export {
  block_size ,
  MakeReader ,
  MakeWriter ,
  MakeArchiver ,
}
/* Belenios_core__Common Not a pure module */
