// Generated by Melange

import * as Hex from "../../../../hex/hex.js";
import * as Curry from "melange.runtime/curry.js";
import * as Base64 from "../../../../base64/base64.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_string from "melange.runtime/caml_string.js";
import * as Stdlib__List from "melange/./list.js";
import * as Stdlib__Array from "melange/./array.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Stdlib__String from "melange/./string.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

var wrap = Belenios_platform__Platform.Z.of_string;

var unwrap = Belenios_platform__Platform.Z.to_string;

var $$Number = {
  wrap: wrap,
  unwrap: unwrap
};

function check(token) {
  var n = token.length;
  if (n < 14) {
    return false;
  }
  var _i = n - 1 | 0;
  while(true) {
    var i = _i;
    if (i < 0) {
      return true;
    }
    var match = Stdlib__String.index_opt("123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz", Caml_string.get(token, i));
    if (match === undefined) {
      return false;
    }
    _i = i - 1 | 0;
    continue ;
  };
}

function wrap$1(x) {
  if (check(x)) {
    return x;
  } else {
    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                    _0: {
                      TAG: /* Caml_string */3,
                      _0: /* No_padding */0,
                      _1: {
                        TAG: /* String_literal */11,
                        _0: " is not a valid UUID",
                        _1: /* End_of_format */0
                      }
                    },
                    _1: "%S is not a valid UUID"
                  }), x);
  }
}

function unwrap$1(x) {
  return x;
}

function check$1(x) {
  if (x.length === 64) {
    return Stdlib__String.for_all((function (param) {
                  if (param >= 58) {
                    return !(param > 102 || param < 97);
                  } else {
                    return param >= 48;
                  }
                }), x);
  } else {
    return false;
  }
}

function of_hex(x) {
  if (check$1(x)) {
    return x;
  } else {
    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                    _0: {
                      TAG: /* Caml_string */3,
                      _0: /* No_padding */0,
                      _1: {
                        TAG: /* String_literal */11,
                        _0: " is not a valid hex-encoded hash",
                        _1: /* End_of_format */0
                      }
                    },
                    _1: "%S is not a valid hex-encoded hash"
                  }), x);
  }
}

function to_hex(x) {
  return x;
}

function of_b64(x) {
  var x$1 = Base64.decode(true, undefined, undefined, undefined, x + "=");
  if (x$1.TAG === /* Ok */0) {
    var x$2 = x$1._0;
    if (x$2.length === 32) {
      return Hex.of_string(undefined, x$2).VAL;
    }
    
  }
  return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                  _0: {
                    TAG: /* Caml_string */3,
                    _0: /* No_padding */0,
                    _1: {
                      TAG: /* String_literal */11,
                      _0: " is not a valid b64-encoded hash",
                      _1: /* End_of_format */0
                    }
                  },
                  _1: "%S is not a valid b64-encoded hash"
                }), x);
}

function to_b64(x) {
  var x$1 = Base64.encode(false, undefined, undefined, undefined, Hex.to_string({
            NAME: "Hex",
            VAL: x
          }));
  if (x$1.TAG === /* Ok */0) {
    return x$1._0;
  }
  throw {
        RE_EXN_ID: "Assert_failure",
        _1: [
          "common_types.ml",
          82,
          11
        ],
        Error: new Error()
      };
}

function weight_of_json(param) {
  if (typeof param === "string") {
    return Stdlib.invalid_arg("invalid weight");
  }
  var variant = param.NAME;
  if (variant === "Intlit" || variant === "String") {
    var x = param.VAL;
    try {
      var x$1 = Belenios_platform__Platform.Z.of_string(x);
      if (Belenios_platform__Platform.Z.compare(x$1, Belenios_platform__Platform.Z.zero) >= 0) {
        return x$1;
      }
      throw {
            RE_EXN_ID: Stdlib.Exit,
            Error: new Error()
          };
    }
    catch (exn){
      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                      _0: {
                        TAG: /* Caml_string */3,
                        _0: /* No_padding */0,
                        _1: {
                          TAG: /* String_literal */11,
                          _0: " is not a valid weight",
                          _1: /* End_of_format */0
                        }
                      },
                      _1: "%S is not a valid weight"
                    }), x);
    }
  } else if (variant === "Int") {
    var x$2 = param.VAL;
    if (x$2 >= 0) {
      return Belenios_platform__Platform.Z.of_int(x$2);
    } else {
      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                      _0: {
                        TAG: /* Int */4,
                        _0: /* Int_d */0,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: {
                          TAG: /* String_literal */11,
                          _0: " is not a valid weight",
                          _1: /* End_of_format */0
                        }
                      },
                      _1: "%d is not a valid weight"
                    }), x$2);
    }
  } else {
    return Stdlib.invalid_arg("invalid weight");
  }
}

var max_int31 = Belenios_platform__Platform.Z.of_string("1073741823");

function json_of_weight(x) {
  if (Belenios_platform__Platform.Z.compare(x, max_int31) <= 0) {
    return {
            NAME: "Int",
            VAL: Belenios_platform__Platform.Z.to_int(x)
          };
  } else {
    return {
            NAME: "String",
            VAL: Belenios_platform__Platform.Z.to_string(x)
          };
  }
}

var compare = Belenios_platform__Platform.Z.compare;

var max_expanded_weight = Curry._1(Belenios_platform__Platform.Z.of_string, "100000000000");

function is_int(x, i) {
  return Belenios_platform__Platform.Z.compare(x, Belenios_platform__Platform.Z.of_int(i)) === 0;
}

function of_string(x) {
  return weight_of_json({
              NAME: "String",
              VAL: x
            });
}

function expand(param, x) {
  return x;
}

function reduce(param, x) {
  return x;
}

function min(a, b) {
  if (Curry._2(compare, a, b) < 0) {
    return a;
  } else {
    return b;
  }
}

function max(a, b) {
  if (Curry._2(compare, a, b) > 0) {
    return a;
  } else {
    return b;
  }
}

var Question_signature = {};

var Question_result = {};

function wrap_homomorphic(param) {
  if (typeof param === "string" || param.NAME !== "List") {
    return Stdlib.failwith("list expected in Election_result.wrap_homomorphic");
  } else {
    return Stdlib__Array.of_list(Stdlib__List.map(weight_of_json, param.VAL));
  }
}

function wrap_nonhomomorphic(param) {
  if (typeof param === "string" || param.NAME !== "List") {
    return Stdlib.failwith("(outer) list expected in Election_result.wrap_nonhomomorphic");
  } else {
    return Stdlib__Array.of_list(Stdlib__List.map((function (param) {
                      if (typeof param === "string" || param.NAME !== "List") {
                        return Stdlib.failwith("(inner) list expected in Election_result.wrap_nonhomomorphic");
                      } else {
                        return Stdlib__Array.of_list(Stdlib__List.map((function (param) {
                                          if (typeof param === "string" || param.NAME !== "Int") {
                                            return Stdlib.failwith("int expected in Election_result.wrap_nonhomomorphic");
                                          } else {
                                            return param.VAL;
                                          }
                                        }), param.VAL));
                      }
                    }), param.VAL));
  }
}

function wrap$2(s, x) {
  var x$1 = typeof x === "string" || x.NAME !== "List" ? Stdlib.failwith("list expected in Election_result.wrap") : x.VAL;
  var loop = function (s, x) {
    if (typeof s === "number") {
      if (x) {
        return Stdlib.failwith("list too long in Election_result.wrap");
      } else {
        return /* Nil */0;
      }
    } else if (s.TAG === /* Homomorphic */0) {
      if (x) {
        return {
                TAG: /* Homomorphic */0,
                _0: wrap_homomorphic(x.hd),
                _1: loop(s._0, x.tl)
              };
      } else {
        return Stdlib.failwith("list too short in Election_result.wrap");
      }
    } else if (x) {
      return {
              TAG: /* NonHomomorphic */1,
              _0: wrap_nonhomomorphic(x.hd),
              _1: loop(s._1, x.tl)
            };
    } else {
      return Stdlib.failwith("list too short in Election_result.wrap");
    }
  };
  return loop(s, x$1);
}

function unwrap_homomorphic(xs) {
  var x = Stdlib__Array.map(json_of_weight, xs);
  return {
          NAME: "List",
          VAL: Stdlib__Array.to_list(x)
        };
}

function unwrap_nonhomomorphic(xs) {
  var x = Stdlib__Array.map((function (ys) {
          var y = Stdlib__Array.map((function (i) {
                  return {
                          NAME: "Int",
                          VAL: i
                        };
                }), ys);
          return {
                  NAME: "List",
                  VAL: Stdlib__Array.to_list(y)
                };
        }), xs);
  return {
          NAME: "List",
          VAL: Stdlib__Array.to_list(x)
        };
}

function unwrap$2(x) {
  var loop = function (x) {
    if (typeof x === "number") {
      return /* [] */0;
    } else if (x.TAG === /* Homomorphic */0) {
      return {
              hd: unwrap_homomorphic(x._0),
              tl: loop(x._1)
            };
    } else {
      return {
              hd: unwrap_nonhomomorphic(x._0),
              tl: loop(x._1)
            };
    }
  };
  return {
          NAME: "List",
          VAL: loop(x)
        };
}

function nth(x, i) {
  if (i < 0) {
    return Stdlib.invalid_arg("Election_result.nth: negative index");
  }
  var _i = i;
  var _xs = x;
  while(true) {
    var xs = _xs;
    var i$1 = _i;
    if (typeof xs === "number") {
      return Stdlib.invalid_arg("Election_result.nth: out of bounds");
    }
    if (i$1 !== 0) {
      _xs = xs._1;
      _i = i$1 - 1 | 0;
      continue ;
    }
    if (typeof xs !== "number") {
      if (xs.TAG === /* Homomorphic */0) {
        return {
                NAME: "Homomorphic",
                VAL: xs._0
              };
      } else {
        return {
                NAME: "NonHomomorphic",
                VAL: xs._0
              };
      }
    }
    
  };
}

function map2(f, xs, ys) {
  var n = ys.length;
  var _i = 0;
  var _xs = xs;
  var _accu = /* [] */0;
  while(true) {
    var accu = _accu;
    var xs$1 = _xs;
    var i = _i;
    if (typeof xs$1 === "number") {
      if (i === n) {
        return Stdlib__List.rev(accu);
      } else {
        return Stdlib.invalid_arg("Election_result.map2");
      }
    }
    if (xs$1.TAG === /* Homomorphic */0) {
      if (i >= n) {
        return Stdlib.invalid_arg("Election_result.map2");
      }
      var accu_0 = Curry._3(f, i, {
            NAME: "Homomorphic",
            VAL: xs$1._0
          }, Caml_array.get(ys, i));
      var accu$1 = {
        hd: accu_0,
        tl: accu
      };
      _accu = accu$1;
      _xs = xs$1._1;
      _i = i + 1 | 0;
      continue ;
    }
    if (i >= n) {
      return Stdlib.invalid_arg("Election_result.map2");
    }
    var accu_0$1 = Curry._3(f, i, {
          NAME: "NonHomomorphic",
          VAL: xs$1._0
        }, Caml_array.get(ys, i));
    var accu$2 = {
      hd: accu_0$1,
      tl: accu
    };
    _accu = accu$2;
    _xs = xs$1._1;
    _i = i + 1 | 0;
    continue ;
  };
}

function for_all3(f, a, b, c) {
  var n = a.length;
  if (n !== b.length) {
    return false;
  }
  if (n !== c.length) {
    return false;
  }
  var _i = n - 1 | 0;
  while(true) {
    var i = _i;
    if (i < 0) {
      return true;
    }
    if (!Curry._3(f, Caml_array.get(a, i), Caml_array.get(b, i), Caml_array.get(c, i))) {
      return false;
    }
    _i = i - 1 | 0;
    continue ;
  };
}

function map3(f, a, b, c) {
  return Stdlib__Array.mapi((function (i, ai) {
                return Curry._3(f, ai, Caml_array.get(b, i), Caml_array.get(c, i));
              }), a);
}

function findi(f, a) {
  var n = a.length;
  var _i = 0;
  while(true) {
    var i = _i;
    if (i >= n) {
      return ;
    }
    var x = Curry._2(f, i, Caml_array.get(a, i));
    if (x !== undefined) {
      return x;
    }
    _i = i + 1 | 0;
    continue ;
  };
}

var $$Array = {
  make_float: Stdlib__Array.make_float,
  init: Stdlib__Array.init,
  make_matrix: Stdlib__Array.make_matrix,
  create_matrix: Stdlib__Array.create_matrix,
  append: Stdlib__Array.append,
  concat: Stdlib__Array.concat,
  sub: Stdlib__Array.sub,
  copy: Stdlib__Array.copy,
  fill: Stdlib__Array.fill,
  blit: Stdlib__Array.blit,
  to_list: Stdlib__Array.to_list,
  of_list: Stdlib__Array.of_list,
  iter: Stdlib__Array.iter,
  iteri: Stdlib__Array.iteri,
  map: Stdlib__Array.map,
  mapi: Stdlib__Array.mapi,
  fold_left: Stdlib__Array.fold_left,
  fold_left_map: Stdlib__Array.fold_left_map,
  fold_right: Stdlib__Array.fold_right,
  iter2: Stdlib__Array.iter2,
  map2: Stdlib__Array.map2,
  for_all: Stdlib__Array.for_all,
  exists: Stdlib__Array.exists,
  for_all2: Stdlib__Array.for_all2,
  exists2: Stdlib__Array.exists2,
  mem: Stdlib__Array.mem,
  memq: Stdlib__Array.memq,
  find_opt: Stdlib__Array.find_opt,
  find_map: Stdlib__Array.find_map,
  split: Stdlib__Array.split,
  combine: Stdlib__Array.combine,
  sort: Stdlib__Array.sort,
  stable_sort: Stdlib__Array.stable_sort,
  fast_sort: Stdlib__Array.fast_sort,
  to_seq: Stdlib__Array.to_seq,
  to_seqi: Stdlib__Array.to_seqi,
  of_seq: Stdlib__Array.of_seq,
  Floatarray: Stdlib__Array.Floatarray,
  for_all3: for_all3,
  map3: map3,
  findi: findi
};

function of_array(x) {
  return {
          NAME: "Array",
          VAL: Stdlib__Array.map((function (x) {
                  return {
                          NAME: "Atomic",
                          VAL: x
                        };
                }), x)
        };
}

function to_array(param) {
  if (param.NAME === "Array") {
    return Stdlib__Array.map((function (param) {
                  if (param.NAME === "Array") {
                    return Stdlib.invalid_arg("Shape.to_array");
                  } else {
                    return param.VAL;
                  }
                }), param.VAL);
  } else {
    return Stdlib.invalid_arg("Shape.to_array");
  }
}

function to_shape_array(param) {
  if (param.NAME === "Array") {
    return param.VAL;
  } else {
    return Stdlib.invalid_arg("Shape.to_shape_array");
  }
}

function map(f, param) {
  if (param.NAME === "Array") {
    return {
            NAME: "Array",
            VAL: Stdlib__Array.map((function (param) {
                    return map(f, param);
                  }), param.VAL)
          };
  } else {
    return {
            NAME: "Atomic",
            VAL: Curry._1(f, param.VAL)
          };
  }
}

function map2$1(f, a, b) {
  if (typeof a === "string") {
    return Stdlib.invalid_arg("Shape.map2");
  }
  var variant = a.NAME;
  if (variant === "Atomic") {
    if (typeof b === "string" || b.NAME !== "Atomic") {
      return Stdlib.invalid_arg("Shape.map2");
    } else {
      return {
              NAME: "Atomic",
              VAL: Curry._2(f, a.VAL, b.VAL)
            };
    }
  } else if (variant === "Array" && !(typeof b === "string" || b.NAME !== "Array")) {
    return {
            NAME: "Array",
            VAL: Stdlib__Array.map2((function (param, param$1) {
                    return map2$1(f, param, param$1);
                  }), a.VAL, b.VAL)
          };
  } else {
    return Stdlib.invalid_arg("Shape.map2");
  }
}

function flatten(param) {
  if (param.NAME === "Array") {
    return Stdlib__List.flatten(Stdlib__Array.to_list(Stdlib__Array.map(flatten, param.VAL)));
  } else {
    return {
            hd: param.VAL,
            tl: /* [] */0
          };
  }
}

function split(x) {
  return [
          map((function (prim) {
                  return prim[0];
                }), x),
          map((function (prim) {
                  return prim[1];
                }), x)
        ];
}

function forall(p, param) {
  if (param.NAME === "Array") {
    return Stdlib__Array.for_all((function (param) {
                  return forall(p, param);
                }), param.VAL);
  } else {
    return Curry._1(p, param.VAL);
  }
}

function forall2(p, x, y) {
  if (typeof x === "string") {
    return Stdlib.invalid_arg("Shape.forall2");
  }
  var variant = x.NAME;
  if (variant === "Atomic") {
    if (typeof y === "string" || y.NAME !== "Atomic") {
      return Stdlib.invalid_arg("Shape.forall2");
    } else {
      return Curry._2(p, x.VAL, y.VAL);
    }
  } else if (variant === "Array" && !(typeof y === "string" || y.NAME !== "Array")) {
    return Stdlib__Array.for_all2((function (param, param$1) {
                  return forall2(p, param, param$1);
                }), x.VAL, y.VAL);
  } else {
    return Stdlib.invalid_arg("Shape.forall2");
  }
}

function forall3(p, x, y, z) {
  if (typeof x === "string") {
    return Stdlib.invalid_arg("Shape.forall3");
  }
  var variant = x.NAME;
  if (variant === "Atomic") {
    if (typeof y === "string" || !(y.NAME === "Atomic" && !(typeof z === "string" || z.NAME !== "Atomic"))) {
      return Stdlib.invalid_arg("Shape.forall3");
    } else {
      return Curry._3(p, x.VAL, y.VAL, z.VAL);
    }
  } else if (variant === "Array" && !(typeof y === "string" || !(y.NAME === "Array" && !(typeof z === "string" || z.NAME !== "Array")))) {
    return for_all3((function (param, param$1, param$2) {
                  return forall3(p, param, param$1, param$2);
                }), x.VAL, y.VAL, z.VAL);
  } else {
    return Stdlib.invalid_arg("Shape.forall3");
  }
}

var Shape = {
  of_array: of_array,
  to_array: to_array,
  to_shape_array: to_shape_array,
  map: map,
  map2: map2$1,
  flatten: flatten,
  split: split,
  forall: forall,
  forall2: forall2,
  forall3: forall3
};

var Atd_shape_t = {};

var Atd_shape_j = {
  write_shape: Belenios_platform__Platform.write_shape,
  read_shape: Belenios_platform__Platform.read_shape
};

var Uuid = {
  min_length: 14,
  wrap: wrap$1,
  unwrap: unwrap$1
};

var Hash = {
  wrap: of_hex,
  unwrap: to_hex,
  of_hex: of_hex,
  to_hex: to_hex,
  to_b64: to_b64,
  of_b64: of_b64,
  hash_string: Belenios_platform__Platform.sha256_hex
};

var Weight_zero = Belenios_platform__Platform.Z.zero;

var Weight_one = Belenios_platform__Platform.Z.one;

var Weight_$plus = Belenios_platform__Platform.Z.$plus;

var Weight_to_string = Belenios_platform__Platform.Z.to_string;

var Weight = {
  wrap: weight_of_json,
  unwrap: json_of_weight,
  zero: Weight_zero,
  one: Weight_one,
  is_int: is_int,
  $plus: Weight_$plus,
  expand: expand,
  reduce: reduce,
  max_expanded_weight: max_expanded_weight,
  min: min,
  max: max,
  of_string: of_string,
  to_string: Weight_to_string,
  compare: compare
};

var Election_result = {
  wrap: wrap$2,
  unwrap: unwrap$2,
  nth: nth,
  map2: map2
};

var Atd_shape_bs = Atd_shape_j;

export {
  $$Number ,
  Uuid ,
  Hash ,
  Weight ,
  Question_signature ,
  Question_result ,
  Election_result ,
  $$Array ,
  Shape ,
  Atd_shape_t ,
  Atd_shape_j ,
  Atd_shape_bs ,
}
/* max_int31 Not a pure module */
