// Generated by Melange

import * as Re from "../../../../re/re.js";
import * as Caml from "melange.runtime/caml.js";
import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Yojson from "../../../../belenios_compat_melange/yojson.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Caml_string from "melange.runtime/caml_string.js";
import * as Stdlib__Int from "melange/./int.js";
import * as Stdlib__Map from "melange/./map.js";
import * as Stdlib__Set from "melange/./set.js";
import * as Stdlib__List from "melange/./list.js";
import * as Stdlib__Buffer from "melange/./buffer.js";
import * as Stdlib__Option from "melange/./option.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Stdlib__String from "melange/./string.js";
import * as Stdlib__Hashtbl from "melange/./hashtbl.js";
import * as Stdlib__Filename from "melange/./filename.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_core__Common_types from "./common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";
import * as Belenios_core__Serializable_core_j from "./serializable_core_j.js";

function let$at(f, x) {
  return Curry._1(f, x);
}

function sha256_b64(x) {
  return Belenios_core__Common_types.Hash.to_b64(Belenios_core__Common_types.Hash.hash_string(x));
}

function drop_prefix(prefix, x) {
  var prefixn = prefix.length;
  var n = x.length;
  if (n >= prefixn && Stdlib__String.sub(x, 0, prefixn) === prefix) {
    return Stdlib__String.sub(x, prefixn, n - prefixn | 0);
  }
  
}

var $$String = {
  make: Stdlib__String.make,
  init: Stdlib__String.init,
  empty: Stdlib__String.empty,
  of_bytes: Stdlib__String.of_bytes,
  to_bytes: Stdlib__String.to_bytes,
  concat: Stdlib__String.concat,
  cat: Stdlib__String.cat,
  equal: Stdlib__String.equal,
  compare: Stdlib__String.compare,
  starts_with: Stdlib__String.starts_with,
  ends_with: Stdlib__String.ends_with,
  contains_from: Stdlib__String.contains_from,
  rcontains_from: Stdlib__String.rcontains_from,
  contains: Stdlib__String.contains,
  sub: Stdlib__String.sub,
  split_on_char: Stdlib__String.split_on_char,
  map: Stdlib__String.map,
  mapi: Stdlib__String.mapi,
  fold_left: Stdlib__String.fold_left,
  fold_right: Stdlib__String.fold_right,
  for_all: Stdlib__String.for_all,
  exists: Stdlib__String.exists,
  trim: Stdlib__String.trim,
  escaped: Stdlib__String.escaped,
  uppercase_ascii: Stdlib__String.uppercase_ascii,
  lowercase_ascii: Stdlib__String.lowercase_ascii,
  capitalize_ascii: Stdlib__String.capitalize_ascii,
  uncapitalize_ascii: Stdlib__String.uncapitalize_ascii,
  iter: Stdlib__String.iter,
  iteri: Stdlib__String.iteri,
  index_from: Stdlib__String.index_from,
  index_from_opt: Stdlib__String.index_from_opt,
  rindex_from: Stdlib__String.rindex_from,
  rindex_from_opt: Stdlib__String.rindex_from_opt,
  index: Stdlib__String.index,
  index_opt: Stdlib__String.index_opt,
  rindex: Stdlib__String.rindex,
  rindex_opt: Stdlib__String.rindex_opt,
  to_seq: Stdlib__String.to_seq,
  to_seqi: Stdlib__String.to_seqi,
  of_seq: Stdlib__String.of_seq,
  blit: Stdlib__String.blit,
  copy: Stdlib__String.copy,
  fill: Stdlib__String.fill,
  uppercase: Stdlib__String.uppercase,
  lowercase: Stdlib__String.lowercase,
  capitalize: Stdlib__String.capitalize,
  uncapitalize: Stdlib__String.uncapitalize,
  drop_prefix: drop_prefix
};

function join(sep, param) {
  if (!param) {
    return /* [] */0;
  }
  var x = param.hd;
  if (param.tl) {
    return {
            hd: x,
            tl: {
              hd: sep,
              tl: join(sep, param.tl)
            }
          };
  } else {
    return {
            hd: x,
            tl: /* [] */0
          };
  }
}

var List = {
  length: Stdlib__List.length,
  compare_lengths: Stdlib__List.compare_lengths,
  compare_length_with: Stdlib__List.compare_length_with,
  cons: Stdlib__List.cons,
  hd: Stdlib__List.hd,
  tl: Stdlib__List.tl,
  nth: Stdlib__List.nth,
  nth_opt: Stdlib__List.nth_opt,
  rev: Stdlib__List.rev,
  init: Stdlib__List.init,
  append: Stdlib__List.append,
  rev_append: Stdlib__List.rev_append,
  concat: Stdlib__List.concat,
  flatten: Stdlib__List.flatten,
  equal: Stdlib__List.equal,
  compare: Stdlib__List.compare,
  iter: Stdlib__List.iter,
  iteri: Stdlib__List.iteri,
  map: Stdlib__List.map,
  mapi: Stdlib__List.mapi,
  rev_map: Stdlib__List.rev_map,
  filter_map: Stdlib__List.filter_map,
  concat_map: Stdlib__List.concat_map,
  fold_left_map: Stdlib__List.fold_left_map,
  fold_left: Stdlib__List.fold_left,
  fold_right: Stdlib__List.fold_right,
  iter2: Stdlib__List.iter2,
  map2: Stdlib__List.map2,
  rev_map2: Stdlib__List.rev_map2,
  fold_left2: Stdlib__List.fold_left2,
  fold_right2: Stdlib__List.fold_right2,
  for_all: Stdlib__List.for_all,
  exists: Stdlib__List.exists,
  for_all2: Stdlib__List.for_all2,
  exists2: Stdlib__List.exists2,
  mem: Stdlib__List.mem,
  memq: Stdlib__List.memq,
  find: Stdlib__List.find,
  find_opt: Stdlib__List.find_opt,
  find_map: Stdlib__List.find_map,
  filter: Stdlib__List.filter,
  find_all: Stdlib__List.find_all,
  filteri: Stdlib__List.filteri,
  partition: Stdlib__List.partition,
  partition_map: Stdlib__List.partition_map,
  assoc: Stdlib__List.assoc,
  assoc_opt: Stdlib__List.assoc_opt,
  assq: Stdlib__List.assq,
  assq_opt: Stdlib__List.assq_opt,
  mem_assoc: Stdlib__List.mem_assoc,
  mem_assq: Stdlib__List.mem_assq,
  remove_assoc: Stdlib__List.remove_assoc,
  remove_assq: Stdlib__List.remove_assq,
  split: Stdlib__List.split,
  combine: Stdlib__List.combine,
  sort: Stdlib__List.sort,
  stable_sort: Stdlib__List.stable_sort,
  fast_sort: Stdlib__List.fast_sort,
  sort_uniq: Stdlib__List.sort_uniq,
  merge: Stdlib__List.merge,
  to_seq: Stdlib__List.to_seq,
  of_seq: Stdlib__List.of_seq,
  join: join
};

function wrap(f, x) {
  try {
    return Caml_option.some(Curry._1(f, x));
  }
  catch (exn){
    return ;
  }
}

function unwrap($$default, x, f) {
  if (x !== undefined) {
    return Curry._1(f, Caml_option.valFromOption(x));
  } else {
    return $$default;
  }
}

var $$Option = {
  none: undefined,
  some: Stdlib__Option.some,
  value: Stdlib__Option.value,
  get: Stdlib__Option.get,
  bind: Stdlib__Option.bind,
  join: Stdlib__Option.join,
  map: Stdlib__Option.map,
  fold: Stdlib__Option.fold,
  iter: Stdlib__Option.iter,
  is_none: Stdlib__Option.is_none,
  is_some: Stdlib__Option.is_some,
  equal: Stdlib__Option.equal,
  compare: Stdlib__Option.compare,
  to_result: Stdlib__Option.to_result,
  to_list: Stdlib__Option.to_list,
  to_seq: Stdlib__Option.to_seq,
  wrap: wrap,
  unwrap: unwrap
};

function compare_b64(a, b) {
  var na = a.length;
  var nb = b.length;
  var value_of = function (c) {
    var i = Stdlib__String.index_opt("+/0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZ", c);
    if (i !== undefined) {
      return i;
    } else {
      return -1;
    }
  };
  var _i = 0;
  while(true) {
    var i = _i;
    var match = i < na;
    var match$1 = i < nb;
    if (!match) {
      if (match$1) {
        return -1;
      } else {
        return 0;
      }
    }
    if (!match$1) {
      return 1;
    }
    var diff = value_of(Caml_string.get(a, i)) - value_of(Caml_string.get(b, i)) | 0;
    if (diff !== 0) {
      return diff;
    }
    _i = i + 1 | 0;
    continue ;
  };
}

var SSet = Stdlib__Set.Make({
      compare: Stdlib__String.compare
    });

var SMap = Stdlib__Map.Make({
      compare: Stdlib__String.compare
    });

var IMap = Stdlib__Map.Make({
      compare: Stdlib__Int.compare
    });

function bytes_to_sample(q) {
  return (Belenios_platform__Platform.Z.bit_length(q) / 8 | 0) + 17 | 0;
}

function check_modulo(p, x) {
  if (Belenios_platform__Platform.Z.compare(x, Belenios_platform__Platform.Z.zero) >= 0) {
    return Belenios_platform__Platform.Z.compare(x, p) < 0;
  } else {
    return false;
  }
}

var b58_digits = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

var z58 = Belenios_platform__Platform.Z.of_int(b58_digits.length);

var z10 = Belenios_platform__Platform.Z.of_int(10);

function sqrt(s) {
  var x0 = Belenios_platform__Platform.Z.shift_right(s, 1);
  if (Belenios_platform__Platform.Z.compare(x0, Belenios_platform__Platform.Z.zero) > 0) {
    var _x0 = x0;
    while(true) {
      var x0$1 = _x0;
      var x1 = Belenios_platform__Platform.Z.shift_right(Belenios_platform__Platform.Z.$plus(x0$1, Belenios_platform__Platform.Z.$slash(s, x0$1)), 1);
      if (Belenios_platform__Platform.Z.compare(x1, x0$1) >= 0) {
        return x0$1;
      }
      _x0 = x1;
      continue ;
    };
  } else {
    return s;
  }
}

function BabyStepGiantStep(G) {
  var log = function (alpha, n) {
    var m = Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.$plus(sqrt(n), Belenios_platform__Platform.Z.one));
    var table = Stdlib__Hashtbl.create(undefined, m);
    var add_to_table = function (x, i) {
      var h = Curry._1(G.hash_to_int, x);
      var ii = Stdlib__Hashtbl.find_opt(table, h);
      var ii$1 = ii !== undefined ? ii : /* [] */0;
      Stdlib__Hashtbl.add(table, h, {
            hd: i,
            tl: ii$1
          });
    };
    var populate_table = function (_j, _cur) {
      while(true) {
        var cur = _cur;
        var j = _j;
        if (j >= m) {
          return cur;
        }
        add_to_table(cur, j);
        _cur = Curry._2(G.$star$tilde, cur, alpha);
        _j = j + 1 | 0;
        continue ;
      };
    };
    var inv_alpha_m = Curry._1(G.invert, populate_table(0, G.one));
    return function (beta) {
      var _i = 0;
      var _gamma = beta;
      while(true) {
        var gamma = _gamma;
        var i = _i;
        if (i >= m) {
          return ;
        }
        var r = Stdlib__Option.bind(Stdlib__Hashtbl.find_opt(table, Curry._1(G.hash_to_int, gamma)), (function(i){
            return function (jj) {
              var _param = jj;
              while(true) {
                var param = _param;
                if (!param) {
                  return ;
                }
                var r = Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.$star(Belenios_platform__Platform.Z.of_int(i), Belenios_platform__Platform.Z.of_int(m)), Belenios_platform__Platform.Z.of_int(param.hd)), G.q);
                if (Curry._2(G.$eq$tilde, Curry._2(G.$star$star$tilde, alpha, r), beta)) {
                  return Caml_option.some(r);
                }
                _param = param.tl;
                continue ;
              };
            }
            }(i)));
        if (r !== undefined) {
          return Caml_option.some(Caml_option.valFromOption(r));
        }
        _gamma = Curry._2(G.$star$tilde, gamma, inv_alpha_m);
        _i = i + 1 | 0;
        continue ;
      };
    };
  };
  return {
          log: log
        };
}

function split_on_br(s) {
  var n = s.length;
  var _i = 0;
  var _j = 0;
  var _accu = /* [] */0;
  while(true) {
    var accu = _accu;
    var j = _j;
    var i = _i;
    if (j > (n - 4 | 0)) {
      return Stdlib__List.rev({
                  hd: Stdlib__String.sub(s, i, n - i | 0),
                  tl: accu
                });
    }
    if (Stdlib__String.sub(s, j, 4) === "<br>") {
      _accu = {
        hd: Stdlib__String.sub(s, i, j - i | 0),
        tl: accu
      };
      _j = j + 4 | 0;
      _i = j + 4 | 0;
      continue ;
    }
    _j = j + 1 | 0;
    continue ;
  };
}

function split_lines(str) {
  var n = str.length;
  var find = function (i, c) {
    var j = Stdlib__String.index_from_opt(str, i, c);
    if (j !== undefined) {
      return j;
    } else {
      return n;
    }
  };
  var _accu = /* [] */0;
  var _i = 0;
  while(true) {
    var i = _i;
    var accu = _accu;
    if (i >= n) {
      return Stdlib__List.rev(accu);
    }
    var j = Caml.caml_int_min(find(i, /* '\n' */10), find(i, /* '\r' */13));
    var line = Stdlib__String.sub(str, i, j - i | 0);
    var accu$1 = line === "" ? accu : ({
          hd: line,
          tl: accu
        });
    _i = j + 1 | 0;
    _accu = accu$1;
    continue ;
  };
}

function strip_cred(x) {
  var match = Stdlib__String.split_on_char(/* ',' */44, x);
  if (match) {
    var match$1 = match.tl;
    if (!match$1) {
      return x;
    }
    var y = match$1.hd;
    var x$1 = match.hd;
    var exit = 0;
    if (y === "") {
      var match$2 = match$1.tl;
      if (match$2) {
        if (!match$2.tl) {
          return x$1;
        }
        
      } else {
        exit = 2;
      }
    } else {
      exit = 2;
    }
    if (exit === 2) {
      var match$3 = match$1.tl;
      if (!match$3) {
        return x;
      }
      if (!match$3.tl) {
        return Curry._2(Stdlib__Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* Char_literal */12,
                            _0: /* ',' */44,
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: /* End_of_format */0
                            }
                          }
                        },
                        _1: "%s,%s"
                      }), x$1, y);
      }
      
    }
    
  }
  return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                  _0: {
                    TAG: /* String_literal */11,
                    _0: "invalid line in public credentials: ",
                    _1: {
                      TAG: /* String */2,
                      _0: /* No_padding */0,
                      _1: /* End_of_format */0
                    }
                  },
                  _1: "invalid line in public credentials: %s"
                }), x);
}

function extract_weight(str) {
  try {
    var i = Stdlib__String.rindex(str, /* ',' */44);
    var w = Belenios_core__Common_types.Weight.of_string(Stdlib__String.sub(str, i + 1 | 0, (str.length - i | 0) - 1 | 0));
    return [
            Stdlib__String.sub(str, 0, i),
            w
          ];
  }
  catch (exn){
    return [
            str,
            Belenios_core__Common_types.Weight.one
          ];
  }
}

function re_exec_opt(rex, x) {
  try {
    return Caml_option.some(Curry._3(Re.Pcre.exec, rex, undefined, x));
  }
  catch (raw_exn){
    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
    if (exn.RE_EXN_ID === Stdlib.Not_found) {
      return ;
    }
    throw exn;
  }
}

var rex = Curry._2(Re.Pcre.regexp, {
      hd: "CASELESS",
      tl: /* [] */0
    }, "^[A-Z0-9._%+-]+$");

function is_username(x) {
  return re_exec_opt(rex, x) !== undefined;
}

var rex$1 = Curry._2(Re.Pcre.regexp, {
      hd: "CASELESS",
      tl: /* [] */0
    }, "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}$");

function is_email(x) {
  return re_exec_opt(rex$1, x) !== undefined;
}

var rex$2 = Curry._2(Re.Pcre.regexp, {
      hd: "CASELESS",
      tl: /* [] */0
    }, "<([A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,})>");

function extract_email(x) {
  if (is_email(x)) {
    return x;
  } else {
    return Stdlib__Option.bind(re_exec_opt(rex$2, x), (function (s) {
                  return Curry._2(Re.Pcre.get_substring, s, 1);
                }));
  }
}

function split_identity_opt(x) {
  var match = Stdlib__String.split_on_char(/* ',' */44, x);
  if (!match) {
    return Stdlib.failwith("Common.split_identity_opt");
  }
  var match$1 = match.tl;
  var address = match.hd;
  if (!match$1) {
    return [
            address,
            undefined,
            undefined
          ];
  }
  var match$2 = match$1.tl;
  var login = match$1.hd;
  if (match$2) {
    if (match$2.tl) {
      return Stdlib.failwith("Common.split_identity_opt");
    } else {
      return [
              address,
              login === "" ? undefined : login,
              Caml_option.some(Belenios_core__Common_types.Weight.of_string(match$2.hd))
            ];
    }
  } else {
    return [
            address,
            login === "" ? undefined : login,
            undefined
          ];
  }
}

function map_and_concat_with_commas(f, xs) {
  var n = xs.length;
  var res = Stdlib__Buffer.create((n << 10));
  for(var i = 0; i < n; ++i){
    Stdlib__Buffer.add_string(res, Curry._1(f, Caml_array.get(xs, i)));
    Stdlib__Buffer.add_char(res, /* ',' */44);
  }
  var size = Stdlib__Buffer.length(res) - 1 | 0;
  if (size > 0) {
    return Stdlib__Buffer.sub(res, 0, size);
  } else {
    return "";
  }
}

function wrap$1(x) {
  if (typeof x !== "string" && x.NAME === "String") {
    var match = split_identity_opt(x.VAL);
    return [
            "Plain",
            {
              address: match[0],
              login: match[1],
              weight: match[2]
            }
          ];
  }
  var s = Yojson.Safe.to_string(x);
  return [
          "Json",
          Belenios_core__Serializable_core_j.voter_of_string(s)
        ];
}

function of_string(x) {
  var o;
  try {
    o = Belenios_core__Serializable_core_j.voter_of_string(x);
  }
  catch (exn){
    return wrap$1({
                NAME: "String",
                VAL: x
              });
  }
  return [
          "Json",
          o
        ];
}

function to_string(param) {
  var o = param[1];
  if (param[0] === "Json") {
    return Belenios_core__Serializable_core_j.string_of_voter(o);
  }
  var login = o.login;
  var address = o.address;
  if (login !== undefined) {
    var weight = o.weight;
    if (weight !== undefined) {
      return address + ("," + (login + ("," + Belenios_core__Common_types.Weight.to_string(Caml_option.valFromOption(weight)))));
    } else {
      return address + ("," + login);
    }
  }
  var weight$1 = o.weight;
  if (weight$1 !== undefined) {
    return address + (",," + Belenios_core__Common_types.Weight.to_string(Caml_option.valFromOption(weight$1)));
  } else {
    return address;
  }
}

function unwrap$1(x) {
  if (x[0] === "Json") {
    return Yojson.Safe.from_string(Belenios_core__Serializable_core_j.string_of_voter(x[1]));
  } else {
    return {
            NAME: "String",
            VAL: to_string(x)
          };
  }
}

function list_to_string(voters) {
  if (Stdlib__List.exists((function (param) {
            return param[0] === "Json";
          }), voters)) {
    return Belenios_core__Serializable_core_j.string_of_voter_list(Stdlib__List.map((function (prim) {
                      return prim[1];
                    }), voters));
  }
  var b = Stdlib__Buffer.create(1024);
  Stdlib__List.iter((function (x) {
          Stdlib__Buffer.add_string(b, to_string(x));
          Stdlib__Buffer.add_char(b, /* '\n' */10);
        }), voters);
  return Stdlib__Buffer.contents(b);
}

function list_of_string(x) {
  var voters;
  try {
    voters = Belenios_core__Serializable_core_j.voter_list_of_string(x);
  }
  catch (exn){
    return Stdlib__List.map(of_string, split_lines(x));
  }
  return Stdlib__List.map((function (x) {
                return [
                        "Json",
                        x
                      ];
              }), voters);
}

function get(param) {
  var match = param[1];
  var address = match.address;
  return [
          address,
          Stdlib__Option.value(match.login, address),
          Stdlib__Option.value(match.weight, Belenios_core__Common_types.Weight.one)
        ];
}

function validate(param) {
  var match = param[1];
  var login = match.login;
  if (is_email(match.address)) {
    if (login !== undefined) {
      return is_username(login);
    } else {
      return true;
    }
  } else {
    return false;
  }
}

function has_explicit_weights(voters) {
  return Stdlib__List.exists((function (param) {
                return param[1].weight !== undefined;
              }), voters);
}

var let$amp = Stdlib__Option.bind;

var $slash$slash = Stdlib__Filename.concat;

var sread = Belenios_platform__Platform.sread;

var swrite = Belenios_platform__Platform.swrite;

function MakeGenerateToken(funarg) {
  var generate_token = function (lengthOpt, param) {
    var length = lengthOpt !== undefined ? lengthOpt : 14;
    return Stdlib__String.init(length, (function (param) {
                  var n = Curry._1(funarg.random, z58);
                  return Caml_string.get(b58_digits, Belenios_platform__Platform.Z.to_int(n));
                }));
  };
  var generate_numeric = function (lengthOpt, param) {
    var length = lengthOpt !== undefined ? lengthOpt : 6;
    var loop = function (_length, _accu) {
      while(true) {
        var accu = _accu;
        var length = _length;
        if (length <= 0) {
          return accu;
        }
        _accu = Belenios_platform__Platform.Z.$star(accu, z10);
        _length = length - 1 | 0;
        continue ;
      };
    };
    var modulus = loop(length, Belenios_platform__Platform.Z.one);
    var n = Curry._1(funarg.random, modulus);
    return Curry._2(Stdlib__Printf.sprintf(/* Format */{
                    _0: {
                      TAG: /* Int */4,
                      _0: /* Int_d */0,
                      _1: {
                        TAG: /* Arg_padding */1,
                        _0: /* Zeros */2
                      },
                      _2: /* No_precision */0,
                      _3: /* End_of_format */0
                    },
                    _1: "%0*d"
                  }), length, Belenios_platform__Platform.Z.to_int(n));
  };
  return {
          generate_token: generate_token,
          generate_numeric: generate_numeric
        };
}

var Voter = {
  wrap: wrap$1,
  unwrap: unwrap$1,
  to_string: to_string,
  of_string: of_string,
  list_to_string: list_to_string,
  list_of_string: list_of_string,
  get: get,
  validate: validate
};

var supported_crypto_versions = {
  hd: 1,
  tl: /* [] */0
};

export {
  let$at ,
  let$amp ,
  $slash$slash ,
  sha256_b64 ,
  $$String ,
  List ,
  $$Option ,
  sread ,
  swrite ,
  compare_b64 ,
  SSet ,
  SMap ,
  IMap ,
  bytes_to_sample ,
  check_modulo ,
  MakeGenerateToken ,
  sqrt ,
  BabyStepGiantStep ,
  split_on_br ,
  split_lines ,
  strip_cred ,
  extract_weight ,
  re_exec_opt ,
  is_username ,
  is_email ,
  extract_email ,
  map_and_concat_with_commas ,
  Voter ,
  has_explicit_weights ,
  supported_crypto_versions ,
}
/* SSet Not a pure module */
