// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_bytes from "melange.runtime/caml_bytes.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Caml_string from "melange.runtime/caml_string.js";
import * as Stdlib__Bytes from "melange/./bytes.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_core__Common_types from "./common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

var digits = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";

var n58 = Belenios_platform__Platform.Z.of_int(58);

var n53 = Belenios_platform__Platform.Z.of_int(53);

function check_raw(x) {
  var loop = function (i, accu) {
    if (i < 14) {
      return Belenios_core__Common.let$amp(Curry._2(Belenios_core__Common.$$String.index_opt, digits, Caml_string.get(x, i)), (function (digit) {
                    return loop(i + 1 | 0, Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.$star(n58, accu), Belenios_platform__Platform.Z.of_int(digit)));
                  }));
    } else {
      return Caml_option.some(accu);
    }
  };
  var match = loop(0, Belenios_platform__Platform.Z.zero);
  var match$1 = Curry._2(Belenios_core__Common.$$String.index_opt, digits, Caml_string.get(x, 14));
  if (match !== undefined && match$1 !== undefined) {
    return Belenios_platform__Platform.Z.$eq$percent(Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$plus(Caml_option.valFromOption(match), Belenios_platform__Platform.Z.of_int(match$1)), n53), Belenios_platform__Platform.Z.zero);
  } else {
    return false;
  }
}

function parse(x) {
  var n = x.length;
  if (n === 15) {
    if (check_raw(x)) {
      return "Valid";
    } else {
      return "Invalid";
    }
  }
  if (n === 19) {
    if (n !== 19) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "credential.ml",
              82,
              4
            ],
            Error: new Error()
          };
    }
    if (!(Caml_string.get(x, 3) === /* '-' */45 && Caml_string.get(x, 7) === /* '-' */45 && Caml_string.get(x, 11) === /* '-' */45 && Caml_string.get(x, 15) === /* '-' */45)) {
      return "Invalid";
    }
    var actual = Curry._3(Belenios_core__Common.$$String.sub, x, 0, 3) + (Curry._3(Belenios_core__Common.$$String.sub, x, 4, 3) + (Curry._3(Belenios_core__Common.$$String.sub, x, 8, 3) + (Curry._3(Belenios_core__Common.$$String.sub, x, 12, 3) + Curry._3(Belenios_core__Common.$$String.sub, x, 16, 3))));
    if (check_raw(actual)) {
      return "Valid";
    } else {
      return "Invalid";
    }
  }
  if (n !== 17) {
    return "Invalid";
  }
  if (n !== 17) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "credential.ml",
            92,
            4
          ],
          Error: new Error()
        };
  }
  if (Caml_string.get(x, 5) === /* '-' */45 && Caml_string.get(x, 11) === /* '-' */45) {
    return "MaybePassword";
  } else {
    return "Invalid";
  }
}

function check(x) {
  var match = parse(x);
  return !(match === "Invalid" || match === "MaybePassword");
}

function MakeDerive(G) {
  var derive = function (uuid, x) {
    var uuid$1 = Belenios_core__Common_types.Uuid.unwrap(uuid);
    var derived = Belenios_platform__Platform.pbkdf2_utf8(1000, uuid$1, x);
    return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.of_hex(derived), G.q);
  };
  return {
          derive: derive
        };
}

function MakeParsePublicCredential(G) {
  var parse_public_credential = function (s) {
    try {
      var exit = 0;
      var i;
      try {
        i = Curry._2(Belenios_core__Common.$$String.index, s, /* ',' */44);
        exit = 1;
      }
      catch (raw_exn){
        var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
        if (exn.RE_EXN_ID === Stdlib.Not_found) {
          var x = Curry._1(G.of_string, s);
          if (Curry._1(G.check, x)) {
            return [
                    Belenios_core__Common_types.Weight.one,
                    x
                  ];
          } else {
            return ;
          }
        }
        throw exn;
      }
      if (exit === 1) {
        var n = s.length;
        var w = Belenios_core__Common_types.Weight.of_string(Curry._3(Belenios_core__Common.$$String.sub, s, i + 1 | 0, (n - i | 0) - 1 | 0));
        var x$1 = Curry._1(G.of_string, Curry._3(Belenios_core__Common.$$String.sub, s, 0, i));
        if (Curry._1(G.check, x$1)) {
          return [
                  w,
                  x$1
                ];
        } else {
          return ;
        }
      }
      
    }
    catch (exn$1){
      return ;
    }
  };
  return {
          parse_public_credential: parse_public_credential
        };
}

function MakeGenerate(funarg) {
  var generate_raw_token = function (param) {
    var res = Caml_bytes.caml_create_bytes(14);
    var _i = 0;
    var _accu = Belenios_platform__Platform.Z.zero;
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i >= 14) {
        return [
                Stdlib__Bytes.to_string(res),
                accu
              ];
      }
      var digit = Belenios_platform__Platform.Z.to_int(Curry._1(funarg.random, n58));
      Caml_bytes.set(res, i, Caml_string.get(digits, digit));
      _accu = Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.$star(n58, accu), Belenios_platform__Platform.Z.of_int(digit));
      _i = i + 1 | 0;
      continue ;
    };
  };
  var add_checksum = function (param) {
    var checksum = 53 - Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.mod(param[1], n53)) | 0;
    return param[0] + Curry._2(Belenios_core__Common.$$String.make, 1, Caml_string.get(digits, checksum));
  };
  var generate = function (param) {
    var x = generate_raw_token(undefined);
    var x$1 = add_checksum(x);
    if (x$1.length !== 15) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "credential.ml",
              33,
              2
            ],
            Error: new Error()
          };
    }
    return Curry._3(Belenios_core__Common.$$String.sub, x$1, 0, 3) + ("-" + (Curry._3(Belenios_core__Common.$$String.sub, x$1, 3, 3) + ("-" + (Curry._3(Belenios_core__Common.$$String.sub, x$1, 6, 3) + ("-" + (Curry._3(Belenios_core__Common.$$String.sub, x$1, 9, 3) + ("-" + Curry._3(Belenios_core__Common.$$String.sub, x$1, 12, 3))))))));
  };
  return {
          generate: generate
        };
}

export {
  MakeGenerate ,
  parse ,
  check ,
  MakeDerive ,
  MakeParsePublicCredential ,
}
/* n58 Not a pure module */
