// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

var q = Belenios_platform__Platform.Z.$neg(Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.one, 255), Belenios_platform__Platform.Z.of_int(19));

var l = Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.one, 252), Belenios_platform__Platform.Z.of_string("27742317777372353535851937790883648493"));

var zero = Belenios_platform__Platform.Z.zero;

var one = Belenios_platform__Platform.Z.one;

var of_int = Belenios_platform__Platform.Z.of_int;

var compare = Belenios_platform__Platform.Z.compare;

function $$double(a) {
  var x = Belenios_platform__Platform.Z.shift_left(a, 1);
  return Belenios_platform__Platform.Z.erem(x, q);
}

function $plus(a, b) {
  var x = Belenios_platform__Platform.Z.$plus(a, b);
  return Belenios_platform__Platform.Z.erem(x, q);
}

function $star(a, b) {
  var x = Belenios_platform__Platform.Z.$star(a, b);
  return Belenios_platform__Platform.Z.erem(x, q);
}

function $neg(a, b) {
  var x = Belenios_platform__Platform.Z.$neg(a, b);
  return Belenios_platform__Platform.Z.erem(x, q);
}

var a = $neg(zero, one);

var a$1 = Curry._1(of_int, 121666);

var d = $neg(zero, $star(Curry._1(of_int, 121665), Belenios_platform__Platform.Z.invert(a$1, q)));

function of_coordinates(param) {
  var y = param[1];
  var x = param[0];
  return [
          x,
          y,
          Belenios_platform__Platform.Z.one,
          $star(x, y)
        ];
}

function to_coordinates(param) {
  var invz = Belenios_platform__Platform.Z.invert(param[2], q);
  return [
          $star(param[0], invz),
          $star(param[1], invz)
        ];
}

function curve(x, y, z, t) {
  var x2 = $star(x, x);
  var y2 = $star(y, y);
  var z2 = $star(z, z);
  var t2 = $star(t, t);
  return $neg($neg($plus($star(a, x2), y2), z2), $star(d, t2));
}

var one$1 = of_coordinates([
      zero,
      one
    ]);

var g = of_coordinates([
      Belenios_platform__Platform.Z.of_string("15112221349535400772501151409588531511454012693041857206046113283949847762202"),
      Belenios_platform__Platform.Z.of_string("46316835694926478169428394003475163141307993866256225615783033603165251855960")
    ]);

var k = $$double(d);

function $star$tilde(param, param$1) {
  var y2 = param$1[1];
  var x2 = param$1[0];
  var y1 = param[1];
  var x1 = param[0];
  var a = $star($neg(y1, x1), $neg(y2, x2));
  var b = $star($plus(y1, x1), $plus(y2, x2));
  var c = $star($star(param[3], k), param$1[3]);
  var d = $star(param[2], $$double(param$1[2]));
  var e = $neg(b, a);
  var f = $neg(d, c);
  var g = $plus(d, c);
  var h = $plus(b, a);
  var x3 = $star(e, f);
  var y3 = $star(g, h);
  var t3 = $star(e, h);
  var z3 = $star(f, g);
  return [
          x3,
          y3,
          z3,
          t3
        ];
}

var windowmask = 15;

var windowmaskZ = Belenios_platform__Platform.Z.of_int(windowmask);

var windowiterations = Math.ceil(255 / 4) | 0;

function $star$star$tilde(p, n) {
  var t = Caml_array.make(windowmask + 1 | 0, one$1);
  Caml_array.set(t, 1, p);
  var init = function (_i) {
    while(true) {
      var i = _i;
      if (i >= windowmask) {
        return ;
      }
      var z = Caml_array.get(t, i / 2 | 0);
      var s = $star$tilde(z, z);
      Caml_array.set(t, i, s);
      Caml_array.set(t, i + 1 | 0, $star$tilde(s, p));
      _i = i + 2 | 0;
      continue ;
    };
  };
  init(2);
  var _i = windowiterations - 1 | 0;
  var _s = one$1;
  while(true) {
    var s = _s;
    var i = _i;
    if (i < 0) {
      return s;
    }
    var k = (i << 2);
    var j = Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.logand(Belenios_platform__Platform.Z.shift_right(n, k), windowmaskZ));
    var s$1 = $star$tilde(s, Caml_array.get(t, j));
    var s$2;
    if (i !== 0) {
      var loop = function (_i, _s) {
        while(true) {
          var s = _s;
          var i = _i;
          if (i <= 0) {
            return s;
          }
          _s = $star$tilde(s, s);
          _i = i - 1 | 0;
          continue ;
        };
      };
      s$2 = loop(4, s$1);
    } else {
      s$2 = s$1;
    }
    _s = s$2;
    _i = i - 1 | 0;
    continue ;
  };
}

function compare$1(param, param$1) {
  var z2 = param$1[2];
  var z1 = param[2];
  var a = Curry._2(compare, $star(param[0], z2), $star(param$1[0], z1));
  if (a === 0) {
    return Curry._2(compare, $star(param[1], z2), $star(param$1[1], z1));
  } else {
    return a;
  }
}

function $eq$tilde(p1, p2) {
  return compare$1(p1, p2) === 0;
}

function check(p) {
  var t = p[3];
  var z = p[2];
  var y = p[1];
  var x = p[0];
  if (Belenios_platform__Platform.Z.compare(z, Belenios_platform__Platform.Z.zero) > 0 && Belenios_core__Common.check_modulo(q, x) && Belenios_core__Common.check_modulo(q, y) && Belenios_core__Common.check_modulo(q, z) && Belenios_core__Common.check_modulo(q, t) && Curry._2(compare, $star(x, y), $star(z, t)) === 0 && Curry._2(compare, curve(x, y, z, t), zero) === 0) {
    return $eq$tilde($star$star$tilde(p, l), one$1);
  } else {
    return false;
  }
}

var a$2 = Curry._1(of_int, 5);

var four_fifth = $star(Curry._1(of_int, 4), Belenios_platform__Platform.Z.invert(a$2, q));

function is_base_point(p) {
  if (!check(p)) {
    return false;
  }
  var match = to_coordinates(p);
  if (Belenios_platform__Platform.Z.compare(four_fifth, match[1]) === 0) {
    var x = match[0];
    return Belenios_platform__Platform.Z.compare(Belenios_platform__Platform.Z.logand(x, Belenios_platform__Platform.Z.one), Belenios_platform__Platform.Z.zero) === 0;
  } else {
    return false;
  }
}

function invert(param) {
  return [
          $neg(zero, param[0]),
          param[1],
          param[2],
          $neg(zero, param[3])
        ];
}

function compress(param) {
  var b = Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.logand(param[0], Belenios_platform__Platform.Z.one), 255);
  return Belenios_platform__Platform.Z.logxor(param[1], b);
}

var mask255 = Belenios_platform__Platform.Z.$neg(Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.one, 255), Belenios_platform__Platform.Z.one);

var five = Belenios_platform__Platform.Z.of_int(5);

var eight = Belenios_platform__Platform.Z.of_int(8);

var exp = Belenios_platform__Platform.Z.$slash(Belenios_platform__Platform.Z.$neg(q, five), eight);

function modsqrt(a) {
  var v = Belenios_platform__Platform.Z.powm(Belenios_platform__Platform.Z.shift_left(a, 1), exp, q);
  var i = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.$star(Belenios_platform__Platform.Z.$star(a, v), v), 1), q);
  return Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$star(Belenios_platform__Platform.Z.$star(a, v), Belenios_platform__Platform.Z.$neg(i, Belenios_platform__Platform.Z.one)), q);
}

function uncompress(raw) {
  var y = Belenios_platform__Platform.Z.logand(raw, mask255);
  var y2 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$star(y, y), q);
  var x2 = Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$star(Belenios_platform__Platform.Z.$neg(y2, Belenios_platform__Platform.Z.one), Belenios_platform__Platform.Z.invert(Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.$star(d, y2), Belenios_platform__Platform.Z.one), q)), q);
  var x = modsqrt(x2);
  if (Belenios_platform__Platform.Z.compare(Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$star(x, x), q), x2) !== 0) {
    return ;
  }
  var xsign = Belenios_platform__Platform.Z.logand(x, Belenios_platform__Platform.Z.one);
  var rsign = Belenios_platform__Platform.Z.shift_right(raw, 255);
  var x$1 = Belenios_platform__Platform.Z.compare(xsign, rsign) === 0 ? x : Belenios_platform__Platform.Z.erem(Belenios_platform__Platform.Z.$neg(Belenios_platform__Platform.Z.zero, x), q);
  return [
          x$1,
          y
        ];
}

function to_string(p) {
  var r = Belenios_platform__Platform.Z.to_hex(compress(to_coordinates(p)));
  var n = r.length;
  if (n > 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ed25519_pure.ml",
            191,
            2
          ],
          Error: new Error()
        };
  }
  if (n < 64) {
    return Curry._2(Belenios_core__Common.$$String.make, 64 - n | 0, /* '0' */48) + r;
  } else {
    return r;
  }
}

function of_string(s) {
  if (s.length !== 64) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ed25519_pure.ml",
            195,
            2
          ],
          Error: new Error()
        };
  }
  var p = uncompress(Belenios_platform__Platform.Z.of_hex(s));
  if (p !== undefined) {
    return of_coordinates(p);
  } else {
    return Stdlib.invalid_arg("Ed25519_pure.of_string");
  }
}

var mask_per_int = 255;

function of_ints(xs) {
  var n = xs.length;
  var encode_int = function (_i, _accu) {
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i >= n) {
        return Belenios_platform__Platform.Z.shift_left(accu, 14);
      }
      var x = Caml_array.get(xs, i) & mask_per_int;
      _accu = Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.shift_left(accu, 8), Belenios_platform__Platform.Z.of_int(x));
      _i = i + 1 | 0;
      continue ;
    };
  };
  var _accu = encode_int(0, Belenios_platform__Platform.Z.zero);
  while(true) {
    var accu = _accu;
    var p = uncompress(accu);
    if (p !== undefined) {
      var p$1 = of_coordinates(p);
      if (check(p$1)) {
        return p$1;
      }
      _accu = Belenios_platform__Platform.Z.$plus(accu, Belenios_platform__Platform.Z.one);
      continue ;
    }
    _accu = Belenios_platform__Platform.Z.$plus(accu, Belenios_platform__Platform.Z.one);
    continue ;
  };
}

var mask_per_int$1 = Belenios_platform__Platform.Z.$neg(Belenios_platform__Platform.Z.shift_left(Belenios_platform__Platform.Z.one, 8), Belenios_platform__Platform.Z.one);

function to_ints(n, p) {
  var x = compress(to_coordinates(p));
  var xs = Caml_array.make(n, 0);
  var decode_int = function (_i, _x) {
    while(true) {
      var x = _x;
      var i = _i;
      if (i < 0) {
        return ;
      }
      Caml_array.set(xs, i, Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.logand(x, mask_per_int$1)));
      _x = Belenios_platform__Platform.Z.shift_right(x, 8);
      _i = i - 1 | 0;
      continue ;
    };
  };
  decode_int(n - 1 | 0, Belenios_platform__Platform.Z.shift_right(x, 14));
  return xs;
}

function hash(prefix, xs) {
  var x = prefix + Belenios_core__Common.map_and_concat_with_commas(to_string, xs);
  var z = Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(x));
  return Belenios_platform__Platform.Z.mod(z, l);
}

function hash_to_int(p) {
  var match = to_coordinates(p);
  return Belenios_platform__Platform.Z.hash_to_int(Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.shift_left(match[0], 256), match[1]));
}

var cofactor = Belenios_platform__Platform.Z.of_int(8);

function get_generator(i) {
  var s = Curry._1(Stdlib__Printf.sprintf(/* Format */{
            _0: {
              TAG: /* String_literal */11,
              _0: "ggen|",
              _1: {
                TAG: /* Int */4,
                _0: /* Int_d */0,
                _1: /* No_padding */0,
                _2: /* No_precision */0,
                _3: /* End_of_format */0
              }
            },
            _1: "ggen|%d"
          }), i);
  var base = Belenios_platform__Platform.Z.shift_right(Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(s)), 2);
  var find_element = function (_accu) {
    while(true) {
      var accu = _accu;
      var p = uncompress(accu);
      if (p !== undefined) {
        var p$1 = of_coordinates(p);
        return $star$star$tilde(p$1, cofactor);
      }
      _accu = Belenios_platform__Platform.Z.$plus(accu, Belenios_platform__Platform.Z.one);
      continue ;
    };
  };
  var h = find_element(base);
  if (compare$1(h, one$1) === 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ed25519_pure.ml",
            266,
            2
          ],
          Error: new Error()
        };
  }
  if (compare$1(h, g) === 0) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ed25519_pure.ml",
            267,
            2
          ],
          Error: new Error()
        };
  }
  return h;
}

function selfcheck(param) {
  if (check(one$1) && is_base_point(g) && $eq$tilde($star$star$tilde(g, l), one$1)) {
    return Belenios_platform__Platform.Z.compare(Belenios_platform__Platform.Z.mod(q, eight), five) === 0;
  } else {
    return false;
  }
}

var q$1 = l;

var description = "Ed25519";

export {
  check ,
  one$1 as one,
  g ,
  q$1 as q,
  $star$tilde ,
  $star$star$tilde ,
  $eq$tilde ,
  invert ,
  to_string ,
  of_string ,
  of_ints ,
  to_ints ,
  hash ,
  hash_to_int ,
  compare$1 as compare,
  get_generator ,
  description ,
  selfcheck ,
}
/* q Not a pure module */
