// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_bytes from "melange.runtime/caml_bytes.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Bytes from "melange/./bytes.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_core__Ed25519_pure from "./ed25519_pure.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

function Make(funarg) {
  var bytes = Curry._1(funarg.bytes, undefined);
  var scalarbytes = Curry._1(funarg.scalarbytes, undefined);
  var z255 = Belenios_platform__Platform.Z.of_int(255);
  var of_z_generic = function (n, z) {
    var result = Caml_bytes.caml_create_bytes(n);
    var _i = 0;
    var _z = z;
    while(true) {
      var z$1 = _z;
      var i = _i;
      if (i >= n) {
        return result;
      }
      Caml_bytes.set(result, i, Stdlib.char_of_int(Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.logand(z$1, z255))));
      _z = Belenios_platform__Platform.Z.shift_right(z$1, 8);
      _i = i + 1 | 0;
      continue ;
    };
  };
  var scalar_of_number = function (z) {
    var z$1 = Belenios_platform__Platform.Z.erem(z, Belenios_core__Ed25519_pure.q);
    return of_z_generic(scalarbytes, z$1);
  };
  var number_of_scalar = function (b) {
    var _i = b.length - 1 | 0;
    var _accu = Belenios_platform__Platform.Z.zero;
    while(true) {
      var accu = _accu;
      var i = _i;
      if (i < 0) {
        return accu;
      }
      _accu = Belenios_platform__Platform.Z.logor(Belenios_platform__Platform.Z.shift_left(accu, 8), Belenios_platform__Platform.Z.of_int(Caml_bytes.get(b, i)));
      _i = i - 1 | 0;
      continue ;
    };
  };
  if (64 !== (bytes << 1)) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "ed25519_libsodium.ml",
            69,
            13
          ],
          Error: new Error()
        };
  }
  var point_of_string = function (s) {
    if (s.length !== 64) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ed25519_libsodium.ml",
              72,
              6
            ],
            Error: new Error()
          };
    }
    return of_z_generic(bytes, Belenios_platform__Platform.Z.of_hex(s));
  };
  var string_of_point = function (p) {
    var raw = number_of_scalar(p);
    var r = Belenios_platform__Platform.Z.to_hex(raw);
    var n = r.length;
    if (n > 64) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "ed25519_libsodium.ml",
              79,
              6
            ],
            Error: new Error()
          };
    }
    if (n < 64) {
      return Curry._2(Belenios_core__Common.$$String.make, 64 - n | 0, /* '0' */48) + r;
    } else {
      return r;
    }
  };
  var get_as_pure = function (p) {
    var a = p.pure;
    if (a !== undefined) {
      return Caml_option.valFromOption(a);
    }
    var a$1 = p.nacl;
    if (a$1 === undefined) {
      return Stdlib.failwith("inconsistency in Ed25519_libsodium.get_as_pure");
    }
    var s = string_of_point(a$1);
    var b = Belenios_core__Ed25519_pure.of_string(s);
    p.pure = Caml_option.some(b);
    return b;
  };
  var get_as_nacl = function (p) {
    var a = p.nacl;
    if (a !== undefined) {
      return a;
    }
    var a$1 = p.pure;
    if (a$1 === undefined) {
      return Stdlib.failwith("inconsistency in Ed25519_libsodium.get_as_nacl");
    }
    var s = Belenios_core__Ed25519_pure.to_string(Caml_option.valFromOption(a$1));
    var b = point_of_string(s);
    p.nacl = b;
    return b;
  };
  var check = function (p) {
    var match = p.nacl;
    var match$1 = p.pure;
    if (match !== undefined) {
      if (Curry._1(funarg.is_valid_point, match) === 1) {
        return true;
      } else {
        return Belenios_core__Ed25519_pure.check(get_as_pure(p));
      }
    } else if (match$1 !== undefined) {
      return Belenios_core__Ed25519_pure.check(Caml_option.valFromOption(match$1));
    } else {
      return Stdlib.failwith("inconsistency in Ed25519_libsodium.check");
    }
  };
  var one = {
    pure: Caml_option.some(Belenios_core__Ed25519_pure.one),
    nacl: undefined
  };
  var g = {
    pure: Caml_option.some(Belenios_core__Ed25519_pure.g),
    nacl: undefined
  };
  var $star$tilde = function (a, b) {
    var r = Caml_bytes.caml_create_bytes(bytes);
    if (Curry._3(funarg.add, r, get_as_nacl(a), get_as_nacl(b)) === 0) {
      return {
              pure: undefined,
              nacl: r
            };
    }
    var p = Belenios_core__Ed25519_pure.$star$tilde(get_as_pure(a), get_as_pure(b));
    return {
            pure: Caml_option.some(p),
            nacl: undefined
          };
  };
  var $star$star$tilde = function (p, n) {
    var r = Caml_bytes.caml_create_bytes(bytes);
    if (Curry._3(funarg.scalarmult, r, scalar_of_number(n), get_as_nacl(p)) === 0) {
      return {
              pure: undefined,
              nacl: r
            };
    }
    var p$1 = Belenios_core__Ed25519_pure.$star$star$tilde(get_as_pure(p), n);
    return {
            pure: Caml_option.some(p$1),
            nacl: undefined
          };
  };
  var compare = function (a, b) {
    var match = a.pure;
    var match$1 = b.pure;
    var match$2 = a.nacl;
    var match$3 = b.nacl;
    if (match !== undefined && match$1 !== undefined) {
      return Belenios_core__Ed25519_pure.compare(Caml_option.valFromOption(match), Caml_option.valFromOption(match$1));
    }
    if (match$2 !== undefined) {
      if (match$3 !== undefined) {
        return Stdlib__Bytes.compare(match$2, match$3);
      } else {
        return Stdlib__Bytes.compare(match$2, get_as_nacl(b));
      }
    } else if (match$3 !== undefined) {
      return Stdlib__Bytes.compare(get_as_nacl(a), match$3);
    } else {
      return Belenios_core__Ed25519_pure.compare(get_as_pure(a), get_as_pure(b));
    }
  };
  var $eq$tilde = function (a, b) {
    return compare(a, b) === 0;
  };
  var invert = function (p) {
    var p$1 = Belenios_core__Ed25519_pure.invert(get_as_pure(p));
    return {
            pure: Caml_option.some(p$1),
            nacl: undefined
          };
  };
  var to_string = function (p) {
    return string_of_point(get_as_nacl(p));
  };
  var of_string = function (s) {
    var p = point_of_string(s);
    return {
            pure: undefined,
            nacl: p
          };
  };
  var to_ints = function (n, p) {
    return Belenios_core__Ed25519_pure.to_ints(n, get_as_pure(p));
  };
  var of_ints = function (xs) {
    var p = Belenios_core__Ed25519_pure.of_ints(xs);
    return {
            pure: Caml_option.some(p),
            nacl: undefined
          };
  };
  var get_generator = function (i) {
    var p = Belenios_core__Ed25519_pure.get_generator(i);
    return {
            pure: Caml_option.some(p),
            nacl: undefined
          };
  };
  var hash = function (prefix, xs) {
    var x = prefix + Belenios_core__Common.map_and_concat_with_commas(to_string, xs);
    var z = Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(x));
    return Belenios_platform__Platform.Z.mod(z, Belenios_core__Ed25519_pure.q);
  };
  var hash_to_int = function (p) {
    return Belenios_core__Ed25519_pure.hash_to_int(get_as_pure(p));
  };
  var selfcheck = function (param) {
    if (!check(one)) {
      return false;
    }
    if (!check(g)) {
      return false;
    }
    if (Belenios_core__Ed25519_pure.compare(get_as_pure(g), Belenios_core__Ed25519_pure.g) !== 0) {
      return false;
    }
    if (!$eq$tilde($star$tilde($star$star$tilde(g, Belenios_platform__Platform.Z.$neg(Belenios_core__Ed25519_pure.q, Belenios_platform__Platform.Z.one)), g), one)) {
      return false;
    }
    var p = Belenios_core__Ed25519_pure.invert(get_as_pure(g));
    return $eq$tilde($star$tilde(g, {
                    pure: Caml_option.some(p),
                    nacl: undefined
                  }), one);
  };
  return {
          check: check,
          one: one,
          g: g,
          q: Belenios_core__Ed25519_pure.q,
          $star$tilde: $star$tilde,
          $star$star$tilde: $star$star$tilde,
          $eq$tilde: $eq$tilde,
          invert: invert,
          to_string: to_string,
          of_string: of_string,
          of_ints: of_ints,
          to_ints: to_ints,
          hash: hash,
          hash_to_int: hash_to_int,
          compare: compare,
          get_generator: get_generator,
          description: "Ed25519",
          selfcheck: selfcheck
        };
}

export {
  Make ,
}
/* Belenios_core__Common Not a pure module */
