// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

function check_params(param) {
  var embedding = param.embedding;
  var q = param.q;
  var p = param.p;
  var g = param.g;
  var tmp;
  if (embedding !== undefined) {
    var bits_per_int = embedding.bits_per_int;
    tmp = embedding.padding > 0 && bits_per_int > 0 && bits_per_int < 32;
  } else {
    tmp = true;
  }
  if (tmp && Belenios_platform__Platform.Z.probab_prime(p, 20) > 0 && Belenios_platform__Platform.Z.probab_prime(q, 20) > 0 && Belenios_core__Common.check_modulo(p, g) && Belenios_core__Common.check_modulo(p, q)) {
    return Belenios_platform__Platform.Z.$eq$percent(Belenios_platform__Platform.Z.powm(g, q, p), Belenios_platform__Platform.Z.one);
  } else {
    return false;
  }
}

function make(description, ff_params) {
  var embedding = ff_params.embedding;
  var q = ff_params.q;
  var p = ff_params.p;
  var g = ff_params.g;
  var one = Belenios_platform__Platform.Z.one;
  var $star$tilde = function (a, b) {
    return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.$star(a, b), p);
  };
  var $star$star$tilde = function (a, b) {
    return Belenios_platform__Platform.Z.powm(a, b, p);
  };
  var invert = function (x) {
    return Belenios_platform__Platform.Z.invert(x, p);
  };
  var $eq$tilde = Belenios_platform__Platform.Z.$eq$percent;
  var check = function (x) {
    if (Belenios_core__Common.check_modulo(p, x)) {
      return Curry._2($eq$tilde, $star$star$tilde(x, q), one);
    } else {
      return false;
    }
  };
  var to_string = Belenios_platform__Platform.Z.to_string;
  var of_string = Belenios_platform__Platform.Z.of_string;
  var of_ints;
  if (embedding !== undefined) {
    var bits_per_int = embedding.bits_per_int;
    var padding = embedding.padding;
    var mask_per_int = (1 << bits_per_int) - 1 | 0;
    of_ints = (function (xs) {
        var n = xs.length;
        var encode_int = function (_i, _accu) {
          while(true) {
            var accu = _accu;
            var i = _i;
            if (i >= n) {
              return Belenios_platform__Platform.Z.shift_left(accu, padding);
            }
            var x = Caml_array.get(xs, i) & mask_per_int;
            _accu = Belenios_platform__Platform.Z.$plus(Belenios_platform__Platform.Z.shift_left(accu, bits_per_int), Belenios_platform__Platform.Z.of_int(x));
            _i = i + 1 | 0;
            continue ;
          };
        };
        var _accu = encode_int(0, Belenios_platform__Platform.Z.zero);
        while(true) {
          var accu = _accu;
          if (check(accu)) {
            return accu;
          }
          _accu = Belenios_platform__Platform.Z.$plus(accu, one);
          continue ;
        };
      });
  } else {
    of_ints = (function (param) {
        return Stdlib.failwith("Group_field.of_bits: missing parameters");
      });
  }
  var to_ints;
  if (embedding !== undefined) {
    var bits_per_int$1 = embedding.bits_per_int;
    var padding$1 = embedding.padding;
    var mask_per_int$1 = Belenios_platform__Platform.Z.$neg(Belenios_platform__Platform.Z.shift_left(one, bits_per_int$1), one);
    to_ints = (function (n, x) {
        var xs = Caml_array.make(n, 0);
        var decode_int = function (_i, _x) {
          while(true) {
            var x = _x;
            var i = _i;
            if (i < 0) {
              return ;
            }
            Caml_array.set(xs, i, Belenios_platform__Platform.Z.to_int(Belenios_platform__Platform.Z.logand(x, mask_per_int$1)));
            _x = Belenios_platform__Platform.Z.shift_right(x, bits_per_int$1);
            _i = i - 1 | 0;
            continue ;
          };
        };
        decode_int(n - 1 | 0, Belenios_platform__Platform.Z.shift_right(x, padding$1));
        return xs;
      });
  } else {
    to_ints = (function (param) {
        return Stdlib.failwith("Group_field.to_bits: missing parameters");
      });
  }
  var hash = function (prefix, xs) {
    var x = prefix + Belenios_core__Common.map_and_concat_with_commas(Belenios_platform__Platform.Z.to_string, xs);
    var z = Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(x));
    return Belenios_platform__Platform.Z.mod(z, q);
  };
  var hash_to_int = Belenios_platform__Platform.Z.hash_to_int;
  var compare = Belenios_platform__Platform.Z.compare;
  var cofactor = Belenios_platform__Platform.Z.$slash(Belenios_platform__Platform.Z.$neg(p, Belenios_platform__Platform.Z.one), q);
  var get_generator = function (i) {
    var s = Curry._1(Stdlib__Printf.sprintf(/* Format */{
              _0: {
                TAG: /* String_literal */11,
                _0: "ggen|",
                _1: {
                  TAG: /* Int */4,
                  _0: /* Int_d */0,
                  _1: /* No_padding */0,
                  _2: /* No_precision */0,
                  _3: /* End_of_format */0
                }
              },
              _1: "ggen|%d"
            }), i);
    var h = Belenios_platform__Platform.Z.of_hex(Belenios_platform__Platform.sha256_hex(s));
    var h$1 = Belenios_platform__Platform.Z.powm(h, cofactor, p);
    if (Belenios_platform__Platform.Z.compare(h$1, Belenios_platform__Platform.Z.zero) === 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "group_field.ml",
              113,
              8
            ],
            Error: new Error()
          };
    }
    if (Belenios_platform__Platform.Z.compare(h$1, Belenios_platform__Platform.Z.one) === 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "group_field.ml",
              114,
              8
            ],
            Error: new Error()
          };
    }
    if (Belenios_platform__Platform.Z.compare(h$1, g) === 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "group_field.ml",
              115,
              8
            ],
            Error: new Error()
          };
    }
    return h$1;
  };
  return {
          check: check,
          one: one,
          g: g,
          q: q,
          $star$tilde: $star$tilde,
          $star$star$tilde: $star$star$tilde,
          $eq$tilde: $eq$tilde,
          invert: invert,
          to_string: to_string,
          of_string: of_string,
          of_ints: of_ints,
          to_ints: to_ints,
          hash: hash,
          hash_to_int: hash_to_int,
          compare: compare,
          get_generator: get_generator,
          description: description
        };
}

export {
  check_params ,
  make ,
}
/* Belenios_core__Common Not a pure module */
