// Generated by Melange

import * as Caml_array from "melange.runtime/caml_array.js";
import * as Stdlib__List from "melange/./list.js";
import * as Stdlib__Array from "melange/./array.js";

function compute_matrix(ngrades, nchoices, blank_allowed, ballots) {
  var n = ballots.length;
  var raw = Stdlib__Array.make_matrix(nchoices, ngrades, 0);
  var add_ballot = function (_i, _invalid, _blank, _valid) {
    while(true) {
      var valid = _valid;
      var blank = _blank;
      var invalid = _invalid;
      var i = _i;
      if (i >= n) {
        return [
                invalid,
                blank,
                valid
              ];
      }
      var ballot = Caml_array.get(ballots, i);
      if (nchoices !== ballot.length) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "majority_judgment.ml",
                30,
                6
              ],
              Error: new Error()
            };
      }
      var check = (function(ballot){
      return function check(_j) {
        while(true) {
          var j = _j;
          if (j >= nchoices) {
            return j;
          }
          var grade = Caml_array.get(ballot, j);
          if (!(0 < grade && grade <= ngrades)) {
            return j;
          }
          _j = j + 1 | 0;
          continue ;
        };
      }
      }(ballot));
      var is_blank_ballot = (function(ballot){
      return function is_blank_ballot(_j) {
        while(true) {
          var j = _j;
          if (j >= nchoices) {
            return true;
          }
          if (Caml_array.get(ballot, j) !== 0) {
            return false;
          }
          _j = j + 1 | 0;
          continue ;
        };
      }
      }(ballot));
      if (check(0) === nchoices) {
        var fill = (function(ballot){
        return function fill(_j) {
          while(true) {
            var j = _j;
            if (j >= nchoices) {
              return ;
            }
            var grade = Caml_array.get(ballot, j) - 1 | 0;
            Caml_array.set(Caml_array.get(raw, j), grade, Caml_array.get(Caml_array.get(raw, j), grade) + 1 | 0);
            _j = j + 1 | 0;
            continue ;
          };
        }
        }(ballot));
        fill(0);
        _valid = valid + 1 | 0;
        _i = i + 1 | 0;
        continue ;
      }
      if (blank_allowed && is_blank_ballot(0)) {
        _blank = blank + 1 | 0;
        _i = i + 1 | 0;
        continue ;
      }
      _invalid = {
        hd: ballot,
        tl: invalid
      };
      _i = i + 1 | 0;
      continue ;
    };
  };
  var match = add_ballot(0, /* [] */0, 0, 0);
  var blank = match[1];
  var blank$1;
  if (blank_allowed) {
    blank$1 = blank;
  } else {
    if (blank !== 0) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "majority_judgment.ml",
              68,
              6
            ],
            Error: new Error()
          };
    }
    blank$1 = undefined;
  }
  return [
          raw,
          Stdlib__Array.of_list(match[0]),
          blank$1,
          match[2]
        ];
}

function compute_increasing_vector(grades) {
  var sum = Stdlib__Array.fold_left((function (prim0, prim1) {
          return prim0 + prim1 | 0;
        }), 0, grades);
  var res = Caml_array.make(sum, -1);
  var ngrades = grades.length;
  var $$process = function (_i, _grade) {
    while(true) {
      var grade = _grade;
      var i = _i;
      if (grade < ngrades) {
        var x = Caml_array.get(grades, grade);
        if ((i + x | 0) > sum) {
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "majority_judgment.ml",
                  81,
                  6
                ],
                Error: new Error()
              };
        }
        var fill = (function(grade){
        return function fill(_j, _n) {
          while(true) {
            var n = _n;
            var j = _j;
            if (n <= 0) {
              return j;
            }
            Caml_array.set(res, j, grade);
            _n = n - 1 | 0;
            _j = j + 1 | 0;
            continue ;
          };
        }
        }(grade));
        var j = fill(i, x);
        _grade = grade + 1 | 0;
        _i = j;
        continue ;
      }
      if (i === sum) {
        return ;
      }
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "majority_judgment.ml",
              90,
              11
            ],
            Error: new Error()
          };
    };
  };
  $$process(0, 0);
  return res;
}

function compute_median_sequence(increasing_vector) {
  var n = increasing_vector.length;
  var tmp = Stdlib__Array.copy(increasing_vector);
  var res = Caml_array.make(n, 0);
  for(var i = 0; i < n; ++i){
    var n$p = n - i | 0;
    var imedian = ((n$p + 1 | 0) / 2 | 0) - 1 | 0;
    Caml_array.set(res, i, Caml_array.get(tmp, imedian));
    Stdlib__Array.blit(tmp, imedian + 1 | 0, tmp, imedian, (n$p - 1 | 0) - imedian | 0);
  }
  return res;
}

function lex_compare(a, b) {
  var n = a.length;
  if (n !== b.length) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "majority_judgment.ml",
            109,
            2
          ],
          Error: new Error()
        };
  }
  var _i = 0;
  while(true) {
    var i = _i;
    if (i >= n) {
      return 0;
    }
    var x = Caml_array.get(a, i) - Caml_array.get(b, i) | 0;
    if (x !== 0) {
      return x;
    }
    _i = i + 1 | 0;
    continue ;
  };
}

function compute_winners(matrix) {
  var n = matrix.length;
  var sorted = Stdlib__Array.mapi((function (i, x) {
          return [
                  i,
                  x
                ];
        }), Stdlib__Array.map(compute_median_sequence, Stdlib__Array.map(compute_increasing_vector, matrix)));
  Stdlib__Array.sort((function (param, param$1) {
          return lex_compare(param[1], param$1[1]);
        }), sorted);
  var _i = 0;
  var _accu = /* [] */0;
  while(true) {
    var accu = _accu;
    var i = _i;
    if (i >= n) {
      return Stdlib__List.rev(accu);
    }
    var match = Caml_array.get(sorted, i);
    var aa = match[1];
    var exaequos = (function(aa){
    return function exaequos(_j, _accu) {
      while(true) {
        var accu = _accu;
        var j = _j;
        if (j >= n) {
          return [
                  j,
                  accu
                ];
        }
        var match = Caml_array.get(sorted, j);
        if (lex_compare(aa, match[1]) !== 0) {
          return [
                  j,
                  accu
                ];
        }
        _accu = {
          hd: match[0],
          tl: accu
        };
        _j = j + 1 | 0;
        continue ;
      };
    }
    }(aa));
    var match$1 = exaequos(i + 1 | 0, {
          hd: match[0],
          tl: /* [] */0
        });
    _accu = {
      hd: match$1[1],
      tl: accu
    };
    _i = match$1[0];
    continue ;
  };
}

function compute(ngrades, nchoices, blank_allowed, ballots) {
  var match = compute_matrix(ngrades, nchoices, blank_allowed, ballots);
  var mj_raw = match[0];
  var mj_winners = compute_winners(mj_raw);
  return {
          mj_raw: mj_raw,
          mj_valid: match[3],
          mj_blank: match[2],
          mj_invalid: match[1],
          mj_winners: mj_winners
        };
}

export {
  compute ,
}
/* No side effect */
