// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Yojson from "../../../../belenios_compat_melange/yojson.js";
import * as CamlinternalLazy from "melange/./camlinternalLazy.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_core__Common_types from "./common_types.js";
import * as Belenios_core__Question_h_j from "./question_h_j.js";
import * as Belenios_core__Question_nh_j from "./question_nh_j.js";

function compute_signature(qs) {
  if (!qs) {
    return {
            x: /* Nil */0
          };
  }
  var match = qs.hd;
  if (match.TAG === /* Homomorphic */0) {
    var X = compute_signature(qs.tl);
    var x = {
      TAG: /* Homomorphic */0,
      _0: X.x
    };
    return {
            x: x
          };
  }
  var X$1 = compute_signature(qs.tl);
  var x_0 = match._0.q_answers.length;
  var x_1 = X$1.x;
  var x$1 = {
    TAG: /* NonHomomorphic */1,
    _0: x_0,
    _1: x_1
  };
  return {
          x: x$1
        };
}

function wrap(x) {
  if (typeof x === "string") {
    return Stdlib.failwith("Question.wrap: unexpected JSON value");
  }
  if (x.NAME !== "Assoc") {
    return Stdlib.failwith("Question.wrap: unexpected JSON value");
  }
  var o = x.VAL;
  var match = Curry._2(Belenios_core__Common.List.assoc_opt, "type", o);
  if (match === undefined) {
    return {
            TAG: /* Homomorphic */0,
            _0: Belenios_core__Question_h_j.question_of_string(Yojson.Safe.to_string(x))
          };
  }
  if (typeof match === "string") {
    return Stdlib.failwith("Question.wrap: unexpected type");
  }
  if (match.NAME !== "String") {
    return Stdlib.failwith("Question.wrap: unexpected type");
  }
  if (match.VAL !== "NonHomomorphic") {
    return Stdlib.failwith("Question.wrap: unexpected type");
  }
  var v = Curry._2(Belenios_core__Common.List.assoc_opt, "value", o);
  if (v !== undefined) {
    return {
            TAG: /* NonHomomorphic */1,
            _0: Belenios_core__Question_nh_j.question_of_string(Yojson.Safe.to_string(v)),
            _1: Curry._2(Belenios_core__Common.List.assoc_opt, "extra", o)
          };
  } else {
    return Stdlib.failwith("Question.wrap: value is missing");
  }
}

function unwrap(q) {
  if (q.TAG === /* Homomorphic */0) {
    return Yojson.Safe.from_string(Belenios_core__Question_h_j.string_of_question(q._0));
  }
  var extra = q._1;
  var o = extra !== undefined ? ({
        hd: [
          "extra",
          extra
        ],
        tl: /* [] */0
      }) : /* [] */0;
  var o_0 = [
    "type",
    {
      NAME: "String",
      VAL: "NonHomomorphic"
    }
  ];
  var o_1 = {
    hd: [
      "value",
      Yojson.Safe.from_string(Belenios_core__Question_nh_j.string_of_question(q._0))
    ],
    tl: o
  };
  var o$1 = {
    hd: o_0,
    tl: o_1
  };
  return {
          NAME: "Assoc",
          VAL: o$1
        };
}

function get_counting_method(extra) {
  if (extra === undefined) {
    return "None";
  }
  if (typeof extra === "string") {
    return "None";
  }
  if (extra.NAME !== "Assoc") {
    return "None";
  }
  var match = Curry._2(Belenios_core__Common.List.assoc_opt, "method", extra.VAL);
  if (match === undefined) {
    return "None";
  }
  if (typeof match === "string") {
    return "None";
  }
  if (match.NAME !== "String") {
    return "None";
  }
  switch (match.VAL) {
    case "MajorityJudgment" :
        var x;
        try {
          x = Belenios_core__Question_nh_j.mj_extra_of_string(Yojson.Safe.to_string(extra));
        }
        catch (exn){
          return "None";
        }
        return {
                NAME: "MajorityJudgment",
                VAL: x
              };
    case "Schulze" :
        var x$1;
        try {
          x$1 = Belenios_core__Question_nh_j.schulze_extra_of_string(Yojson.Safe.to_string(extra));
        }
        catch (exn$1){
          return "None";
        }
        return {
                NAME: "Schulze",
                VAL: x$1
              };
    default:
      return "None";
  }
}

function erase_question(q) {
  if (q.TAG !== /* Homomorphic */0) {
    return {
            TAG: /* NonHomomorphic */1,
            _0: {
              q_answers: Curry._2(Belenios_core__Common_types.$$Array.map, (function (param) {
                      return "";
                    }), q._0.q_answers),
              q_question: ""
            },
            _1: q._1
          };
  }
  var q$1 = q._0;
  return {
          TAG: /* Homomorphic */0,
          _0: {
            q_answers: Curry._2(Belenios_core__Common_types.$$Array.map, (function (param) {
                    return "";
                  }), q$1.q_answers),
            q_blank: q$1.q_blank,
            q_min: q$1.q_min,
            q_max: q$1.q_max,
            q_question: ""
          }
        };
}

function Make(M, G, QHomomorphic, QNonHomomorphic) {
  var create_answer = function (q, public_key, prefix, m) {
    if (q.TAG === /* Homomorphic */0) {
      var answer = Curry._4(QHomomorphic.create_answer, q._0, public_key, prefix, m);
      return Yojson.Safe.from_string(Belenios_core__Question_h_j.string_of_answer((function (param) {
                        return Belenios_core__Common.swrite(G.to_string, param);
                      }), answer));
    }
    var answer$1 = Curry._4(QNonHomomorphic.create_answer, q._0, public_key, prefix, m);
    return Yojson.Safe.from_string(Belenios_core__Question_nh_j.string_of_answer((function (param) {
                      return Belenios_core__Common.swrite(G.to_string, param);
                    }), answer$1));
  };
  var verify_answer = function (q, public_key, prefix, a) {
    if (q.TAG === /* Homomorphic */0) {
      return Curry._4(QHomomorphic.verify_answer, q._0, public_key, prefix, Belenios_core__Question_h_j.answer_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), Yojson.Safe.to_string(a)));
    } else {
      return Curry._4(QNonHomomorphic.verify_answer, q._0, public_key, prefix, Belenios_core__Question_nh_j.answer_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), Yojson.Safe.to_string(a)));
    }
  };
  var extract_ciphertexts = function (q, a) {
    if (q.TAG === /* Homomorphic */0) {
      return Curry._2(QHomomorphic.extract_ciphertexts, q._0, Belenios_core__Question_h_j.answer_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), Yojson.Safe.to_string(a)));
    } else {
      return Curry._2(QNonHomomorphic.extract_ciphertexts, q._0, Belenios_core__Question_nh_j.answer_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), Yojson.Safe.to_string(a)));
    }
  };
  var process_ciphertexts = function (q, e) {
    if (q.TAG === /* Homomorphic */0) {
      return Curry._2(QHomomorphic.process_ciphertexts, q._0, e);
    } else {
      return Curry._2(QNonHomomorphic.process_ciphertexts, q._0, e);
    }
  };
  var compute_result = function (num_tallied, qs, x) {
    if (x.NAME !== "Array") {
      return Stdlib.invalid_arg("compute_result: invalid result");
    }
    var compute_h = {
      LAZY_DONE: false,
      VAL: (function () {
          return Curry._1(QHomomorphic.compute_result, num_tallied);
        })
    };
    var loop = function (qs, xs) {
      if (typeof qs === "number") {
        if (xs) {
          return Stdlib.invalid_arg("compute_result: list too long");
        } else {
          return /* Nil */0;
        }
      } else if (qs.TAG === /* Homomorphic */0) {
        if (xs) {
          return {
                  TAG: /* Homomorphic */0,
                  _0: Curry._1(CamlinternalLazy.force(compute_h), xs.hd),
                  _1: loop(qs._0, xs.tl)
                };
        } else {
          return Stdlib.invalid_arg("compute_result: list too short");
        }
      } else if (xs) {
        return {
                TAG: /* NonHomomorphic */1,
                _0: Curry._2(QNonHomomorphic.compute_result, qs._0, xs.hd),
                _1: loop(qs._1, xs.tl)
              };
      } else {
        return Stdlib.invalid_arg("compute_result: list too short");
      }
    };
    return loop(qs, Curry._1(Belenios_core__Common_types.$$Array.to_list, x.VAL));
  };
  var check_result = function (num_tallied, qs, x, rs) {
    if (x.NAME !== "Array") {
      return Stdlib.invalid_arg("check_result: invalid result");
    }
    var _qs = qs;
    var _xs = Curry._1(Belenios_core__Common_types.$$Array.to_list, x.VAL);
    var _rs = rs;
    while(true) {
      var rs$1 = _rs;
      var xs = _xs;
      var qs$1 = _qs;
      if (typeof qs$1 === "number") {
        if (xs) {
          if (typeof rs$1 === "number") {
            return Stdlib.invalid_arg("check_result: list too long");
          } else {
            return Stdlib.invalid_arg("check_result: list too short");
          }
        } else if (typeof rs$1 === "number") {
          return true;
        } else {
          return Stdlib.invalid_arg("check_result: list too short");
        }
      }
      if (qs$1.TAG === /* Homomorphic */0) {
        if (!xs) {
          return Stdlib.invalid_arg("check_result: list too short");
        }
        if (!Curry._3(QHomomorphic.check_result, num_tallied, xs.hd, rs$1._0)) {
          return false;
        }
        _rs = rs$1._1;
        _xs = xs.tl;
        _qs = qs$1._0;
        continue ;
      }
      if (!xs) {
        return Stdlib.invalid_arg("check_result: list too short");
      }
      if (!Curry._3(QNonHomomorphic.check_result, qs$1._0, xs.hd, rs$1._0)) {
        return false;
      }
      _rs = rs$1._1;
      _xs = xs.tl;
      _qs = qs$1._1;
      continue ;
    };
  };
  return {
          create_answer: create_answer,
          verify_answer: verify_answer,
          extract_ciphertexts: extract_ciphertexts,
          process_ciphertexts: process_ciphertexts,
          compute_result: compute_result,
          check_result: check_result
        };
}

export {
  compute_signature ,
  wrap ,
  unwrap ,
  get_counting_method ,
  erase_question ,
  Make ,
}
/* Belenios_core__Common Not a pure module */
