// Generated by Melange

import * as Atdgen_codec_decode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_decode.js";
import * as Atdgen_codec_encode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_encode.js";
import * as Belenios_core__Serializable_core_bs from "./serializable_core_bs.js";

var write_schulze_extra = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.bool, "blank", t.schulze_extra_blank),
                  tl: /* [] */0
                });
    });

function string_of_schulze_extra(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_schulze_extra, x));
}

var read_schulze_extra = Atdgen_codec_decode.make(function (json) {
      return {
              schulze_extra_blank: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("blank", Atdgen_codec_decode.bool, param);
                    }), json)
            };
    });

function schulze_extra_of_string(s) {
  return Atdgen_codec_decode.decode(read_schulze_extra, JSON.parse(s));
}

function write__x_20d39e2(param) {
  return Atdgen_codec_encode.array(Atdgen_codec_encode.string, param);
}

function read__x_20d39e2(param) {
  return Atdgen_codec_decode.array(Atdgen_codec_decode.string, param);
}

var write_question = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, write__x_20d39e2, "answers", t.q_answers),
                  tl: {
                    hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "question", t.q_question),
                    tl: /* [] */0
                  }
                });
    });

function string_of_question(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_question, x));
}

var read_question = Atdgen_codec_decode.make(function (json) {
      return {
              q_answers: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("answers", read__x_20d39e2, param);
                    }), json),
              q_question: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("question", Atdgen_codec_decode.string, param);
                    }), json)
            };
    });

function question_of_string(s) {
  return Atdgen_codec_decode.decode(read_question, JSON.parse(s));
}

function string_of_proof(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(Belenios_core__Serializable_core_bs.write_proof, x));
}

function proof_of_string(s) {
  return Atdgen_codec_decode.decode(Belenios_core__Serializable_core_bs.read_proof, JSON.parse(s));
}

var write_mj_extra = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.bool, "blank", t.mj_extra_blank),
                  tl: {
                    hd: Atdgen_codec_encode.field(undefined, write__x_20d39e2, "grades", t.mj_extra_grades),
                    tl: /* [] */0
                  }
                });
    });

function string_of_mj_extra(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_mj_extra, x));
}

var read_mj_extra = Atdgen_codec_decode.make(function (json) {
      return {
              mj_extra_blank: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("blank", Atdgen_codec_decode.bool, param);
                    }), json),
              mj_extra_grades: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("grades", read__x_20d39e2, param);
                    }), json)
            };
    });

function mj_extra_of_string(s) {
  return Atdgen_codec_decode.decode(read_mj_extra, JSON.parse(s));
}

var write_ciphertext = Belenios_core__Serializable_core_bs.write_ciphertext;

function string_of_ciphertext(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(Belenios_core__Serializable_core_bs.write_ciphertext(write__a), x));
}

var read_ciphertext = Belenios_core__Serializable_core_bs.read_ciphertext;

function ciphertext_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(Belenios_core__Serializable_core_bs.read_ciphertext(read__a), JSON.parse(s));
}

function write_answer(write__a) {
  return Atdgen_codec_encode.make(function (t) {
              return Atdgen_codec_encode.obj({
                          hd: Atdgen_codec_encode.field(undefined, Belenios_core__Serializable_core_bs.write_ciphertext(write__a), "choices", t.choices),
                          tl: {
                            hd: Atdgen_codec_encode.field(undefined, Belenios_core__Serializable_core_bs.write_proof, "proof", t.proof),
                            tl: /* [] */0
                          }
                        });
            });
}

function string_of_answer(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_answer(write__a), x));
}

function read_answer(read__a) {
  return Atdgen_codec_decode.make(function (json) {
              var partial_arg = Belenios_core__Serializable_core_bs.read_ciphertext(read__a);
              return {
                      choices: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("choices", partial_arg, param);
                            }), json),
                      proof: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("proof", Belenios_core__Serializable_core_bs.read_proof, param);
                            }), json)
                    };
            });
}

function answer_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(read_answer(read__a), JSON.parse(s));
}

var read_proof = Belenios_core__Serializable_core_bs.read_proof;

var write_proof = Belenios_core__Serializable_core_bs.write_proof;

export {
  read_schulze_extra ,
  schulze_extra_of_string ,
  write_schulze_extra ,
  string_of_schulze_extra ,
  read_question ,
  question_of_string ,
  write_question ,
  string_of_question ,
  read_proof ,
  proof_of_string ,
  write_proof ,
  string_of_proof ,
  read_mj_extra ,
  mj_extra_of_string ,
  write_mj_extra ,
  string_of_mj_extra ,
  read_ciphertext ,
  ciphertext_of_string ,
  write_ciphertext ,
  string_of_ciphertext ,
  read_answer ,
  answer_of_string ,
  write_answer ,
  string_of_answer ,
}
/* write_schulze_extra Not a pure module */
