// Generated by Melange

import * as Atdgen_codec_decode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_decode.js";
import * as Atdgen_codec_encode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_encode.js";
import * as Belenios_core__Serializable_core_bs from "./serializable_core_bs.js";

function write__x_20d39e2(param) {
  return Atdgen_codec_encode.array(Atdgen_codec_encode.string, param);
}

function read__x_20d39e2(param) {
  return Atdgen_codec_decode.array(Atdgen_codec_decode.string, param);
}

Atdgen_codec_decode.option_as_constr(Atdgen_codec_decode.bool);

var write_question = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, write__x_20d39e2, "answers", t.q_answers),
                  tl: {
                    hd: Atdgen_codec_encode.field_o(undefined, Atdgen_codec_encode.bool, "blank", t.q_blank),
                    tl: {
                      hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.$$int, "min", t.q_min),
                      tl: {
                        hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.$$int, "max", t.q_max),
                        tl: {
                          hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "question", t.q_question),
                          tl: /* [] */0
                        }
                      }
                    }
                  }
                });
    });

function string_of_question(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_question, x));
}

var read_question = Atdgen_codec_decode.make(function (json) {
      return {
              q_answers: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("answers", read__x_20d39e2, param);
                    }), json),
              q_blank: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.fieldOptional("blank", Atdgen_codec_decode.bool, param);
                    }), json),
              q_min: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("min", Atdgen_codec_decode.$$int, param);
                    }), json),
              q_max: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("max", Atdgen_codec_decode.$$int, param);
                    }), json),
              q_question: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("question", Atdgen_codec_decode.string, param);
                    }), json)
            };
    });

function question_of_string(s) {
  return Atdgen_codec_decode.decode(read_question, JSON.parse(s));
}

function string_of_disjunctive_proof(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(Belenios_core__Serializable_core_bs.write_disjunctive_proof, x));
}

function disjunctive_proof_of_string(s) {
  return Atdgen_codec_decode.decode(Belenios_core__Serializable_core_bs.read_disjunctive_proof, JSON.parse(s));
}

var write_ciphertext = Belenios_core__Serializable_core_bs.write_ciphertext;

function string_of_ciphertext(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(Belenios_core__Serializable_core_bs.write_ciphertext(write__a), x));
}

var read_ciphertext = Belenios_core__Serializable_core_bs.read_ciphertext;

function ciphertext_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(Belenios_core__Serializable_core_bs.read_ciphertext(read__a), JSON.parse(s));
}

function write__x_4ad4c69(param) {
  return Atdgen_codec_encode.array(Belenios_core__Serializable_core_bs.write_disjunctive_proof, param);
}

function read__x_4ad4c69(param) {
  return Atdgen_codec_decode.array(Belenios_core__Serializable_core_bs.read_disjunctive_proof, param);
}

Atdgen_codec_decode.option_as_constr(Belenios_core__Serializable_core_bs.read_disjunctive_proof);

function write_answer(write__a) {
  return Atdgen_codec_encode.make(function (t) {
              var partial_arg = Belenios_core__Serializable_core_bs.write_ciphertext(write__a);
              return Atdgen_codec_encode.obj({
                          hd: Atdgen_codec_encode.field(undefined, (function (param) {
                                  return Atdgen_codec_encode.array(partial_arg, param);
                                }), "choices", t.choices),
                          tl: {
                            hd: Atdgen_codec_encode.field(undefined, write__x_4ad4c69, "individual_proofs", t.individual_proofs),
                            tl: {
                              hd: Atdgen_codec_encode.field(undefined, Belenios_core__Serializable_core_bs.write_disjunctive_proof, "overall_proof", t.overall_proof),
                              tl: {
                                hd: Atdgen_codec_encode.field_o(undefined, Belenios_core__Serializable_core_bs.write_disjunctive_proof, "blank_proof", t.blank_proof),
                                tl: /* [] */0
                              }
                            }
                          }
                        });
            });
}

function string_of_answer(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_answer(write__a), x));
}

function read_answer(read__a) {
  return Atdgen_codec_decode.make(function (json) {
              var partial_arg = Belenios_core__Serializable_core_bs.read_ciphertext(read__a);
              var partial_arg$1 = function (param) {
                return Atdgen_codec_decode.array(partial_arg, param);
              };
              return {
                      choices: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("choices", partial_arg$1, param);
                            }), json),
                      individual_proofs: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("individual_proofs", read__x_4ad4c69, param);
                            }), json),
                      overall_proof: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("overall_proof", Belenios_core__Serializable_core_bs.read_disjunctive_proof, param);
                            }), json),
                      blank_proof: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.fieldOptional("blank_proof", Belenios_core__Serializable_core_bs.read_disjunctive_proof, param);
                            }), json)
                    };
            });
}

function answer_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(read_answer(read__a), JSON.parse(s));
}

var read_disjunctive_proof = Belenios_core__Serializable_core_bs.read_disjunctive_proof;

var write_disjunctive_proof = Belenios_core__Serializable_core_bs.write_disjunctive_proof;

export {
  read_question ,
  question_of_string ,
  write_question ,
  string_of_question ,
  read_disjunctive_proof ,
  disjunctive_proof_of_string ,
  write_disjunctive_proof ,
  string_of_disjunctive_proof ,
  read_ciphertext ,
  ciphertext_of_string ,
  write_ciphertext ,
  string_of_ciphertext ,
  read_answer ,
  answer_of_string ,
  write_answer ,
  string_of_answer ,
}
/*  Not a pure module */
