// Generated by Melange

import * as Stdlib from "melange/./stdlib.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Stdlib__List from "melange/./list.js";
import * as Stdlib__Array from "melange/./array.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";

function compare(param, param$1) {
  var w2 = param$1[0];
  var w1 = param[0];
  if (Caml_obj.caml_greaterthan(w1, w2)) {
    return 1;
  }
  if (Caml_obj.caml_lessthan(w1, w2)) {
    return -1;
  }
  var l2 = param$1[1];
  var l1 = param[1];
  if (Caml_obj.caml_lessthan(l1, l2)) {
    return 1;
  } else if (Caml_obj.caml_greaterthan(l1, l2)) {
    return -1;
  } else {
    return 0;
  }
}

function min(x, y) {
  if (compare(x, y) > 0) {
    return y;
  } else {
    return x;
  }
}

function max(x, y) {
  if (compare(x, y) > 0) {
    return x;
  } else {
    return y;
  }
}

function compute_raw(nchoices, ballots) {
  var result = Stdlib__Array.make_matrix(nchoices, nchoices, 0);
  Stdlib__List.iter((function (ballot) {
          if (nchoices !== ballot.length) {
            throw {
                  RE_EXN_ID: "Assert_failure",
                  _1: [
                    "schulze.ml",
                    62,
                    6
                  ],
                  Error: new Error()
                };
          }
          var get = function (i) {
            var x = Caml_array.get(ballot, i);
            if (x === 0) {
              return Stdlib.max_int;
            } else {
              return x;
            }
          };
          for(var i = 0 ,i_finish = nchoices - 2 | 0; i <= i_finish; ++i){
            var x = get(i);
            for(var j = i + 1 | 0; j < nchoices; ++j){
              var y = get(j);
              if (x < y) {
                Caml_array.set(Caml_array.get(result, i), j, Caml_array.get(Caml_array.get(result, i), j) + 1 | 0);
              } else if (y < x) {
                Caml_array.set(Caml_array.get(result, j), i, Caml_array.get(Caml_array.get(result, j), i) + 1 | 0);
              }
              
            }
          }
        }), ballots);
  return result;
}

function compute_initial_matrix(m) {
  var n = m.length;
  var r = Stdlib__Array.make_matrix(n, n, [
        0,
        0
      ]);
  for(var i = 0; i < n; ++i){
    for(var j = 0; j < n; ++j){
      var x = Caml_array.get(Caml_array.get(m, i), j);
      var y = Caml_array.get(Caml_array.get(m, j), i);
      if (x > y) {
        Caml_array.set(Caml_array.get(r, i), j, [
              x,
              y
            ]);
      } else if (x < y) {
        Caml_array.set(Caml_array.get(r, j), i, [
              y,
              x
            ]);
      }
      
    }
  }
  return r;
}

function compute_transitive_closure(m) {
  var n = m.length;
  for(var k = 0; k < n; ++k){
    for(var i = 0; i < n; ++i){
      for(var j = 0; j < n; ++j){
        Caml_array.set(Caml_array.get(m, i), j, max(Caml_array.get(Caml_array.get(m, i), j), min(Caml_array.get(Caml_array.get(m, i), k), Caml_array.get(Caml_array.get(m, k), j))));
      }
    }
  }
}

function compute_winners(m, ignore) {
  var n = m.length;
  var winners = /* [] */0;
  for(var i = 0; i < n; ++i){
    if (!Caml_array.get(ignore, i)) {
      var won = true;
      try {
        for(var j = 0; j < n; ++j){
          if (!Caml_array.get(ignore, j) && compare(Caml_array.get(Caml_array.get(m, j), i), Caml_array.get(Caml_array.get(m, i), j)) > 0) {
            won = false;
            throw {
                  RE_EXN_ID: Stdlib.Exit,
                  Error: new Error()
                };
          }
          
        }
      }
      catch (raw_exn){
        var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
        if (exn.RE_EXN_ID !== Stdlib.Exit) {
          throw exn;
        }
        
      }
      if (won) {
        winners = {
          hd: i,
          tl: winners
        };
      }
      
    }
    
  }
  return Stdlib__List.rev(winners);
}

function rank_candidates(raw) {
  var n = raw.length;
  var beatpaths = compute_initial_matrix(raw);
  var ignore = Caml_array.make(n, false);
  compute_transitive_closure(beatpaths);
  var num_ranked = {
    contents: 0
  };
  var result = /* [] */0;
  while(num_ranked.contents < n) {
    var winners = compute_winners(beatpaths, ignore);
    result = {
      hd: winners,
      tl: result
    };
    Stdlib__List.iter((function (j) {
            Caml_array.set(ignore, j, true);
            num_ranked.contents = num_ranked.contents + 1 | 0;
          }), winners);
  };
  return [
          Stdlib__List.rev(result),
          beatpaths
        ];
}

function compute(nchoices, blank_allowed, ballots) {
  var n = ballots.length;
  var ballots$1 = Stdlib__Array.to_list(ballots);
  var null_ballot = Caml_array.make(nchoices, 0);
  var match;
  if (blank_allowed) {
    var loop = function (_valid, _blank, _ballots, _param) {
      while(true) {
        var param = _param;
        var ballots = _ballots;
        var blank = _blank;
        var valid = _valid;
        if (!param) {
          return [
                  valid,
                  blank,
                  ballots
                ];
        }
        var xs = param.tl;
        var ballot = param.hd;
        if (Caml_obj.caml_equal(ballot, null_ballot)) {
          _param = xs;
          _blank = blank + 1 | 0;
          continue ;
        }
        _param = xs;
        _ballots = {
          hd: ballot,
          tl: ballots
        };
        _valid = valid + 1 | 0;
        continue ;
      };
    };
    match = loop(0, 0, /* [] */0, ballots$1);
  } else {
    match = [
      n,
      undefined,
      ballots$1
    ];
  }
  var schulze_raw = compute_raw(nchoices, match[2]);
  var match$1 = rank_candidates(schulze_raw);
  return {
          schulze_valid: match[0],
          schulze_blank: match[1],
          schulze_raw: schulze_raw,
          schulze_beatpaths: match$1[1],
          schulze_winners: match$1[0]
        };
}

export {
  compute ,
}
/* No side effect */
