// Generated by Melange

import * as Atdgen_runtime from "../../../../bs-atdgen-codec-runtime/src/atdgen_runtime.js";
import * as Atdgen_codec_decode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_decode.js";
import * as Atdgen_codec_encode from "../../../../bs-atdgen-codec-runtime/src/atdgen_codec_encode.js";
import * as Belenios_core__Common_types from "./common_types.js";

function write__x_77e06da(param) {
  return Atdgen_codec_encode.contramap(Belenios_core__Common_types.Weight.unwrap, Atdgen_runtime.jsont_of_json, param);
}

function read__x_77e06da(param) {
  return Atdgen_codec_decode.map(Belenios_core__Common_types.Weight.wrap, Atdgen_runtime.json_of_jsont, param);
}

function string_of_weight(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_77e06da, x));
}

function weight_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_77e06da, JSON.parse(s));
}

Atdgen_codec_decode.option_as_constr(read__x_77e06da);

Atdgen_codec_decode.option_as_constr(Atdgen_codec_decode.string);

var write_voter = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, Atdgen_codec_encode.string, "address", t.address),
                  tl: {
                    hd: Atdgen_codec_encode.field_o(undefined, Atdgen_codec_encode.string, "login", t.login),
                    tl: {
                      hd: Atdgen_codec_encode.field_o(undefined, write__x_77e06da, "weight", t.weight),
                      tl: /* [] */0
                    }
                  }
                });
    });

function string_of_voter(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_voter, x));
}

var read_voter = Atdgen_codec_decode.make(function (json) {
      return {
              address: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("address", Atdgen_codec_decode.string, param);
                    }), json),
              login: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.fieldOptional("login", Atdgen_codec_decode.string, param);
                    }), json),
              weight: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.fieldOptional("weight", read__x_77e06da, param);
                    }), json)
            };
    });

function voter_of_string(s) {
  return Atdgen_codec_decode.decode(read_voter, JSON.parse(s));
}

function write__voter_list(param) {
  return Atdgen_codec_encode.list(write_voter, param);
}

function read__voter_list(param) {
  return Atdgen_codec_decode.list(read_voter, param);
}

function string_of_voter_list(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__voter_list, x));
}

function voter_list_of_string(s) {
  return Atdgen_codec_decode.decode(read__voter_list, JSON.parse(s));
}

function write__x_b068143(param) {
  return Atdgen_codec_encode.contramap(Belenios_core__Common_types.$$Number.unwrap, Atdgen_codec_encode.string, param);
}

function read__x_b068143(param) {
  return Atdgen_codec_decode.map(Belenios_core__Common_types.$$Number.wrap, Atdgen_codec_decode.string, param);
}

function string_of_number(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_b068143, x));
}

function number_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_b068143, JSON.parse(s));
}

var write_proof = Atdgen_codec_encode.make(function (t) {
      return Atdgen_codec_encode.obj({
                  hd: Atdgen_codec_encode.field(undefined, write__x_b068143, "challenge", t.challenge),
                  tl: {
                    hd: Atdgen_codec_encode.field(undefined, write__x_b068143, "response", t.response),
                    tl: /* [] */0
                  }
                });
    });

function string_of_proof(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_proof, x));
}

var read_proof = Atdgen_codec_decode.make(function (json) {
      return {
              challenge: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("challenge", read__x_b068143, param);
                    }), json),
              response: Atdgen_codec_decode.decode((function (param) {
                      return Atdgen_codec_decode.field("response", read__x_b068143, param);
                    }), json)
            };
    });

function proof_of_string(s) {
  return Atdgen_codec_decode.decode(read_proof, JSON.parse(s));
}

function write__x_dfc239d(param) {
  return Atdgen_codec_encode.array(write_proof, param);
}

function read__x_dfc239d(param) {
  return Atdgen_codec_decode.array(read_proof, param);
}

function string_of_disjunctive_proof(x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write__x_dfc239d, x));
}

function disjunctive_proof_of_string(s) {
  return Atdgen_codec_decode.decode(read__x_dfc239d, JSON.parse(s));
}

function write_ciphertext(write__a) {
  return Atdgen_codec_encode.make(function (t) {
              return Atdgen_codec_encode.obj({
                          hd: Atdgen_codec_encode.field(undefined, write__a, "alpha", t.alpha),
                          tl: {
                            hd: Atdgen_codec_encode.field(undefined, write__a, "beta", t.beta),
                            tl: /* [] */0
                          }
                        });
            });
}

function string_of_ciphertext(write__a, x) {
  return JSON.stringify(Atdgen_codec_encode.encode(write_ciphertext(write__a), x));
}

function read_ciphertext(read__a) {
  return Atdgen_codec_decode.make(function (json) {
              return {
                      alpha: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("alpha", read__a, param);
                            }), json),
                      beta: Atdgen_codec_decode.decode((function (param) {
                              return Atdgen_codec_decode.field("beta", read__a, param);
                            }), json)
                    };
            });
}

function ciphertext_of_string(read__a, s) {
  return Atdgen_codec_decode.decode(read_ciphertext(read__a), JSON.parse(s));
}

var read_weight = read__x_77e06da;

var write_weight = write__x_77e06da;

var read_voter_list = read__voter_list;

var write_voter_list = write__voter_list;

var read_number = read__x_b068143;

var write_number = write__x_b068143;

var read_disjunctive_proof = read__x_dfc239d;

var write_disjunctive_proof = write__x_dfc239d;

export {
  read_weight ,
  weight_of_string ,
  write_weight ,
  string_of_weight ,
  read_voter ,
  voter_of_string ,
  write_voter ,
  string_of_voter ,
  read_voter_list ,
  voter_list_of_string ,
  write_voter_list ,
  string_of_voter_list ,
  read_number ,
  number_of_string ,
  write_number ,
  string_of_number ,
  read_proof ,
  proof_of_string ,
  write_proof ,
  string_of_proof ,
  read_disjunctive_proof ,
  disjunctive_proof_of_string ,
  write_disjunctive_proof ,
  string_of_disjunctive_proof ,
  read_ciphertext ,
  ciphertext_of_string ,
  write_ciphertext ,
  string_of_ciphertext ,
}
/*  Not a pure module */
