// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Belenios_core__Common from "./common.js";
import * as Belenios_core__Common_types from "./common_types.js";

function $$process(ballot) {
  var nchoices = ballot.length;
  var used = Caml_array.make(nchoices, false);
  var lookup = function (rank, _i) {
    while(true) {
      var i = _i;
      if (i >= nchoices) {
        return ;
      }
      if (Caml_array.get(ballot, i) === rank) {
        if (Caml_array.get(used, i)) {
          throw {
                RE_EXN_ID: "Assert_failure",
                _1: [
                  "stv.ml",
                  34,
                  8
                ],
                Error: new Error()
              };
        }
        Caml_array.set(used, i, true);
        return i;
      }
      _i = i + 1 | 0;
      continue ;
    };
  };
  var build_preference_list = function (_rank, _accu) {
    while(true) {
      var accu = _accu;
      var rank = _rank;
      var i = lookup(rank, 0);
      if (i === undefined) {
        return Curry._1(Belenios_core__Common.List.rev, accu);
      }
      _accu = {
        hd: i,
        tl: accu
      };
      _rank = rank + 1 | 0;
      continue ;
    };
  };
  var preference_list = build_preference_list(1, /* [] */0);
  var check = function (_i) {
    while(true) {
      var i = _i;
      if (i >= nchoices) {
        return true;
      }
      if (!(Caml_array.get(used, i) || Caml_array.get(ballot, i) === 0)) {
        return false;
      }
      _i = i + 1 | 0;
      continue ;
    };
  };
  if (check(0)) {
    return preference_list;
  }
  
}

function assign(choices, b) {
  var ballot = b[1];
  var prepend = function (ballots, choices, x) {
    var bs = Curry._2(Belenios_core__Common.IMap.find_opt, x, choices);
    if (bs !== undefined) {
      return Curry._3(Belenios_core__Common.IMap.add, x, Curry._2(Belenios_core__Common.List.rev_append, ballots, bs), choices);
    } else {
      return Curry._3(Belenios_core__Common.IMap.add, x, ballots, choices);
    }
  };
  if (ballot) {
    return Curry._3(Belenios_core__Common.List.fold_left, (function (param, param$1) {
                  return prepend(/* [] */0, param, param$1);
                }), prepend({
                    hd: b,
                    tl: /* [] */0
                  }, choices, ballot.hd), ballot.tl);
  } else {
    return choices;
  }
}

function transfer(coef, i, scores) {
  return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                var ai = param[0];
                return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                              var w = param[0];
                              var w$1 = Caml_obj.caml_equal(ai, i) ? w * coef : w;
                              var b = Curry._2(Belenios_core__Common.List.filter, (function (x) {
                                      return Caml_obj.caml_notequal(x, i);
                                    }), param[1]);
                              return {
                                      hd: [
                                        w$1,
                                        b
                                      ],
                                      tl: accu
                                    };
                            }), accu, param[1][0]);
              }), /* [] */0, scores);
}

function run(quota, _ballots, _events, _nseats) {
  while(true) {
    var nseats = _nseats;
    var events = _events;
    var ballots = _ballots;
    if (nseats <= 0) {
      return Curry._1(Belenios_core__Common.List.rev, events);
    }
    var choices = Curry._3(Belenios_core__Common.List.fold_left, assign, Belenios_core__Common.IMap.empty, ballots);
    if (Curry._1(Belenios_core__Common.IMap.cardinal, choices) <= nseats) {
      var x = Curry._2(Belenios_core__Common.List.map, (function (prim) {
              return prim[0];
            }), Curry._1(Belenios_core__Common.IMap.bindings, choices));
      return Curry._1(Belenios_core__Common.List.rev, {
                  hd: {
                    NAME: "Win",
                    VAL: x
                  },
                  tl: events
                });
    }
    var scores = Curry._2(Belenios_core__Common.List.sort, (function (param, param$1) {
            return Caml_obj.caml_compare([
                        param$1[1][1],
                        param[0]
                      ], [
                        param[1][1],
                        param$1[0]
                      ]);
          }), Curry._1(Belenios_core__Common.IMap.bindings, Curry._2(Belenios_core__Common.IMap.map, (function (bs) {
                    return [
                            bs,
                            Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                                    return accu + param[0];
                                  }), 0, bs)
                          ];
                  }), choices)));
    if (scores) {
      var match = scores.hd;
      var aw = match[1][1];
      if (aw >= quota) {
        var xs = scores.tl;
        var ai = match[0];
        var events$1;
        if (xs) {
          var match$1 = xs.hd;
          events$1 = aw === match$1[1][1] ? ({
                hd: {
                  NAME: "TieWin",
                  VAL: {
                    hd: ai,
                    tl: {
                      hd: match$1[0],
                      tl: /* [] */0
                    }
                  }
                },
                tl: events
              }) : events;
        } else {
          events$1 = events;
        }
        var c = (aw - quota) / aw;
        _nseats = nseats - 1 | 0;
        _events = {
          hd: {
            NAME: "Win",
            VAL: {
              hd: ai,
              tl: /* [] */0
            }
          },
          tl: events$1
        };
        _ballots = transfer(c, ai, scores);
        continue ;
      }
      
    }
    var match$2 = Curry._1(Belenios_core__Common.List.rev, scores);
    if (match$2) {
      var xs$1 = match$2.tl;
      var match$3 = match$2.hd;
      var ai$1 = match$3[0];
      var events$2;
      if (xs$1) {
        var match$4 = xs$1.hd;
        events$2 = match$3[1][1] === match$4[1][1] ? ({
              hd: {
                NAME: "TieLose",
                VAL: {
                  hd: ai$1,
                  tl: {
                    hd: match$4[0],
                    tl: /* [] */0
                  }
                }
              },
              tl: events
            }) : events;
      } else {
        events$2 = events;
      }
      _events = {
        hd: {
          NAME: "Lose",
          VAL: ai$1
        },
        tl: events$2
      };
      _ballots = transfer(1, ai$1, scores);
      continue ;
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "stv.ml",
            148,
            12
          ],
          Error: new Error()
        };
  };
}

function compute(nseats, ballots) {
  var nballots = ballots.length;
  var partition = function (_accu, _invalid, _i) {
    while(true) {
      var i = _i;
      var invalid = _invalid;
      var accu = _accu;
      if (i >= nballots) {
        return [
                Curry._2(Belenios_core__Common.List.sort, Caml_obj.caml_compare, accu),
                Curry._1(Belenios_core__Common_types.$$Array.of_list, Curry._2(Belenios_core__Common.List.sort, Caml_obj.caml_compare, invalid))
              ];
      }
      var ballot = Caml_array.get(ballots, i);
      var x = $$process(ballot);
      if (x !== undefined) {
        _i = i + 1 | 0;
        _accu = {
          hd: x,
          tl: accu
        };
        continue ;
      }
      _i = i + 1 | 0;
      _invalid = {
        hd: ballot,
        tl: invalid
      };
      continue ;
    };
  };
  var match = partition(/* [] */0, /* [] */0, 0);
  var stv_ballots = match[0];
  var n = Curry._1(Belenios_core__Common.List.length, stv_ballots);
  var quota = Math.floor(n / (nseats + 1 | 0)) + 1;
  var wballots = Curry._2(Belenios_core__Common.List.map, (function (b) {
          return [
                  1,
                  b
                ];
        }), stv_ballots);
  var stv_events = run(quota, wballots, /* [] */0, nseats);
  var stv_winners = Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
              if (typeof param === "string" || param.NAME !== "Win") {
                return /* [] */0;
              } else {
                return param.VAL;
              }
            }), stv_events));
  var tmp;
  if (n > 0) {
    var nwinners = Curry._1(Belenios_core__Common.List.length, stv_winners);
    var nchoices = Caml_array.get(ballots, 0).length;
    tmp = nchoices > nseats ? nwinners === nseats : nwinners === nchoices;
  } else {
    tmp = Caml_obj.caml_equal(stv_winners, /* [] */0);
  }
  if (!tmp) {
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "stv.ml",
            179,
            2
          ],
          Error: new Error()
        };
  }
  return {
          stv_ballots: stv_ballots,
          stv_invalid: match[1],
          stv_events: stv_events,
          stv_winners: stv_winners
        };
}

export {
  compute ,
}
/* Belenios_core__Common Not a pure module */
