// Generated by Melange

import * as CamlinternalLazy from "melange/./camlinternalLazy.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";

var prng = {
  LAZY_DONE: false,
  VAL: (function () {
      return Belenios_platform__Platform.pseudo_rng(Belenios_platform__Platform.random_string(undefined, 16));
    })
};

function random(q) {
  var size = Belenios_core__Common.bytes_to_sample(q);
  var r = Belenios_platform__Platform.random_string(CamlinternalLazy.force(prng), size);
  return Belenios_platform__Platform.Z.mod(Belenios_platform__Platform.Z.of_bits(r), q);
}

export {
  random ,
}
/* Belenios_core__Common Not a pure module */
