// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Belenios__Group from "../../lib/shell/group.js";
import * as Belenios__Election from "../../lib/shell/election.js";
import * as Belenios__Trustees from "../../lib/shell/trustees.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_core__Common_types from "../../lib/core/common_types.js";
import * as Belenios_core__Serializable_j from "../../lib/core/serializable_j.js";

function parse_params(p) {
  var T = Belenios__Trustees.get_by_version(p.version);
  var version = p.version;
  var uuid = Belenios_core__Common_types.Uuid.wrap(p.uuid);
  var template = Belenios_core__Serializable_j.template_of_string(p.template);
  var G = Curry._1(Belenios__Group.of_string(version), p.group);
  var get_trustees = function (param) {
    return Belenios_core__Serializable_j.trustees_of_string((function (param) {
                  return Belenios_core__Common.sread(G.of_string, param);
                }), Curry._1(p.get_trustees, undefined));
  };
  return {
          version: version,
          uuid: uuid,
          template: template,
          group: p.group,
          G: G,
          get_trustees: get_trustees,
          Trustees: T
        };
}

function make(params) {
  var P = parse_params(params);
  var K = Curry._1(P.Trustees.MakeCombinator, P.G);
  var trustees = Curry._1(P.get_trustees, undefined);
  var y = Curry._1(K.combine_keys, trustees);
  var public_key = Curry._1(P.G.to_string, y);
  var params_e_version = P.version;
  var params_e_description = P.template.t_description;
  var params_e_name = P.template.t_name;
  var params_e_questions = P.template.t_questions;
  var params_e_uuid = P.uuid;
  var params_e_administrator = P.template.t_administrator;
  var params_e_credential_authority = P.template.t_credential_authority;
  var params$1 = {
    e_version: params_e_version,
    e_description: params_e_description,
    e_name: params_e_name,
    e_questions: params_e_questions,
    e_uuid: params_e_uuid,
    e_administrator: params_e_administrator,
    e_credential_authority: params_e_credential_authority
  };
  var mkelection = function (param) {
    return Belenios__Election.make_raw_election(params$1, P.group, public_key);
  };
  return {
          mkelection: mkelection
        };
}

export {
  make ,
}
/* Belenios__Group Not a pure module */
