// Generated by Melange

import * as Caml from "melange.runtime/caml.js";
import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_bytes from "melange.runtime/caml_bytes.js";
import * as Caml_int64 from "melange.runtime/caml_int64.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Fun from "melange/./fun.js";
import * as Stdlib__Sys from "melange/./sys.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Stdlib__Hashtbl from "melange/./hashtbl.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_core__Events from "../../lib/core/events.js";
import * as Belenios_core__Archive from "../../lib/core/archive.js";
import * as Caml_external_polyfill from "melange.runtime/caml_external_polyfill.js";
import * as Belenios_core__Common_types from "../../lib/core/common_types.js";
import * as Belenios_core__Serializable_j from "../../lib/core/serializable_j.js";

function $$return(x) {
  return x;
}

function bind(x, f) {
  return Curry._1(f, x);
}

function fail(x) {
  throw x;
}

function $$yield(param) {
  
}

var get_pos = Stdlib.LargeFile.pos_in;

var set_pos = Stdlib.LargeFile.seek_in;

function read_block(ic, buffer) {
  Stdlib.really_input(ic, buffer, 0, Belenios_core__Archive.block_size);
}

var Reader = Belenios_core__Archive.MakeReader({
      $$yield: $$yield,
      $$return: $$return,
      bind: bind,
      fail: fail,
      get_pos: get_pos,
      set_pos: set_pos,
      read_block: read_block
    });

var get_pos$1 = Stdlib.LargeFile.pos_out;

var write_block = Stdlib.output_bytes;

var Writer = Belenios_core__Archive.MakeWriter({
      $$yield: $$yield,
      $$return: $$return,
      bind: bind,
      fail: fail,
      get_pos: get_pos$1,
      write_block: write_block
    });

function build_index(filename) {
  var r = Stdlib__Hashtbl.create(undefined, 1000);
  var ic = Stdlib.open_in(filename);
  var header = Curry._1(Reader.read_header, ic);
  return Stdlib__Fun.protect((function (param) {
                Stdlib.close_in(ic);
              }), (function (param) {
                var _last;
                var _accu = Belenios_core__Events.empty_roots;
                var _lines = /* [] */0;
                while(true) {
                  var lines = _lines;
                  var accu = _accu;
                  var last = _last;
                  var record;
                  try {
                    record = Curry._1(Reader.read_record, ic);
                  }
                  catch (raw_exn){
                    var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
                    if (exn.RE_EXN_ID === Stdlib.End_of_file) {
                      return [
                              r,
                              last,
                              accu,
                              lines,
                              header.timestamp
                            ];
                    }
                    throw exn;
                  }
                  var $$event = record.typ;
                  var match;
                  if ($$event) {
                    var $$event$1 = $$event._0;
                    match = [
                      $$event$1,
                      Belenios_core__Events.update_roots(record.hash, $$event$1, accu)
                    ];
                  } else {
                    match = [
                      last,
                      accu
                    ];
                  }
                  Stdlib__Hashtbl.add(r, record.hash, record.location);
                  _lines = {
                    hd: [
                      record.typ,
                      record.hash
                    ],
                    tl: lines
                  };
                  _accu = match[1];
                  _last = match[0];
                  continue ;
                };
              }));
}

function get_index(file) {
  var match = build_index(file);
  return {
          map: match[0],
          roots: match[2],
          last_event: match[1],
          file: file,
          lines: match[3],
          timestamp: match[4]
        };
}

function gethash(index, filename, x) {
  var i = Stdlib__Hashtbl.find_opt(index, x);
  if (i === undefined) {
    return ;
  }
  var ic = Stdlib.open_in(filename);
  return Stdlib__Fun.protect((function (param) {
                Stdlib.close_in(ic);
              }), (function (param) {
                Stdlib.LargeFile.seek_in(ic, i.location_offset);
                if (!Caml.i64_le(i.location_length, Caml_int64.of_int32(Stdlib__Sys.max_string_length))) {
                  throw {
                        RE_EXN_ID: "Assert_failure",
                        _1: [
                          "tool_events.ml",
                          104,
                          9
                        ],
                        Error: new Error()
                      };
                }
                return Stdlib.really_input_string(ic, Caml_int64.to_int32(i.location_length));
              }));
}

function get_data(i, x) {
  return gethash(i.map, i.file, x);
}

function get_event(i, x) {
  return Curry._2(Belenios_core__Common.$$Option.map, Belenios_core__Serializable_j.event_of_string, gethash(i.map, i.file, x));
}

function get_roots(i) {
  return i.roots;
}

function fold_on_event_payload_hashes(index, typ, last_event, f, accu) {
  var _e = last_event;
  var _accu = accu;
  while(true) {
    var accu$1 = _accu;
    var e = _e;
    var e$1 = get_event(index, e);
    if (e$1 !== undefined) {
      if (e$1.event_typ !== typ) {
        return accu$1;
      }
      var match = e$1.event_payload;
      var match$1 = e$1.event_parent;
      if (match !== undefined) {
        if (match$1 !== undefined) {
          _accu = Curry._2(f, Caml_option.valFromOption(match), accu$1);
          _e = Caml_option.valFromOption(match$1);
          continue ;
        }
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_events.ml",
                125,
                16
              ],
              Error: new Error()
            };
      }
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_events.ml",
              125,
              16
            ],
            Error: new Error()
          };
    }
    throw {
          RE_EXN_ID: "Assert_failure",
          _1: [
            "tool_events.ml",
            120,
            14
          ],
          Error: new Error()
        };
  };
}

function fold_on_event_payloads(index, typ, last_event, f, accu) {
  return fold_on_event_payload_hashes(index, typ, last_event, (function (payload, accu) {
                var x = get_data(index, payload);
                if (x !== undefined) {
                  return Curry._2(f, x, accu);
                }
                throw {
                      RE_EXN_ID: "Assert_failure",
                      _1: [
                        "tool_events.ml",
                        134,
                        16
                      ],
                      Error: new Error()
                    };
              }), accu);
}

function fsck(index) {
  var x = index.last_event;
  var last_event = x !== undefined ? x : Stdlib.failwith("no events");
  var header_timestamp = index.timestamp;
  var header = {
    version: 1,
    timestamp: header_timestamp
  };
  var get_pos = Stdlib.LargeFile.pos_in;
  var buffer = Caml_bytes.caml_create_bytes(Belenios_core__Archive.block_size);
  var write_block = function (ic, expected) {
    try {
      Stdlib.really_input(ic, buffer, 0, Belenios_core__Archive.block_size);
      if (Caml_external_polyfill.resolve("caml_bytes_notequal")(expected, buffer)) {
        return Stdlib.failwith("generated archive is not identical to original one");
      } else {
        return ;
      }
    }
    catch (raw_exn){
      var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
      if (exn.RE_EXN_ID === Stdlib.End_of_file) {
        return Stdlib.failwith("generate archive is longer than original one");
      }
      throw exn;
    }
  };
  var Comparer = Belenios_core__Archive.MakeWriter({
        $$yield: $$yield,
        $$return: $$return,
        bind: bind,
        fail: fail,
        get_pos: get_pos,
        write_block: write_block
      });
  var get_hash = function (hash) {
    return gethash(index.map, index.file, hash);
  };
  var Archiver = Belenios_core__Archive.MakeArchiver({
        $$yield: $$yield,
        $$return: $$return,
        bind: bind,
        fail: fail,
        get_hash: get_hash
      }, Comparer);
  var ic = Stdlib.open_in_bin(index.file);
  var length = Stdlib.LargeFile.in_channel_length(ic);
  Stdlib__Fun.protect((function (param) {
          Stdlib.close_in(ic);
        }), (function (param) {
          Curry._3(Archiver.write_archive, ic, header, last_event);
          if (Caml.i64_neq(Stdlib.LargeFile.pos_in(ic), length)) {
            return Stdlib.failwith("generated archive is shorter than original one");
          }
          
        }));
}

function starts_with(prefix, index) {
  var _x = Curry._1(Belenios_core__Common.List.rev, prefix.lines);
  var _y = Curry._1(Belenios_core__Common.List.rev, index.lines);
  while(true) {
    var y = _y;
    var x = _x;
    if (!x) {
      return true;
    }
    if (!y) {
      return false;
    }
    if (!Caml_obj.caml_equal(x.hd, y.hd)) {
      return false;
    }
    _y = y.tl;
    _x = x.tl;
    continue ;
  };
}

function write_header(filename, timestamp) {
  var oc = Stdlib.open_out_gen({
        hd: /* Open_wronly */1,
        tl: {
          hd: /* Open_append */2,
          tl: {
            hd: /* Open_creat */3,
            tl: {
              hd: /* Open_binary */6,
              tl: /* [] */0
            }
          }
        }
      }, 420, filename);
  Stdlib__Fun.protect((function (param) {
          Stdlib.close_out(oc);
        }), (function (param) {
          Curry._2(Writer.write_header, oc, {
                version: 1,
                timestamp: timestamp
              });
        }));
}

function raw_append(filename, timestamp, xs) {
  var oc = Stdlib.open_out_gen({
        hd: /* Open_wronly */1,
        tl: {
          hd: /* Open_append */2,
          tl: {
            hd: /* Open_binary */6,
            tl: /* [] */0
          }
        }
      }, 420, filename);
  return Stdlib__Fun.protect((function (param) {
                Stdlib.close_out(oc);
              }), (function (param) {
                return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                              return {
                                      hd: Curry._4(Writer.write_record, oc, timestamp, param[0], param[1]),
                                      tl: accu
                                    };
                            }), /* [] */0, xs);
              }));
}

function append(index, ops) {
  var match = Curry._3(Belenios_core__Common.List.fold_left, (function (param, x) {
          var lines = param[3];
          var items = param[2];
          var roots = param[1];
          var last_event = param[0];
          if (x.TAG === /* Data */0) {
            var x$1 = x._0;
            var items_0 = [
              /* Data */0,
              x$1
            ];
            var items$1 = {
              hd: items_0,
              tl: items
            };
            var lines_0 = [
              /* Data */0,
              Belenios_core__Common_types.Hash.hash_string(x$1)
            ];
            var lines$1 = {
              hd: lines_0,
              tl: lines
            };
            return [
                    last_event,
                    roots,
                    items$1,
                    lines$1
                  ];
          }
          var match = last_event !== undefined ? [
              Caml_option.some(Belenios_core__Common_types.Hash.hash_string(Belenios_core__Serializable_j.string_of_event(last_event))),
              last_event.event_height + 1 | 0
            ] : [
              undefined,
              0
            ];
          var event_event_parent = match[0];
          var event_event_height = match[1];
          var event_event_typ = x._0;
          var event_event_payload = x._1;
          var $$event = {
            event_parent: event_event_parent,
            event_height: event_event_height,
            event_typ: event_event_typ,
            event_payload: event_event_payload
          };
          var typ = /* Event */{
            _0: $$event
          };
          var event_s = Belenios_core__Serializable_j.string_of_event($$event);
          var event_h = Belenios_core__Common_types.Hash.hash_string(event_s);
          var roots$1 = Belenios_core__Events.update_roots(event_h, $$event, roots);
          var items_0$1 = [
            typ,
            event_s
          ];
          var items$2 = {
            hd: items_0$1,
            tl: items
          };
          return [
                  $$event,
                  roots$1,
                  items$2,
                  {
                    hd: [
                      typ,
                      event_h
                    ],
                    tl: lines
                  }
                ];
        }), [
        index.last_event,
        index.roots,
        /* [] */0,
        index.lines
      ], ops);
  var items = Curry._1(Belenios_core__Common.List.rev, match[2]);
  var records = raw_append(index.file, index.timestamp, items);
  Curry._2(Belenios_core__Common.List.iter, (function (r) {
          Stdlib__Hashtbl.add(index.map, r.hash, r.location);
        }), records);
  index.roots = match[1];
  index.last_event = match[0];
  index.lines = match[3];
}

function init(file, election, trustees, public_creds) {
  if (Caml_external_polyfill.resolve("caml_sys_file_exists")(file)) {
    Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
              _0: {
                TAG: /* String */2,
                _0: /* No_padding */0,
                _1: {
                  TAG: /* String_literal */11,
                  _0: " already exists",
                  _1: /* End_of_format */0
                }
              },
              _1: "%s already exists"
            }), file);
  }
  var timestamp = Caml_int64.of_float(0.0);
  var index = {
    map: Stdlib__Hashtbl.create(undefined, 1000),
    roots: Belenios_core__Events.empty_roots,
    last_event: undefined,
    file: file,
    lines: /* [] */0,
    timestamp: timestamp
  };
  write_header(file, timestamp);
  var setup_election = Belenios_core__Common_types.Hash.hash_string(election);
  var setup_trustees = Belenios_core__Common_types.Hash.hash_string(trustees);
  var setup_credentials = Belenios_core__Common_types.Hash.hash_string(public_creds);
  var setup_data = {
    setup_election: setup_election,
    setup_trustees: setup_trustees,
    setup_credentials: setup_credentials
  };
  var setup_data_s = Belenios_core__Serializable_j.string_of_setup_data(setup_data);
  append(index, {
        hd: {
          TAG: /* Data */0,
          _0: election
        },
        tl: {
          hd: {
            TAG: /* Data */0,
            _0: trustees
          },
          tl: {
            hd: {
              TAG: /* Data */0,
              _0: public_creds
            },
            tl: {
              hd: {
                TAG: /* Data */0,
                _0: setup_data_s
              },
              tl: {
                hd: {
                  TAG: /* Event */1,
                  _0: "Setup",
                  _1: Caml_option.some(Belenios_core__Common_types.Hash.hash_string(setup_data_s))
                },
                tl: /* [] */0
              }
            }
          }
        }
      });
  return index;
}

var DirectMonad = {
  $$yield: $$yield,
  $$return: $$return,
  bind: bind,
  fail: fail
};

export {
  get_index ,
  get_data ,
  get_event ,
  get_roots ,
  fold_on_event_payload_hashes ,
  fold_on_event_payloads ,
  fsck ,
  starts_with ,
  append ,
  init ,
  DirectMonad ,
  Writer ,
}
/* Reader Not a pure module */
