// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Belenios__Group from "../../lib/shell/group.js";
import * as Belenios__Trustees from "../../lib/shell/trustees.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";
import * as Belenios_core__Serializable_j from "../../lib/core/serializable_j.js";

function Make(funarg, funarg$1, funarg$2) {
  var G = Curry._1(Belenios__Group.of_string(funarg.version), funarg.group);
  var Trustees = Belenios__Trustees.get_by_version(funarg.version);
  var KG = Curry._2(Trustees.MakeSimple, G, funarg$1);
  var K = Curry._1(Trustees.MakeCombinator, G);
  var trustee_keygen = function (param) {
    var private_key = Curry._1(KG.generate, undefined);
    var public_key = Curry._1(KG.prove, private_key);
    if (!Curry._1(K.check, {
            hd: {
              NAME: "Single",
              VAL: public_key
            },
            tl: /* [] */0
          })) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_tkeygen.ml",
              55,
              4
            ],
            Error: new Error()
          };
    }
    var id = Curry._1(Belenios_core__Common.$$String.uppercase_ascii, Curry._3(Belenios_core__Common.$$String.sub, Belenios_platform__Platform.sha256_hex(Curry._1(G.to_string, public_key.trustee_public_key)), 0, 8));
    var priv = Belenios_core__Serializable_j.string_of_number(private_key);
    var pub = Belenios_core__Serializable_j.string_of_trustee_public_key((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), public_key);
    return {
            id: id,
            priv: priv,
            pub: pub
          };
  };
  return {
          trustee_keygen: trustee_keygen
        };
}

export {
  Make ,
}
/* Belenios__Group Not a pure module */
