// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Caml_obj from "melange.runtime/caml_obj.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Caml_exceptions from "melange.runtime/caml_exceptions.js";
import * as CamlinternalLazy from "melange/./camlinternalLazy.js";
import * as Stdlib__Printexc from "melange/./printexc.js";
import * as Belenios__Election from "../../lib/shell/election.js";
import * as Belenios__Trustees from "../../lib/shell/trustees.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_core__Credential from "../../lib/core/credential.js";
import * as Belenios_core__Common_types from "../../lib/core/common_types.js";
import * as Belenios_tool_common__Random from "./random.js";
import * as Belenios_core__Serializable_j from "../../lib/core/serializable_j.js";
import * as Belenios_tool_common__Tool_events from "./tool_events.js";

var Cmdline_error = /* @__PURE__ */Caml_exceptions.create("Belenios_tool_common.Tool_election.Cmdline_error");

function failcmd(fmt) {
  return Stdlib__Printf.ksprintf((function (x) {
                throw {
                      RE_EXN_ID: Cmdline_error,
                      _1: x,
                      Error: new Error()
                    };
              }), fmt);
}

function Make(funarg, funarg$1) {
  var index = Belenios_tool_common__Tool_events.get_index(funarg.file);
  var roots = Belenios_tool_common__Tool_events.get_roots(index);
  var fsck = function (param) {
    Belenios_tool_common__Tool_events.fsck(index);
  };
  var x = roots.roots_setup_data;
  var setup_data;
  if (x !== undefined) {
    var x$1 = Belenios_tool_common__Tool_events.get_data(index, Caml_option.valFromOption(x));
    setup_data = x$1 !== undefined ? Belenios_core__Serializable_j.setup_data_of_string(x$1) : failcmd(/* Format */{
            _0: {
              TAG: /* String_literal */11,
              _0: "could not get setup data",
              _1: /* End_of_format */0
            },
            _1: "could not get setup data"
          });
  } else {
    setup_data = failcmd(/* Format */{
          _0: {
            TAG: /* String_literal */11,
            _0: "setup data are missing",
            _1: /* End_of_format */0
          },
          _1: "setup data are missing"
        });
  }
  var x$2 = Belenios_tool_common__Tool_events.get_data(index, setup_data.setup_election);
  var raw_election = x$2 !== undefined ? x$2 : failcmd(/* Format */{
          _0: {
            TAG: /* String_literal */11,
            _0: "could not get election",
            _1: /* End_of_format */0
          },
          _1: "could not get election"
        });
  var get_public_creds = function (param) {
    return Curry._2(Belenios_core__Common.$$Option.map, Belenios_core__Serializable_j.public_credentials_of_string, Belenios_tool_common__Tool_events.get_data(index, setup_data.setup_credentials));
  };
  var get_trustees = function (param) {
    return Belenios_tool_common__Tool_events.get_data(index, setup_data.setup_trustees);
  };
  var get_ballots = function (param) {
    var x = roots.roots_last_ballot_event;
    if (x !== undefined) {
      return Belenios_tool_common__Tool_events.fold_on_event_payloads(index, "Ballot", Caml_option.valFromOption(x), (function (x, accu) {
                    return {
                            hd: x,
                            tl: accu
                          };
                  }), /* [] */0);
    } else {
      return /* [] */0;
    }
  };
  var get_shuffles = function (param) {
    return Belenios_core__Common.let$amp(roots.roots_last_shuffle_event, (function (x) {
                  return Belenios_tool_common__Tool_events.fold_on_event_payload_hashes(index, "Shuffle", x, (function (x, accu) {
                                var y = Belenios_tool_common__Tool_events.get_data(index, x);
                                if (y === undefined) {
                                  return Stdlib.failwith("could not get shuffle");
                                }
                                var owned = Belenios_core__Serializable_j.owned_of_string(Belenios_core__Serializable_j.read_hash, y);
                                var z = Belenios_tool_common__Tool_events.get_data(index, owned.owned_payload);
                                if (z !== undefined) {
                                  return {
                                          hd: [
                                            x,
                                            owned,
                                            z
                                          ],
                                          tl: accu
                                        };
                                } else {
                                  return Stdlib.failwith("could not get shuffle payload");
                                }
                              }), /* [] */0);
                }));
  };
  var get_pds = function (param) {
    return Belenios_core__Common.let$amp(roots.roots_last_pd_event, (function (x) {
                  return Belenios_tool_common__Tool_events.fold_on_event_payload_hashes(index, "PartialDecryption", x, (function (x, accu) {
                                var y = Belenios_tool_common__Tool_events.get_data(index, x);
                                if (y === undefined) {
                                  return Stdlib.failwith("could not get partial decryption");
                                }
                                var owned = Belenios_core__Serializable_j.owned_of_string(Belenios_core__Serializable_j.read_hash, y);
                                var z = Belenios_tool_common__Tool_events.get_data(index, owned.owned_payload);
                                if (z !== undefined) {
                                  return {
                                          hd: [
                                            x,
                                            owned,
                                            z
                                          ],
                                          tl: accu
                                        };
                                } else {
                                  return Stdlib.failwith("could not get partial decryption payload");
                                }
                              }), /* [] */0);
                }));
  };
  var get_result = function (param) {
    return Belenios_core__Common.let$amp(roots.roots_result, (function (x) {
                  return Belenios_tool_common__Tool_events.get_data(index, x);
                }));
  };
  var print_msg = function (prim) {
    console.error(prim);
  };
  var fsck$1 = fsck;
  var setup_data$1 = setup_data;
  var raw_election$1 = raw_election;
  var get_trustees$1 = get_trustees;
  var get_public_creds$1 = get_public_creds;
  var get_ballots$1 = get_ballots;
  var get_shuffles$1 = get_shuffles;
  var get_pds$1 = get_pds;
  var get_result$1 = get_result;
  var print_msg$1 = print_msg;
  var include = Belenios__Election.Make({
        raw_election: raw_election$1
      }, Belenios_tool_common__Random, {});
  var G = include.G;
  var election = include.election;
  var public_key = include.public_key;
  var string_of_ballot = include.string_of_ballot;
  var ballot_of_string = include.ballot_of_string;
  var write_result = include.write_result;
  var read_result = include.read_result;
  var E = include.E;
  var Trustees = Belenios__Trustees.get_by_version(election.e_version);
  var P = Curry._2(Trustees.MakePKI, G, Belenios_tool_common__Random);
  var C = Curry._3(Trustees.MakeChannels, G, Belenios_tool_common__Random, P);
  var K = Curry._1(Trustees.MakeCombinator, G);
  var trustees_as_string = Curry._1(get_trustees$1, undefined);
  var trustees = Curry._2(Belenios_core__Common.$$Option.map, (function (param) {
          return Belenios_core__Serializable_j.trustees_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), param);
        }), trustees_as_string);
  var public_keys_with_pok = Curry._2(Belenios_core__Common.$$Option.map, (function (x) {
          return Curry._1(Belenios_core__Common_types.$$Array.of_list, Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
                                if (param.NAME === "Pedersen") {
                                  return Curry._1(Belenios_core__Common_types.$$Array.to_list, param.VAL.t_verification_keys);
                                } else {
                                  return {
                                          hd: param.VAL,
                                          tl: /* [] */0
                                        };
                                }
                              }), x)));
        }), trustees);
  if (trustees !== undefined) {
    if (!Curry._1(K.check, trustees)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              166,
              6
            ],
            Error: new Error()
          };
    }
    var y$p = Curry._1(K.combine_keys, trustees);
    if (!Curry._2(G.$eq$tilde, public_key, y$p)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              168,
              6
            ],
            Error: new Error()
          };
    }
    
  } else {
    Stdlib.failwith("missing trustees");
  }
  var public_keys = Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common_types.$$Array.map, (function (pk) {
              return pk.trustee_public_key;
            })), public_keys_with_pok);
  var pks = {
    LAZY_DONE: false,
    VAL: (function () {
        if (public_keys !== undefined) {
          return public_keys;
        } else {
          return Stdlib.failwith("missing public keys");
        }
      })
  };
  var PPC = Belenios_core__Credential.MakeParsePublicCredential(G);
  var raw_public_creds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_public_creds$1, undefined);
      })
  };
  var public_creds_weights = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._2(Belenios_core__Common.List.fold_left, (function (param, x) {
                          var accu = param[1];
                          var has_weights = param[0] || Curry._2(Belenios_core__Common.$$String.index_opt, x, /* ',' */44) !== undefined;
                          var match = Curry._1(PPC.parse_public_credential, x);
                          if (match === undefined) {
                            return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                            _0: {
                                              TAG: /* String */2,
                                              _0: /* No_padding */0,
                                              _1: {
                                                TAG: /* String_literal */11,
                                                _0: " is not a valid public credential",
                                                _1: /* End_of_format */0
                                              }
                                            },
                                            _1: "%s is not a valid public credential"
                                          }), x);
                          }
                          var y = Curry._1(G.to_string, match[1]);
                          if (Curry._2(Belenios_core__Common.SMap.mem, y, accu)) {
                            return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                            _0: {
                                              TAG: /* String_literal */11,
                                              _0: "duplicate credential: ",
                                              _1: {
                                                TAG: /* String */2,
                                                _0: /* No_padding */0,
                                                _1: /* End_of_format */0
                                              }
                                            },
                                            _1: "duplicate credential: %s"
                                          }), y);
                          } else {
                            return [
                                    has_weights,
                                    Curry._3(Belenios_core__Common.SMap.add, y, [
                                          match[0],
                                          {
                                            contents: undefined
                                          }
                                        ], accu)
                                  ];
                          }
                        }), [
                        false,
                        Belenios_core__Common.SMap.empty
                      ]), CamlinternalLazy.force(raw_public_creds));
      })
  };
  var public_creds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, (function (prim) {
                      return prim[1];
                    }), CamlinternalLazy.force(public_creds_weights));
      })
  };
  var rawballots = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_ballots$1, undefined);
      })
  };
  var string_of_cast_error = function (param) {
    if (typeof param === "string") {
      if (param === "NonCanonical") {
        return "ballot not in canonical form";
      } else if (param === "DuplicateBallot") {
        return "duplicate ballot";
      } else if (param === "WrongUsername") {
        return "wrong username";
      } else if (param === "UsedCredential") {
        return "used credential";
      } else if (param === "RevoteNotAllowed") {
        return "revote not allowed";
      } else if (param === "WrongWeight") {
        return "wrong weight";
      } else if (param === "InvalidBallot") {
        return "invalid ballot";
      } else if (param === "ExpiredBallot") {
        return "expired ballot";
      } else if (param === "InvalidCredential") {
        return "invalid credential";
      } else {
        return "wrong credential";
      }
    } else {
      return Curry._1(Stdlib__Printf.sprintf(/* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "ill-formed ballot: ",
                        _1: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: /* End_of_format */0
                        }
                      },
                      _1: "ill-formed ballot: %s"
                    }), Stdlib__Printexc.to_string(param.VAL));
    }
  };
  var cast = function (accu, rawballot) {
    var hash = Belenios_core__Common_types.Hash.hash_string(rawballot);
    var creds = CamlinternalLazy.force(public_creds);
    if (creds === undefined) {
      return Stdlib.failwith("missing public credentials");
    }
    var creds$1 = Caml_option.valFromOption(creds);
    var ballot_id = Belenios_core__Common.sha256_b64(rawballot);
    return Belenios_core__Common.let$at((function (cont) {
                  return Belenios_core__Common.let$at((function (cont2) {
                                if (Curry._2(Belenios_core__Common.SSet.mem, ballot_id, accu)) {
                                  return Curry._1(cont, {
                                              TAG: /* Error */1,
                                              _0: "DuplicateBallot"
                                            });
                                } else {
                                  return Curry._1(cont2, Curry._2(Belenios_core__Common.SSet.add, ballot_id, accu));
                                }
                              }), (function (accu) {
                                var x = Curry._1(E.check_rawballot, rawballot);
                                if (x.TAG !== /* Ok */0) {
                                  return Curry._1(cont, x);
                                }
                                var rc = x._0;
                                var x$1 = Curry._2(Belenios_core__Common.SMap.find_opt, rc.rc_credential, creds$1);
                                if (x$1 !== undefined) {
                                  if (Curry._1(rc.rc_check, undefined)) {
                                    return Curry._1(cont, {
                                                TAG: /* Ok */0,
                                                _0: [
                                                  rc.rc_credential,
                                                  x$1[1].contents,
                                                  accu
                                                ]
                                              });
                                  } else {
                                    return Curry._1(cont, {
                                                TAG: /* Error */1,
                                                _0: "InvalidBallot"
                                              });
                                  }
                                } else {
                                  return Curry._1(cont, {
                                              TAG: /* Error */1,
                                              _0: "InvalidCredential"
                                            });
                                }
                              }));
                }), (function (x) {
                  if (x.TAG !== /* Ok */0) {
                    return Curry._2(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                    _0: {
                                      TAG: /* String_literal */11,
                                      _0: "error while casting ballot ",
                                      _1: {
                                        TAG: /* String */2,
                                        _0: /* No_padding */0,
                                        _1: {
                                          TAG: /* String_literal */11,
                                          _0: ": ",
                                          _1: {
                                            TAG: /* String */2,
                                            _0: /* No_padding */0,
                                            _1: /* End_of_format */0
                                          }
                                        }
                                      }
                                    },
                                    _1: "error while casting ballot %s: %s"
                                  }), ballot_id, string_of_cast_error(x._0));
                  }
                  var match = x._0;
                  var credential = match[0];
                  var match$1 = Curry._2(Belenios_core__Common.SMap.find_opt, credential, creds$1);
                  if (match$1 === undefined) {
                    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                    _0: {
                                      TAG: /* String_literal */11,
                                      _0: "invalid credential for ballot ",
                                      _1: {
                                        TAG: /* String */2,
                                        _0: /* No_padding */0,
                                        _1: /* End_of_format */0
                                      }
                                    },
                                    _1: "invalid credential for ballot %s"
                                  }), ballot_id);
                  }
                  var used = match$1[1];
                  if (!Caml_obj.caml_equal(used.contents, match[1])) {
                    throw {
                          RE_EXN_ID: "Assert_failure",
                          _1: [
                            "tool_election.ml",
                            255,
                            13
                          ],
                          Error: new Error()
                        };
                  }
                  used.contents = ballot_id;
                  return [
                          [
                            hash,
                            [
                              credential,
                              match$1[0],
                              rawballot
                            ]
                          ],
                          match[2]
                        ];
                }));
  };
  var rev_ballots = {
    LAZY_DONE: false,
    VAL: (function () {
        var bs = CamlinternalLazy.force(rawballots);
        if (bs !== undefined) {
          var _accu = /* [] */0;
          var _seen = Belenios_core__Common.SSet.empty;
          var _param = bs;
          while(true) {
            var param = _param;
            var seen = _seen;
            var accu = _accu;
            if (!param) {
              return accu;
            }
            var match = cast(seen, param.hd);
            _param = param.tl;
            _seen = match[1];
            _accu = {
              hd: match[0],
              tl: accu
            };
            continue ;
          };
        } else {
          return /* [] */0;
        }
      })
  };
  var final_ballots = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, b) {
                        var credential = b[1][0];
                        var seen = accu[0];
                        if (Curry._2(Belenios_core__Common.SSet.mem, credential, seen)) {
                          return accu;
                        } else {
                          return [
                                  Curry._2(Belenios_core__Common.SSet.add, credential, seen),
                                  {
                                    hd: b,
                                    tl: accu[1]
                                  }
                                ];
                        }
                      }), [
                      Belenios_core__Common.SSet.empty,
                      /* [] */0
                    ], CamlinternalLazy.force(rev_ballots))[1];
      })
  };
  var raw_encrypted_tally = {
    LAZY_DONE: false,
    VAL: (function () {
        var ballots = Curry._2(Belenios_core__Common.List.rev_map, (function (param) {
                var match = param[1];
                return [
                        match[1],
                        Curry._1(ballot_of_string, match[2])
                      ];
              }), CamlinternalLazy.force(final_ballots));
        var sized_total_weight = Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                return Belenios_core__Common_types.Weight.$plus(accu, param[0]);
              }), Belenios_core__Common_types.Weight.zero, ballots);
        var encrypted_tally = Curry._1(E.process_ballots, ballots);
        return [
                encrypted_tally,
                {
                  sized_num_tallied: Curry._1(Belenios_core__Common.List.length, ballots),
                  sized_total_weight: sized_total_weight,
                  sized_encrypted_tally: Belenios_core__Common_types.Hash.hash_string(Belenios_core__Serializable_j.string_of_encrypted_tally((function (param) {
                              return Belenios_core__Common.swrite(G.to_string, param);
                            }), encrypted_tally))
                }
              ];
      })
  };
  var result_as_string = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_result$1, undefined);
      })
  };
  var result = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, (function (param) {
                      return Belenios_core__Serializable_j.election_result_of_string(read_result, param);
                    }), CamlinternalLazy.force(result_as_string));
      })
  };
  var lazy_shuffles = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_shuffles$1, undefined);
      })
  };
  var shuffles_as_text = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, (function (param) {
                          return param[2];
                        })), CamlinternalLazy.force(lazy_shuffles));
      })
  };
  var shuffles = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, (function (param) {
                          return Belenios_core__Serializable_j.shuffle_of_string((function (param) {
                                        return Belenios_core__Common.sread(G.of_string, param);
                                      }), param);
                        })), CamlinternalLazy.force(shuffles_as_text));
      })
  };
  var shuffles_hash = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, Belenios_core__Common.sha256_b64), CamlinternalLazy.force(shuffles_as_text));
      })
  };
  var shuffles_check = {
    LAZY_DONE: false,
    VAL: (function () {
        var match = CamlinternalLazy.force(raw_encrypted_tally);
        var cc = Curry._1(E.extract_nh_ciphertexts, match[0]);
        var ss = CamlinternalLazy.force(shuffles);
        if (ss !== undefined) {
          var _i = 0;
          var _cc = cc;
          var _ss = ss;
          while(true) {
            var ss$1 = _ss;
            var cc$1 = _cc;
            var i = _i;
            if (!ss$1) {
              return true;
            }
            var s = ss$1.hd;
            if (!Curry._2(E.check_shuffle, cc$1, s)) {
              return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "shuffle #",
                                _1: {
                                  TAG: /* Int */4,
                                  _0: /* Int_d */0,
                                  _1: /* No_padding */0,
                                  _2: /* No_precision */0,
                                  _3: {
                                    TAG: /* String_literal */11,
                                    _0: " failed tests",
                                    _1: /* End_of_format */0
                                  }
                                }
                              },
                              _1: "shuffle #%d failed tests"
                            }), i);
            }
            _ss = ss$1.tl;
            _cc = s.shuffle_ciphertexts;
            _i = i + 1 | 0;
            continue ;
          };
        } else {
          return true;
        }
      })
  };
  var encrypted_tally = {
    LAZY_DONE: false,
    VAL: (function () {
        var match = CamlinternalLazy.force(raw_encrypted_tally);
        var ntally = match[1];
        var raw_encrypted_tally$1 = match[0];
        var match$1 = Curry._2(Belenios_core__Common.$$Option.map, Belenios_core__Common.List.rev, CamlinternalLazy.force(shuffles));
        if (match$1 !== undefined && match$1) {
          return [
                  Curry._2(E.merge_nh_ciphertexts, match$1.hd.shuffle_ciphertexts, raw_encrypted_tally$1),
                  ntally
                ];
        } else {
          return [
                  raw_encrypted_tally$1,
                  ntally
                ];
        }
      })
  };
  var vote = function (privcred, ballot) {
    var sk;
    if (privcred !== undefined) {
      var CD = Belenios_core__Credential.MakeDerive(G);
      sk = Curry._2(CD.derive, election.e_uuid, privcred);
    } else {
      sk = Stdlib.failwith("missing private credential");
    }
    var b = Curry._2(E.create_ballot, sk, ballot);
    if (!Curry._1(E.check_ballot, b)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              372,
              4
            ],
            Error: new Error()
          };
    }
    return Curry._1(string_of_ballot, b);
  };
  var decrypt = function (owned_owner, privkey) {
    var sk = Belenios_core__Serializable_j.number_of_string(privkey);
    var pk = Curry._2(G.$star$star$tilde, G.g, sk);
    if (Curry._2(Belenios_core__Common_types.$$Array.for_all, (function (x) {
              return !Curry._2(G.$eq$tilde, x, pk);
            }), CamlinternalLazy.force(pks))) {
      Stdlib.failwith("your key is not present in trustees");
    }
    var shuffles = CamlinternalLazy.force(shuffles_hash);
    if (shuffles !== undefined) {
      if (shuffles) {
        Curry._2(Belenios_core__Common.List.iter, (function (s) {
                Curry._1(Stdlib__Printf.ksprintf(print_msg$1, /* Format */{
                          _0: {
                            TAG: /* String_literal */11,
                            _0: "I: shuffle ",
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: {
                                TAG: /* String_literal */11,
                                _0: " has been applied",
                                _1: /* End_of_format */0
                              }
                            }
                          },
                          _1: "I: shuffle %s has been applied"
                        }), s);
              }), shuffles);
      } else if (Belenios__Election.has_nh_questions(election)) {
        Stdlib.failwith("the election has non-homomorphic questions and no shuffles were found");
      }
      
    } else if (Belenios__Election.has_nh_questions(election)) {
      Stdlib.failwith("the election has non-homomorphic questions and no shuffles were found");
    }
    if (Belenios__Election.has_nh_questions(election)) {
      Curry._1(print_msg$1, "I: you should check that your shuffle appears in the list of applied shuffles");
    }
    var match = CamlinternalLazy.force(encrypted_tally);
    var tally = match[0];
    var factor = Curry._2(E.compute_factor, tally, sk);
    if (!Curry._3(E.check_factor, tally, pk, factor)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              395,
              4
            ],
            Error: new Error()
          };
    }
    var pd = Belenios_core__Serializable_j.string_of_partial_decryption((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), factor);
    var opd_owned_payload = Belenios_core__Common_types.Hash.hash_string(pd);
    var opd = {
      owned_owner: owned_owner,
      owned_payload: opd_owned_payload
    };
    return [
            pd,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, opd)
          ];
  };
  var tdecrypt = function (owned_owner, key, pdk) {
    var sk = Curry._1(P.derive_sk, key);
    var dk = Curry._1(P.derive_dk, key);
    var vk = Curry._2(G.$star$star$tilde, G.g, sk);
    var pdk$1 = Curry._3(C.recv, dk, vk, Belenios_core__Serializable_j.encrypted_msg_of_string((function (param) {
                return Belenios_core__Common.sread(G.of_string, param);
              }), pdk));
    var pdk$2 = Belenios_core__Serializable_j.partial_decryption_key_of_string(pdk$1).pdk_decryption_key;
    var pvk = Curry._2(G.$star$star$tilde, G.g, pdk$2);
    if (trustees !== undefined) {
      if (!Curry._2(Belenios_core__Common.List.exists, (function (param) {
                return param.NAME === "Pedersen" ? Curry._2(Belenios_core__Common_types.$$Array.exists, (function (x) {
                                return Curry._2(G.$eq$tilde, x.trustee_public_key, pvk);
                              }), param.VAL.t_verification_keys) : false;
              }), trustees)) {
        Stdlib.failwith("your key is not present in threshold parameters");
      }
      
    } else {
      Stdlib.failwith("trustees are missing");
    }
    var match = CamlinternalLazy.force(encrypted_tally);
    var tally = match[0];
    var factor = Curry._2(E.compute_factor, tally, pdk$2);
    if (!Curry._3(E.check_factor, tally, pvk, factor)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              426,
              4
            ],
            Error: new Error()
          };
    }
    var pd = Belenios_core__Serializable_j.string_of_partial_decryption((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), factor);
    var opd_owned_payload = Belenios_core__Common_types.Hash.hash_string(pd);
    var opd = {
      owned_owner: owned_owner,
      owned_payload: opd_owned_payload
    };
    return [
            pd,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, opd)
          ];
  };
  var pds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_pds$1, undefined);
      })
  };
  var compute_result = function (param) {
    var x = CamlinternalLazy.force(pds);
    var pds$1 = x !== undefined ? x : Stdlib.failwith("missing partial decryptions");
    var factors = Curry._2(Belenios_core__Common.List.map, (function (param) {
            var of_string = function (param) {
              return Belenios_core__Serializable_j.partial_decryption_of_string((function (param) {
                            return Belenios_core__Common.sread(G.of_string, param);
                          }), param);
            };
            return {
                    owned_owner: param[1].owned_owner,
                    owned_payload: Curry._1(of_string, param[2])
                  };
          }), pds$1);
    var match = CamlinternalLazy.force(encrypted_tally);
    var sized = match[1];
    var sized_sized_num_tallied = sized.sized_num_tallied;
    var sized_sized_total_weight = sized.sized_total_weight;
    var sized_sized_encrypted_tally = match[0];
    var sized$1 = {
      sized_num_tallied: sized_sized_num_tallied,
      sized_total_weight: sized_sized_total_weight,
      sized_encrypted_tally: sized_sized_encrypted_tally
    };
    if (trustees === undefined) {
      return Stdlib.failwith("missing trustees");
    }
    var result = Curry._3(E.compute_result, sized$1, factors, trustees);
    if (result.TAG === /* Ok */0) {
      return Belenios_core__Serializable_j.string_of_election_result(write_result, result._0);
    } else {
      return Stdlib.failwith(Belenios__Trustees.string_of_combination_error(result._0));
    }
  };
  var verify = function (param) {
    Curry._1(fsck$1, undefined);
    if (trustees !== undefined) {
      if (!Curry._1(K.check, trustees)) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                461,
                8
              ],
              Error: new Error()
            };
      }
      if (!Curry._2(G.$eq$tilde, public_key, Curry._1(K.combine_keys, trustees))) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                462,
                8
              ],
              Error: new Error()
            };
      }
      
    } else {
      Stdlib.failwith("missing trustees");
    }
    var match = CamlinternalLazy.force(rawballots);
    if (match !== undefined) {
      var b = CamlinternalLazy.force(shuffles_check);
      if (!b) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                467,
                55
              ],
              Error: new Error()
            };
      }
      
    } else {
      Curry._1(print_msg$1, "I: no ballots to check");
    }
    var match$1 = CamlinternalLazy.force(result);
    var match$2 = CamlinternalLazy.force(pds);
    if (match$1 !== undefined) {
      if (trustees !== undefined) {
        if (match$2 !== undefined) {
          var factors = Curry._2(Belenios_core__Common.List.map, (function (param) {
                  var of_string = function (param) {
                    return Belenios_core__Serializable_j.partial_decryption_of_string((function (param) {
                                  return Belenios_core__Common.sread(G.of_string, param);
                                }), param);
                  };
                  return {
                          owned_owner: param[1].owned_owner,
                          owned_payload: Curry._1(of_string, param[2])
                        };
                }), match$2);
          var match$3 = CamlinternalLazy.force(encrypted_tally);
          var sized = match$3[1];
          var sized_sized_num_tallied = sized.sized_num_tallied;
          var sized_sized_total_weight = sized.sized_total_weight;
          var sized_sized_encrypted_tally = match$3[0];
          var sized$1 = {
            sized_num_tallied: sized_sized_num_tallied,
            sized_total_weight: sized_sized_total_weight,
            sized_encrypted_tally: sized_sized_encrypted_tally
          };
          if (!Curry._4(E.check_result, sized$1, factors, trustees, match$1)) {
            Stdlib.failwith("check_result failed");
          }
          
        } else {
          Stdlib.failwith("no partial decryptions");
        }
      } else {
        Stdlib.failwith("missing trustees");
      }
    } else {
      Curry._1(print_msg$1, "I: no result to check");
    }
    Curry._1(print_msg$1, "I: all checks passed");
  };
  var shuffle_ciphertexts = function (owned_owner) {
    var match = CamlinternalLazy.force(encrypted_tally);
    var cc = Curry._1(E.extract_nh_ciphertexts, match[0]);
    var shuffle = Curry._1(E.shuffle_ciphertexts, cc);
    var shuffle_s = Belenios_core__Serializable_j.string_of_shuffle((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), shuffle);
    var owned_owned_payload = Belenios_core__Common_types.Hash.hash_string(shuffle_s);
    var owned = {
      owned_owner: owned_owner,
      owned_payload: owned_owned_payload
    };
    return [
            shuffle_s,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, owned)
          ];
  };
  var checksums = function (param) {
    var election = setup_data$1.setup_election;
    var shuffles = Belenios_core__Common.let$amp(CamlinternalLazy.force(lazy_shuffles), (function (x) {
            return Curry._2(Belenios_core__Common.List.map, (function (param) {
                          return param[1];
                        }), x);
          }));
    var match = CamlinternalLazy.force(encrypted_tally);
    var encrypted_tally$1 = Caml_option.some(match[1].sized_encrypted_tally);
    var trustees = trustees_as_string !== undefined ? trustees_as_string : Stdlib.failwith("missing trustees");
    var x = CamlinternalLazy.force(raw_public_creds);
    var public_credentials = x !== undefined ? x : Stdlib.failwith("missing credentials");
    return Belenios_core__Serializable_j.string_of_election_checksums(Belenios__Election.compute_checksums(election, trustees, public_credentials, shuffles, encrypted_tally$1));
  };
  var split = function (line) {
    var i = Curry._2(Belenios_core__Common.$$String.index_opt, line, /* ' ' */32);
    if (i !== undefined) {
      return [
              Curry._3(Belenios_core__Common.$$String.sub, line, 0, i),
              Curry._3(Belenios_core__Common.$$String.sub, line, i + 1 | 0, (line.length - i | 0) - 1 | 0)
            ];
    } else {
      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "Invalid private credential line (",
                        _1: {
                          TAG: /* Caml_string */3,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* Char_literal */12,
                            _0: /* ')' */41,
                            _1: /* End_of_format */0
                          }
                        }
                      },
                      _1: "Invalid private credential line (%S)"
                    }), line);
    }
  };
  var compute_voters = function (privcreds) {
    var D = Belenios_core__Credential.MakeDerive(G);
    var map = Curry._3(Belenios_core__Common.List.fold_left, (function (accu, line) {
            var match = split(line);
            return Curry._3(Belenios_core__Common.SMap.add, Curry._1(G.to_string, Curry._2(G.$star$star$tilde, G.g, Curry._2(D.derive, election.e_uuid, match[1]))), match[0], accu);
          }), Belenios_core__Common.SMap.empty, privcreds);
    var creds = CamlinternalLazy.force(public_creds);
    if (creds !== undefined) {
      return Curry._3(Belenios_core__Common.SMap.fold, (function (cred, param, accu) {
                    var h = param[1].contents;
                    if (h === undefined) {
                      return accu;
                    }
                    var id = Curry._2(Belenios_core__Common.SMap.find_opt, cred, map);
                    if (id !== undefined) {
                      return {
                              hd: id,
                              tl: accu
                            };
                    } else {
                      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                      _0: {
                                        TAG: /* String_literal */11,
                                        _0: "Unknown public key in ballot ",
                                        _1: {
                                          TAG: /* String */2,
                                          _0: /* No_padding */0,
                                          _1: /* End_of_format */0
                                        }
                                      },
                                      _1: "Unknown public key in ballot %s"
                                    }), h);
                    }
                  }), Caml_option.valFromOption(creds), /* [] */0);
    } else {
      return /* [] */0;
    }
  };
  var compute_ballot_summary = function (param) {
    var match = CamlinternalLazy.force(public_creds_weights);
    var has_weights = match !== undefined ? match[0] : false;
    return Belenios_core__Serializable_j.string_of_ballot_summary(Curry._2(Belenios_core__Common.List.rev_map, (function (param) {
                      var w = param[1][1];
                      var bs_weight;
                      if (has_weights) {
                        bs_weight = Caml_option.some(w);
                      } else {
                        if (!Belenios_core__Common_types.Weight.is_int(w, 1)) {
                          throw {
                                RE_EXN_ID: "Assert_failure",
                                _1: [
                                  "tool_election.ml",
                                  562,
                                  15
                                ],
                                Error: new Error()
                              };
                        }
                        bs_weight = undefined;
                      }
                      return {
                              bs_hash: param[0],
                              bs_weight: bs_weight
                            };
                    }), CamlinternalLazy.force(final_ballots)));
  };
  var compute_encrypted_tally = function (param) {
    var match = CamlinternalLazy.force(raw_encrypted_tally);
    return [
            Belenios_core__Serializable_j.string_of_encrypted_tally((function (param) {
                    return Belenios_core__Common.swrite(G.to_string, param);
                  }), match[0]),
            Belenios_core__Serializable_j.string_of_sized_encrypted_tally(Belenios_core__Serializable_j.write_hash, match[1])
          ];
  };
  var let_fingerprint = include.fingerprint;
  var let_S = include.S;
  var let_get_credential = include.get_credential;
  return {
          vote: vote,
          decrypt: decrypt,
          tdecrypt: tdecrypt,
          compute_result: compute_result,
          verify: verify,
          shuffle_ciphertexts: shuffle_ciphertexts,
          checksums: checksums,
          compute_voters: compute_voters,
          compute_ballot_summary: compute_ballot_summary,
          compute_encrypted_tally: compute_encrypted_tally
        };
}

function MakeRaw(funarg, funarg$1) {
  var fsck = function (param) {
    
  };
  var setup_election = Belenios_core__Common_types.Hash.hash_string(funarg.raw_election);
  var setup_trustees = Belenios_core__Common_types.Hash.hash_string("");
  var setup_credentials = Belenios_core__Common_types.Hash.hash_string("");
  var setup_data = {
    setup_election: setup_election,
    setup_trustees: setup_trustees,
    setup_credentials: setup_credentials
  };
  var get_public_creds = function (param) {
    return funarg.public_creds;
  };
  var get_trustees = function (param) {
    return funarg.trustees;
  };
  var get_ballots = function (param) {
    return funarg.ballots;
  };
  var get_shuffles = function (param) {
    
  };
  var get_pds = function (param) {
    return funarg.pds;
  };
  var get_result = function (param) {
    
  };
  var print_msg = function (prim) {
    console.log(prim);
  };
  var partial_arg_raw_election = funarg.raw_election;
  var fsck$1 = fsck;
  var setup_data$1 = setup_data;
  var raw_election = partial_arg_raw_election;
  var get_trustees$1 = get_trustees;
  var get_public_creds$1 = get_public_creds;
  var get_ballots$1 = get_ballots;
  var get_shuffles$1 = get_shuffles;
  var get_pds$1 = get_pds;
  var get_result$1 = get_result;
  var print_msg$1 = print_msg;
  var include = Belenios__Election.Make({
        raw_election: raw_election
      }, Belenios_tool_common__Random, {});
  var G = include.G;
  var election = include.election;
  var public_key = include.public_key;
  var string_of_ballot = include.string_of_ballot;
  var ballot_of_string = include.ballot_of_string;
  var write_result = include.write_result;
  var read_result = include.read_result;
  var E = include.E;
  var Trustees = Belenios__Trustees.get_by_version(election.e_version);
  var P = Curry._2(Trustees.MakePKI, G, Belenios_tool_common__Random);
  var C = Curry._3(Trustees.MakeChannels, G, Belenios_tool_common__Random, P);
  var K = Curry._1(Trustees.MakeCombinator, G);
  var trustees_as_string = Curry._1(get_trustees$1, undefined);
  var trustees = Curry._2(Belenios_core__Common.$$Option.map, (function (param) {
          return Belenios_core__Serializable_j.trustees_of_string((function (param) {
                        return Belenios_core__Common.sread(G.of_string, param);
                      }), param);
        }), trustees_as_string);
  var public_keys_with_pok = Curry._2(Belenios_core__Common.$$Option.map, (function (x) {
          return Curry._1(Belenios_core__Common_types.$$Array.of_list, Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
                                if (param.NAME === "Pedersen") {
                                  return Curry._1(Belenios_core__Common_types.$$Array.to_list, param.VAL.t_verification_keys);
                                } else {
                                  return {
                                          hd: param.VAL,
                                          tl: /* [] */0
                                        };
                                }
                              }), x)));
        }), trustees);
  if (trustees !== undefined) {
    if (!Curry._1(K.check, trustees)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              166,
              6
            ],
            Error: new Error()
          };
    }
    var y$p = Curry._1(K.combine_keys, trustees);
    if (!Curry._2(G.$eq$tilde, public_key, y$p)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              168,
              6
            ],
            Error: new Error()
          };
    }
    
  } else {
    Stdlib.failwith("missing trustees");
  }
  var public_keys = Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common_types.$$Array.map, (function (pk) {
              return pk.trustee_public_key;
            })), public_keys_with_pok);
  var pks = {
    LAZY_DONE: false,
    VAL: (function () {
        if (public_keys !== undefined) {
          return public_keys;
        } else {
          return Stdlib.failwith("missing public keys");
        }
      })
  };
  var PPC = Belenios_core__Credential.MakeParsePublicCredential(G);
  var raw_public_creds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_public_creds$1, undefined);
      })
  };
  var public_creds_weights = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._2(Belenios_core__Common.List.fold_left, (function (param, x) {
                          var accu = param[1];
                          var has_weights = param[0] || Curry._2(Belenios_core__Common.$$String.index_opt, x, /* ',' */44) !== undefined;
                          var match = Curry._1(PPC.parse_public_credential, x);
                          if (match === undefined) {
                            return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                            _0: {
                                              TAG: /* String */2,
                                              _0: /* No_padding */0,
                                              _1: {
                                                TAG: /* String_literal */11,
                                                _0: " is not a valid public credential",
                                                _1: /* End_of_format */0
                                              }
                                            },
                                            _1: "%s is not a valid public credential"
                                          }), x);
                          }
                          var y = Curry._1(G.to_string, match[1]);
                          if (Curry._2(Belenios_core__Common.SMap.mem, y, accu)) {
                            return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                            _0: {
                                              TAG: /* String_literal */11,
                                              _0: "duplicate credential: ",
                                              _1: {
                                                TAG: /* String */2,
                                                _0: /* No_padding */0,
                                                _1: /* End_of_format */0
                                              }
                                            },
                                            _1: "duplicate credential: %s"
                                          }), y);
                          } else {
                            return [
                                    has_weights,
                                    Curry._3(Belenios_core__Common.SMap.add, y, [
                                          match[0],
                                          {
                                            contents: undefined
                                          }
                                        ], accu)
                                  ];
                          }
                        }), [
                        false,
                        Belenios_core__Common.SMap.empty
                      ]), CamlinternalLazy.force(raw_public_creds));
      })
  };
  var public_creds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, (function (prim) {
                      return prim[1];
                    }), CamlinternalLazy.force(public_creds_weights));
      })
  };
  var rawballots = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_ballots$1, undefined);
      })
  };
  var string_of_cast_error = function (param) {
    if (typeof param === "string") {
      if (param === "NonCanonical") {
        return "ballot not in canonical form";
      } else if (param === "DuplicateBallot") {
        return "duplicate ballot";
      } else if (param === "WrongUsername") {
        return "wrong username";
      } else if (param === "UsedCredential") {
        return "used credential";
      } else if (param === "RevoteNotAllowed") {
        return "revote not allowed";
      } else if (param === "WrongWeight") {
        return "wrong weight";
      } else if (param === "InvalidBallot") {
        return "invalid ballot";
      } else if (param === "ExpiredBallot") {
        return "expired ballot";
      } else if (param === "InvalidCredential") {
        return "invalid credential";
      } else {
        return "wrong credential";
      }
    } else {
      return Curry._1(Stdlib__Printf.sprintf(/* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "ill-formed ballot: ",
                        _1: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: /* End_of_format */0
                        }
                      },
                      _1: "ill-formed ballot: %s"
                    }), Stdlib__Printexc.to_string(param.VAL));
    }
  };
  var cast = function (accu, rawballot) {
    var hash = Belenios_core__Common_types.Hash.hash_string(rawballot);
    var creds = CamlinternalLazy.force(public_creds);
    if (creds === undefined) {
      return Stdlib.failwith("missing public credentials");
    }
    var creds$1 = Caml_option.valFromOption(creds);
    var ballot_id = Belenios_core__Common.sha256_b64(rawballot);
    return Belenios_core__Common.let$at((function (cont) {
                  return Belenios_core__Common.let$at((function (cont2) {
                                if (Curry._2(Belenios_core__Common.SSet.mem, ballot_id, accu)) {
                                  return Curry._1(cont, {
                                              TAG: /* Error */1,
                                              _0: "DuplicateBallot"
                                            });
                                } else {
                                  return Curry._1(cont2, Curry._2(Belenios_core__Common.SSet.add, ballot_id, accu));
                                }
                              }), (function (accu) {
                                var x = Curry._1(E.check_rawballot, rawballot);
                                if (x.TAG !== /* Ok */0) {
                                  return Curry._1(cont, x);
                                }
                                var rc = x._0;
                                var x$1 = Curry._2(Belenios_core__Common.SMap.find_opt, rc.rc_credential, creds$1);
                                if (x$1 !== undefined) {
                                  if (Curry._1(rc.rc_check, undefined)) {
                                    return Curry._1(cont, {
                                                TAG: /* Ok */0,
                                                _0: [
                                                  rc.rc_credential,
                                                  x$1[1].contents,
                                                  accu
                                                ]
                                              });
                                  } else {
                                    return Curry._1(cont, {
                                                TAG: /* Error */1,
                                                _0: "InvalidBallot"
                                              });
                                  }
                                } else {
                                  return Curry._1(cont, {
                                              TAG: /* Error */1,
                                              _0: "InvalidCredential"
                                            });
                                }
                              }));
                }), (function (x) {
                  if (x.TAG !== /* Ok */0) {
                    return Curry._2(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                    _0: {
                                      TAG: /* String_literal */11,
                                      _0: "error while casting ballot ",
                                      _1: {
                                        TAG: /* String */2,
                                        _0: /* No_padding */0,
                                        _1: {
                                          TAG: /* String_literal */11,
                                          _0: ": ",
                                          _1: {
                                            TAG: /* String */2,
                                            _0: /* No_padding */0,
                                            _1: /* End_of_format */0
                                          }
                                        }
                                      }
                                    },
                                    _1: "error while casting ballot %s: %s"
                                  }), ballot_id, string_of_cast_error(x._0));
                  }
                  var match = x._0;
                  var credential = match[0];
                  var match$1 = Curry._2(Belenios_core__Common.SMap.find_opt, credential, creds$1);
                  if (match$1 === undefined) {
                    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                    _0: {
                                      TAG: /* String_literal */11,
                                      _0: "invalid credential for ballot ",
                                      _1: {
                                        TAG: /* String */2,
                                        _0: /* No_padding */0,
                                        _1: /* End_of_format */0
                                      }
                                    },
                                    _1: "invalid credential for ballot %s"
                                  }), ballot_id);
                  }
                  var used = match$1[1];
                  if (!Caml_obj.caml_equal(used.contents, match[1])) {
                    throw {
                          RE_EXN_ID: "Assert_failure",
                          _1: [
                            "tool_election.ml",
                            255,
                            13
                          ],
                          Error: new Error()
                        };
                  }
                  used.contents = ballot_id;
                  return [
                          [
                            hash,
                            [
                              credential,
                              match$1[0],
                              rawballot
                            ]
                          ],
                          match[2]
                        ];
                }));
  };
  var rev_ballots = {
    LAZY_DONE: false,
    VAL: (function () {
        var bs = CamlinternalLazy.force(rawballots);
        if (bs !== undefined) {
          var _accu = /* [] */0;
          var _seen = Belenios_core__Common.SSet.empty;
          var _param = bs;
          while(true) {
            var param = _param;
            var seen = _seen;
            var accu = _accu;
            if (!param) {
              return accu;
            }
            var match = cast(seen, param.hd);
            _param = param.tl;
            _seen = match[1];
            _accu = {
              hd: match[0],
              tl: accu
            };
            continue ;
          };
        } else {
          return /* [] */0;
        }
      })
  };
  var final_ballots = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._3(Belenios_core__Common.List.fold_left, (function (accu, b) {
                        var credential = b[1][0];
                        var seen = accu[0];
                        if (Curry._2(Belenios_core__Common.SSet.mem, credential, seen)) {
                          return accu;
                        } else {
                          return [
                                  Curry._2(Belenios_core__Common.SSet.add, credential, seen),
                                  {
                                    hd: b,
                                    tl: accu[1]
                                  }
                                ];
                        }
                      }), [
                      Belenios_core__Common.SSet.empty,
                      /* [] */0
                    ], CamlinternalLazy.force(rev_ballots))[1];
      })
  };
  var raw_encrypted_tally = {
    LAZY_DONE: false,
    VAL: (function () {
        var ballots = Curry._2(Belenios_core__Common.List.rev_map, (function (param) {
                var match = param[1];
                return [
                        match[1],
                        Curry._1(ballot_of_string, match[2])
                      ];
              }), CamlinternalLazy.force(final_ballots));
        var sized_total_weight = Curry._3(Belenios_core__Common.List.fold_left, (function (accu, param) {
                return Belenios_core__Common_types.Weight.$plus(accu, param[0]);
              }), Belenios_core__Common_types.Weight.zero, ballots);
        var encrypted_tally = Curry._1(E.process_ballots, ballots);
        return [
                encrypted_tally,
                {
                  sized_num_tallied: Curry._1(Belenios_core__Common.List.length, ballots),
                  sized_total_weight: sized_total_weight,
                  sized_encrypted_tally: Belenios_core__Common_types.Hash.hash_string(Belenios_core__Serializable_j.string_of_encrypted_tally((function (param) {
                              return Belenios_core__Common.swrite(G.to_string, param);
                            }), encrypted_tally))
                }
              ];
      })
  };
  var result_as_string = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_result$1, undefined);
      })
  };
  var result = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, (function (param) {
                      return Belenios_core__Serializable_j.election_result_of_string(read_result, param);
                    }), CamlinternalLazy.force(result_as_string));
      })
  };
  var lazy_shuffles = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_shuffles$1, undefined);
      })
  };
  var shuffles_as_text = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, (function (param) {
                          return param[2];
                        })), CamlinternalLazy.force(lazy_shuffles));
      })
  };
  var shuffles = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, (function (param) {
                          return Belenios_core__Serializable_j.shuffle_of_string((function (param) {
                                        return Belenios_core__Common.sread(G.of_string, param);
                                      }), param);
                        })), CamlinternalLazy.force(shuffles_as_text));
      })
  };
  var shuffles_hash = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._2(Belenios_core__Common.$$Option.map, Curry._1(Belenios_core__Common.List.map, Belenios_core__Common.sha256_b64), CamlinternalLazy.force(shuffles_as_text));
      })
  };
  var shuffles_check = {
    LAZY_DONE: false,
    VAL: (function () {
        var match = CamlinternalLazy.force(raw_encrypted_tally);
        var cc = Curry._1(E.extract_nh_ciphertexts, match[0]);
        var ss = CamlinternalLazy.force(shuffles);
        if (ss !== undefined) {
          var _i = 0;
          var _cc = cc;
          var _ss = ss;
          while(true) {
            var ss$1 = _ss;
            var cc$1 = _cc;
            var i = _i;
            if (!ss$1) {
              return true;
            }
            var s = ss$1.hd;
            if (!Curry._2(E.check_shuffle, cc$1, s)) {
              return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                              _0: {
                                TAG: /* String_literal */11,
                                _0: "shuffle #",
                                _1: {
                                  TAG: /* Int */4,
                                  _0: /* Int_d */0,
                                  _1: /* No_padding */0,
                                  _2: /* No_precision */0,
                                  _3: {
                                    TAG: /* String_literal */11,
                                    _0: " failed tests",
                                    _1: /* End_of_format */0
                                  }
                                }
                              },
                              _1: "shuffle #%d failed tests"
                            }), i);
            }
            _ss = ss$1.tl;
            _cc = s.shuffle_ciphertexts;
            _i = i + 1 | 0;
            continue ;
          };
        } else {
          return true;
        }
      })
  };
  var encrypted_tally = {
    LAZY_DONE: false,
    VAL: (function () {
        var match = CamlinternalLazy.force(raw_encrypted_tally);
        var ntally = match[1];
        var raw_encrypted_tally$1 = match[0];
        var match$1 = Curry._2(Belenios_core__Common.$$Option.map, Belenios_core__Common.List.rev, CamlinternalLazy.force(shuffles));
        if (match$1 !== undefined && match$1) {
          return [
                  Curry._2(E.merge_nh_ciphertexts, match$1.hd.shuffle_ciphertexts, raw_encrypted_tally$1),
                  ntally
                ];
        } else {
          return [
                  raw_encrypted_tally$1,
                  ntally
                ];
        }
      })
  };
  var vote = function (privcred, ballot) {
    var sk;
    if (privcred !== undefined) {
      var CD = Belenios_core__Credential.MakeDerive(G);
      sk = Curry._2(CD.derive, election.e_uuid, privcred);
    } else {
      sk = Stdlib.failwith("missing private credential");
    }
    var b = Curry._2(E.create_ballot, sk, ballot);
    if (!Curry._1(E.check_ballot, b)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              372,
              4
            ],
            Error: new Error()
          };
    }
    return Curry._1(string_of_ballot, b);
  };
  var decrypt = function (owned_owner, privkey) {
    var sk = Belenios_core__Serializable_j.number_of_string(privkey);
    var pk = Curry._2(G.$star$star$tilde, G.g, sk);
    if (Curry._2(Belenios_core__Common_types.$$Array.for_all, (function (x) {
              return !Curry._2(G.$eq$tilde, x, pk);
            }), CamlinternalLazy.force(pks))) {
      Stdlib.failwith("your key is not present in trustees");
    }
    var shuffles = CamlinternalLazy.force(shuffles_hash);
    if (shuffles !== undefined) {
      if (shuffles) {
        Curry._2(Belenios_core__Common.List.iter, (function (s) {
                Curry._1(Stdlib__Printf.ksprintf(print_msg$1, /* Format */{
                          _0: {
                            TAG: /* String_literal */11,
                            _0: "I: shuffle ",
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: {
                                TAG: /* String_literal */11,
                                _0: " has been applied",
                                _1: /* End_of_format */0
                              }
                            }
                          },
                          _1: "I: shuffle %s has been applied"
                        }), s);
              }), shuffles);
      } else if (Belenios__Election.has_nh_questions(election)) {
        Stdlib.failwith("the election has non-homomorphic questions and no shuffles were found");
      }
      
    } else if (Belenios__Election.has_nh_questions(election)) {
      Stdlib.failwith("the election has non-homomorphic questions and no shuffles were found");
    }
    if (Belenios__Election.has_nh_questions(election)) {
      Curry._1(print_msg$1, "I: you should check that your shuffle appears in the list of applied shuffles");
    }
    var match = CamlinternalLazy.force(encrypted_tally);
    var tally = match[0];
    var factor = Curry._2(E.compute_factor, tally, sk);
    if (!Curry._3(E.check_factor, tally, pk, factor)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              395,
              4
            ],
            Error: new Error()
          };
    }
    var pd = Belenios_core__Serializable_j.string_of_partial_decryption((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), factor);
    var opd_owned_payload = Belenios_core__Common_types.Hash.hash_string(pd);
    var opd = {
      owned_owner: owned_owner,
      owned_payload: opd_owned_payload
    };
    return [
            pd,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, opd)
          ];
  };
  var tdecrypt = function (owned_owner, key, pdk) {
    var sk = Curry._1(P.derive_sk, key);
    var dk = Curry._1(P.derive_dk, key);
    var vk = Curry._2(G.$star$star$tilde, G.g, sk);
    var pdk$1 = Curry._3(C.recv, dk, vk, Belenios_core__Serializable_j.encrypted_msg_of_string((function (param) {
                return Belenios_core__Common.sread(G.of_string, param);
              }), pdk));
    var pdk$2 = Belenios_core__Serializable_j.partial_decryption_key_of_string(pdk$1).pdk_decryption_key;
    var pvk = Curry._2(G.$star$star$tilde, G.g, pdk$2);
    if (trustees !== undefined) {
      if (!Curry._2(Belenios_core__Common.List.exists, (function (param) {
                return param.NAME === "Pedersen" ? Curry._2(Belenios_core__Common_types.$$Array.exists, (function (x) {
                                return Curry._2(G.$eq$tilde, x.trustee_public_key, pvk);
                              }), param.VAL.t_verification_keys) : false;
              }), trustees)) {
        Stdlib.failwith("your key is not present in threshold parameters");
      }
      
    } else {
      Stdlib.failwith("trustees are missing");
    }
    var match = CamlinternalLazy.force(encrypted_tally);
    var tally = match[0];
    var factor = Curry._2(E.compute_factor, tally, pdk$2);
    if (!Curry._3(E.check_factor, tally, pvk, factor)) {
      throw {
            RE_EXN_ID: "Assert_failure",
            _1: [
              "tool_election.ml",
              426,
              4
            ],
            Error: new Error()
          };
    }
    var pd = Belenios_core__Serializable_j.string_of_partial_decryption((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), factor);
    var opd_owned_payload = Belenios_core__Common_types.Hash.hash_string(pd);
    var opd = {
      owned_owner: owned_owner,
      owned_payload: opd_owned_payload
    };
    return [
            pd,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, opd)
          ];
  };
  var pds = {
    LAZY_DONE: false,
    VAL: (function () {
        return Curry._1(get_pds$1, undefined);
      })
  };
  var compute_result = function (param) {
    var x = CamlinternalLazy.force(pds);
    var pds$1 = x !== undefined ? x : Stdlib.failwith("missing partial decryptions");
    var factors = Curry._2(Belenios_core__Common.List.map, (function (param) {
            var of_string = function (param) {
              return Belenios_core__Serializable_j.partial_decryption_of_string((function (param) {
                            return Belenios_core__Common.sread(G.of_string, param);
                          }), param);
            };
            return {
                    owned_owner: param[1].owned_owner,
                    owned_payload: Curry._1(of_string, param[2])
                  };
          }), pds$1);
    var match = CamlinternalLazy.force(encrypted_tally);
    var sized = match[1];
    var sized_sized_num_tallied = sized.sized_num_tallied;
    var sized_sized_total_weight = sized.sized_total_weight;
    var sized_sized_encrypted_tally = match[0];
    var sized$1 = {
      sized_num_tallied: sized_sized_num_tallied,
      sized_total_weight: sized_sized_total_weight,
      sized_encrypted_tally: sized_sized_encrypted_tally
    };
    if (trustees === undefined) {
      return Stdlib.failwith("missing trustees");
    }
    var result = Curry._3(E.compute_result, sized$1, factors, trustees);
    if (result.TAG === /* Ok */0) {
      return Belenios_core__Serializable_j.string_of_election_result(write_result, result._0);
    } else {
      return Stdlib.failwith(Belenios__Trustees.string_of_combination_error(result._0));
    }
  };
  var verify = function (param) {
    Curry._1(fsck$1, undefined);
    if (trustees !== undefined) {
      if (!Curry._1(K.check, trustees)) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                461,
                8
              ],
              Error: new Error()
            };
      }
      if (!Curry._2(G.$eq$tilde, public_key, Curry._1(K.combine_keys, trustees))) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                462,
                8
              ],
              Error: new Error()
            };
      }
      
    } else {
      Stdlib.failwith("missing trustees");
    }
    var match = CamlinternalLazy.force(rawballots);
    if (match !== undefined) {
      var b = CamlinternalLazy.force(shuffles_check);
      if (!b) {
        throw {
              RE_EXN_ID: "Assert_failure",
              _1: [
                "tool_election.ml",
                467,
                55
              ],
              Error: new Error()
            };
      }
      
    } else {
      Curry._1(print_msg$1, "I: no ballots to check");
    }
    var match$1 = CamlinternalLazy.force(result);
    var match$2 = CamlinternalLazy.force(pds);
    if (match$1 !== undefined) {
      if (trustees !== undefined) {
        if (match$2 !== undefined) {
          var factors = Curry._2(Belenios_core__Common.List.map, (function (param) {
                  var of_string = function (param) {
                    return Belenios_core__Serializable_j.partial_decryption_of_string((function (param) {
                                  return Belenios_core__Common.sread(G.of_string, param);
                                }), param);
                  };
                  return {
                          owned_owner: param[1].owned_owner,
                          owned_payload: Curry._1(of_string, param[2])
                        };
                }), match$2);
          var match$3 = CamlinternalLazy.force(encrypted_tally);
          var sized = match$3[1];
          var sized_sized_num_tallied = sized.sized_num_tallied;
          var sized_sized_total_weight = sized.sized_total_weight;
          var sized_sized_encrypted_tally = match$3[0];
          var sized$1 = {
            sized_num_tallied: sized_sized_num_tallied,
            sized_total_weight: sized_sized_total_weight,
            sized_encrypted_tally: sized_sized_encrypted_tally
          };
          if (!Curry._4(E.check_result, sized$1, factors, trustees, match$1)) {
            Stdlib.failwith("check_result failed");
          }
          
        } else {
          Stdlib.failwith("no partial decryptions");
        }
      } else {
        Stdlib.failwith("missing trustees");
      }
    } else {
      Curry._1(print_msg$1, "I: no result to check");
    }
    Curry._1(print_msg$1, "I: all checks passed");
  };
  var shuffle_ciphertexts = function (owned_owner) {
    var match = CamlinternalLazy.force(encrypted_tally);
    var cc = Curry._1(E.extract_nh_ciphertexts, match[0]);
    var shuffle = Curry._1(E.shuffle_ciphertexts, cc);
    var shuffle_s = Belenios_core__Serializable_j.string_of_shuffle((function (param) {
            return Belenios_core__Common.swrite(G.to_string, param);
          }), shuffle);
    var owned_owned_payload = Belenios_core__Common_types.Hash.hash_string(shuffle_s);
    var owned = {
      owned_owner: owned_owner,
      owned_payload: owned_owned_payload
    };
    return [
            shuffle_s,
            Belenios_core__Serializable_j.string_of_owned(Belenios_core__Serializable_j.write_hash, owned)
          ];
  };
  var checksums = function (param) {
    var election = setup_data$1.setup_election;
    var shuffles = Belenios_core__Common.let$amp(CamlinternalLazy.force(lazy_shuffles), (function (x) {
            return Curry._2(Belenios_core__Common.List.map, (function (param) {
                          return param[1];
                        }), x);
          }));
    var match = CamlinternalLazy.force(encrypted_tally);
    var encrypted_tally$1 = Caml_option.some(match[1].sized_encrypted_tally);
    var trustees = trustees_as_string !== undefined ? trustees_as_string : Stdlib.failwith("missing trustees");
    var x = CamlinternalLazy.force(raw_public_creds);
    var public_credentials = x !== undefined ? x : Stdlib.failwith("missing credentials");
    return Belenios_core__Serializable_j.string_of_election_checksums(Belenios__Election.compute_checksums(election, trustees, public_credentials, shuffles, encrypted_tally$1));
  };
  var split = function (line) {
    var i = Curry._2(Belenios_core__Common.$$String.index_opt, line, /* ' ' */32);
    if (i !== undefined) {
      return [
              Curry._3(Belenios_core__Common.$$String.sub, line, 0, i),
              Curry._3(Belenios_core__Common.$$String.sub, line, i + 1 | 0, (line.length - i | 0) - 1 | 0)
            ];
    } else {
      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "Invalid private credential line (",
                        _1: {
                          TAG: /* Caml_string */3,
                          _0: /* No_padding */0,
                          _1: {
                            TAG: /* Char_literal */12,
                            _0: /* ')' */41,
                            _1: /* End_of_format */0
                          }
                        }
                      },
                      _1: "Invalid private credential line (%S)"
                    }), line);
    }
  };
  var compute_voters = function (privcreds) {
    var D = Belenios_core__Credential.MakeDerive(G);
    var map = Curry._3(Belenios_core__Common.List.fold_left, (function (accu, line) {
            var match = split(line);
            return Curry._3(Belenios_core__Common.SMap.add, Curry._1(G.to_string, Curry._2(G.$star$star$tilde, G.g, Curry._2(D.derive, election.e_uuid, match[1]))), match[0], accu);
          }), Belenios_core__Common.SMap.empty, privcreds);
    var creds = CamlinternalLazy.force(public_creds);
    if (creds !== undefined) {
      return Curry._3(Belenios_core__Common.SMap.fold, (function (cred, param, accu) {
                    var h = param[1].contents;
                    if (h === undefined) {
                      return accu;
                    }
                    var id = Curry._2(Belenios_core__Common.SMap.find_opt, cred, map);
                    if (id !== undefined) {
                      return {
                              hd: id,
                              tl: accu
                            };
                    } else {
                      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                                      _0: {
                                        TAG: /* String_literal */11,
                                        _0: "Unknown public key in ballot ",
                                        _1: {
                                          TAG: /* String */2,
                                          _0: /* No_padding */0,
                                          _1: /* End_of_format */0
                                        }
                                      },
                                      _1: "Unknown public key in ballot %s"
                                    }), h);
                    }
                  }), Caml_option.valFromOption(creds), /* [] */0);
    } else {
      return /* [] */0;
    }
  };
  var compute_ballot_summary = function (param) {
    var match = CamlinternalLazy.force(public_creds_weights);
    var has_weights = match !== undefined ? match[0] : false;
    return Belenios_core__Serializable_j.string_of_ballot_summary(Curry._2(Belenios_core__Common.List.rev_map, (function (param) {
                      var w = param[1][1];
                      var bs_weight;
                      if (has_weights) {
                        bs_weight = Caml_option.some(w);
                      } else {
                        if (!Belenios_core__Common_types.Weight.is_int(w, 1)) {
                          throw {
                                RE_EXN_ID: "Assert_failure",
                                _1: [
                                  "tool_election.ml",
                                  562,
                                  15
                                ],
                                Error: new Error()
                              };
                        }
                        bs_weight = undefined;
                      }
                      return {
                              bs_hash: param[0],
                              bs_weight: bs_weight
                            };
                    }), CamlinternalLazy.force(final_ballots)));
  };
  var compute_encrypted_tally = function (param) {
    var match = CamlinternalLazy.force(raw_encrypted_tally);
    return [
            Belenios_core__Serializable_j.string_of_encrypted_tally((function (param) {
                    return Belenios_core__Common.swrite(G.to_string, param);
                  }), match[0]),
            Belenios_core__Serializable_j.string_of_sized_encrypted_tally(Belenios_core__Serializable_j.write_hash, match[1])
          ];
  };
  var let_fingerprint = include.fingerprint;
  var let_S = include.S;
  var let_get_credential = include.get_credential;
  return {
          vote: vote,
          decrypt: decrypt,
          tdecrypt: tdecrypt,
          compute_result: compute_result,
          verify: verify,
          shuffle_ciphertexts: shuffle_ciphertexts,
          checksums: checksums,
          compute_voters: compute_voters,
          compute_ballot_summary: compute_ballot_summary,
          compute_encrypted_tally: compute_encrypted_tally
        };
}

export {
  Make ,
  MakeRaw ,
}
/* Stdlib__Printexc Not a pure module */
