// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Stdlib__Map from "melange/./map.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios__Group from "../../lib/shell/group.js";
import * as Belenios_core__Common from "../../lib/core/common.js";
import * as Belenios_core__Credential from "../../lib/core/credential.js";
import * as Belenios_core__Common_types from "../../lib/core/common_types.js";

function find_first(n, _first) {
  while(true) {
    var first = _first;
    if (String(first).length === String(first + n | 0).length) {
      return first;
    }
    _first = Math.imul(10, first);
    continue ;
  };
}

function generate_ids(n) {
  var first = find_first(n, 1);
  var last = (first + n | 0) - 1 | 0;
  var _last = last;
  var _accu = /* [] */0;
  while(true) {
    var accu = _accu;
    var last$1 = _last;
    if (last$1 < first) {
      return accu;
    }
    var address = String(last$1);
    var x_1 = {
      address: address,
      login: undefined,
      weight: undefined
    };
    var x = [
      "Plain",
      x_1
    ];
    _accu = {
      hd: x,
      tl: accu
    };
    _last = last$1 - 1 | 0;
    continue ;
  };
}

function Make(funarg, funarg$1, funarg$2) {
  var uuid = Belenios_core__Common_types.Uuid.wrap(funarg.uuid);
  var G = Curry._1(Belenios__Group.of_string(funarg.version), funarg.group);
  var CG = Belenios_core__Credential.MakeGenerate(funarg$1);
  var CD = Belenios_core__Credential.MakeDerive(G);
  var CredSet = Stdlib__Map.Make({
        compare: G.compare
      });
  var derive_in_group = function (x) {
    if (!Belenios_core__Credential.check(x)) {
      return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                      _0: {
                        TAG: /* String_literal */11,
                        _0: "invalid secret credential: ",
                        _1: {
                          TAG: /* String */2,
                          _0: /* No_padding */0,
                          _1: /* End_of_format */0
                        }
                      },
                      _1: "invalid secret credential: %s"
                    }), x);
    }
    var x$1 = Curry._2(CD.derive, uuid, x);
    return Curry._2(G.$star$star$tilde, G.g, x$1);
  };
  var derive = function (x) {
    return Curry._1(G.to_string, derive_in_group(x));
  };
  var generate = function (ids) {
    var implicit_weights = !Belenios_core__Common.has_explicit_weights(ids);
    var match = Curry._3(Belenios_core__Common.List.fold_left, (function (param, id) {
            var match = Belenios_core__Common.Voter.get(id);
            var username = match[1];
            var priv = Curry._1(CG.generate, undefined);
            return [
                    {
                      hd: [
                        username,
                        priv
                      ],
                      tl: param[0]
                    },
                    Curry._3(CredSet.add, derive_in_group(priv), [
                          match[2],
                          username
                        ], param[1])
                  ];
          }), [
          /* [] */0,
          CredSet.empty
        ], ids);
    var serialize = function (param) {
      var match = param[1];
      return Curry._1(G.to_string, param[0]) + ((
                implicit_weights ? "," : Curry._1(Stdlib__Printf.sprintf(/* Format */{
                            _0: {
                              TAG: /* Char_literal */12,
                              _0: /* ',' */44,
                              _1: {
                                TAG: /* String */2,
                                _0: /* No_padding */0,
                                _1: /* End_of_format */0
                              }
                            },
                            _1: ",%s"
                          }), Belenios_core__Common_types.Weight.to_string(match[0]))
              ) + Curry._1(Stdlib__Printf.sprintf(/* Format */{
                        _0: {
                          TAG: /* Char_literal */12,
                          _0: /* ',' */44,
                          _1: {
                            TAG: /* String */2,
                            _0: /* No_padding */0,
                            _1: /* End_of_format */0
                          }
                        },
                        _1: ",%s"
                      }), match[1]));
    };
    var serialize_public = function (param) {
      return Curry._1(G.to_string, param[0]) + (
              implicit_weights ? "" : Curry._1(Stdlib__Printf.sprintf(/* Format */{
                          _0: {
                            TAG: /* Char_literal */12,
                            _0: /* ',' */44,
                            _1: {
                              TAG: /* String */2,
                              _0: /* No_padding */0,
                              _1: /* End_of_format */0
                            }
                          },
                          _1: ",%s"
                        }), Belenios_core__Common_types.Weight.to_string(param[1][0]))
            );
    };
    var bindings = Curry._1(CredSet.bindings, match[1]);
    return {
            priv: Curry._1(Belenios_core__Common.List.rev, match[0]),
            public: Curry._2(Belenios_core__Common.List.map, serialize_public, bindings),
            public_with_ids: Curry._2(Belenios_core__Common.List.map, serialize, bindings)
          };
  };
  return {
          derive: derive,
          generate: generate
        };
}

export {
  Make ,
  generate_ids ,
}
/* Belenios__Group Not a pure module */
