// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib__List from "melange/./list.js";
import * as Stdlib__Array from "melange/./array.js";
import * as Belenios_core__Common from "../../../lib/core/common.js";
import * as Belenios_platform__Platform from "../../../../../belenios_platform_melange/platform.js";
import * as Belenios_tool_common__Random from "../../../common/tool/random.js";
import * as Belenios_core__Serializable_j from "../../../lib/core/serializable_j.js";
import * as Belenios_tool_common__Tool_credgen from "../../../common/tool/tool_credgen.js";
import * as Belenios_tool_common__Tool_tkeygen from "../../../common/tool/tool_tkeygen.js";
import * as Belenios_tool_common__Tool_election from "../../../common/tool/tool_election.js";
import * as Belenios_tool_common__Tool_mkelection from "../../../common/tool/tool_mkelection.js";

var P = {
  group: "BELENIOS-2048",
  version: 1
};

function generate_token(param) {
  var X = Belenios_core__Common.MakeGenerateToken(Belenios_tool_common__Random);
  return Curry._2(X.generate_token, 14, undefined);
}

function generate_trustee(param) {
  var R = Belenios_tool_common__Tool_tkeygen.Make(P, Belenios_tool_common__Random, {});
  var kp = Curry._1(R.trustee_keygen, undefined);
  var my_trustee_key = Belenios_core__Serializable_j.trustee_public_key_of_string(Belenios_platform__Platform.read_json, kp.pub);
  var my_trustee = {
    NAME: "Single",
    VAL: my_trustee_key
  };
  return [
          kp.priv,
          Belenios_core__Serializable_j.string_of_trustees(Belenios_platform__Platform.write_json, {
                hd: my_trustee,
                tl: /* [] */0
              })
        ];
}

function make_election(name, description, options, trustees) {
  var question_body_q_blank = false;
  var question_body = {
    q_answers: options,
    q_blank: question_body_q_blank,
    q_min: 0,
    q_max: 1,
    q_question: "Best"
  };
  var question = {
    TAG: /* Homomorphic */0,
    _0: question_body
  };
  var questions = [question];
  var template = {
    t_description: description,
    t_name: name,
    t_questions: questions,
    t_administrator: undefined,
    t_credential_authority: undefined
  };
  var uuid = generate_token(undefined);
  var template$1 = Belenios_core__Serializable_j.string_of_template(template);
  var get_trustees = function (param) {
    return trustees;
  };
  var R = Belenios_tool_common__Tool_mkelection.make({
        version: 1,
        uuid: uuid,
        group: "BELENIOS-2048",
        template: template$1,
        get_trustees: get_trustees
      });
  return Curry._1(R.mkelection, undefined);
}

function make_credentials(uuid, n) {
  var R = Belenios_tool_common__Tool_credgen.Make({
        version: 1,
        uuid: uuid,
        group: "BELENIOS-2048"
      }, Belenios_tool_common__Random, {});
  var ids = Belenios_tool_common__Tool_credgen.generate_ids(n);
  var credentials = Curry._1(R.generate, ids);
  return [
          credentials.public,
          Stdlib__List.map((function (param) {
                  return param[1];
                }), credentials.priv)
        ];
}

function derive_credential(uuid, public_credential) {
  var R = Belenios_tool_common__Tool_credgen.Make({
        version: 1,
        uuid: uuid,
        group: "BELENIOS-2048"
      }, Belenios_tool_common__Random, {});
  return Curry._1(R.derive, public_credential);
}

function encrypt_ballot(election, cred, plaintext, trustees) {
  var PR = {
    raw_election: election,
    trustees: trustees,
    ballots: /* [] */0,
    public_creds: /* [] */0,
    pds: /* [] */0
  };
  var X = Belenios_tool_common__Tool_election.MakeRaw(PR, {});
  return Curry._2(X.vote, cred, plaintext);
}

function compute_encrypted_tally(election, ballots, trustees, public_creds) {
  var PR = {
    raw_election: election,
    trustees: trustees,
    ballots: ballots,
    public_creds: public_creds,
    pds: /* [] */0
  };
  var X = Belenios_tool_common__Tool_election.MakeRaw(PR, {});
  return Curry._1(X.compute_encrypted_tally, undefined);
}

function decrypt(election, ballots, trustees, public_creds, priv_key) {
  var PR = {
    raw_election: election,
    trustees: trustees,
    ballots: ballots,
    public_creds: public_creds,
    pds: /* [] */0
  };
  var X = Belenios_tool_common__Tool_election.MakeRaw(PR, {});
  return Curry._2(X.decrypt, 1, priv_key);
}

function compute_result(election, ballots, trustees, public_creds, partial_decryptions) {
  var PR = {
    raw_election: election,
    trustees: trustees,
    ballots: ballots,
    public_creds: public_creds,
    pds: partial_decryptions
  };
  var X = Belenios_tool_common__Tool_election.MakeRaw(PR, {});
  return Curry._1(X.compute_result, undefined);
}

function genTrustee(param) {
  var match = generate_trustee(undefined);
  return [
          match[0],
          match[1]
        ];
}

var makeElection = make_election;

var encryptBallot = encrypt_ballot;

function makeCredentials(uuid, n) {
  var match = make_credentials(uuid, n);
  return [
          Stdlib__Array.of_list(match[0]),
          Stdlib__Array.of_list(match[1])
        ];
}

var derive = derive_credential;

function decrypt$1(election, ballots, trustees, credentials, privkey) {
  var match = decrypt(election, Stdlib__Array.to_list(ballots), trustees, Stdlib__Array.to_list(credentials), privkey);
  return [
          match[0],
          match[1]
        ];
}

function result(election, ballots, trustees, credentials, a, b) {
  var my_owned_hash = Belenios_core__Serializable_j.owned_of_string(Belenios_core__Serializable_j.read_hash, b);
  var partial_decryptions_0 = [
    my_owned_hash.owned_payload,
    my_owned_hash,
    a
  ];
  var partial_decryptions = {
    hd: partial_decryptions_0,
    tl: /* [] */0
  };
  return compute_result(election, Stdlib__Array.to_list(ballots), trustees, Stdlib__Array.to_list(credentials), partial_decryptions);
}

export {
  P ,
  generate_token ,
  generate_trustee ,
  make_election ,
  make_credentials ,
  derive_credential ,
  encrypt_ballot ,
  compute_encrypted_tally ,
  compute_result ,
  genTrustee ,
  makeElection ,
  encryptBallot ,
  makeCredentials ,
  derive ,
  decrypt$1 as decrypt,
  result ,
}
/* Belenios_core__Common Not a pure module */
