// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Yojson from "../../../../belenios_compat_melange/yojson.js";
import * as Caml_array from "melange.runtime/caml_array.js";
import * as Caml_option from "melange.runtime/caml_option.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Caml_js_exceptions from "melange.runtime/caml_js_exceptions.js";
import * as Belenios_core__Common from "../core/common.js";
import * as Belenios_v1__Election from "../v1/election.js";
import * as Belenios_core__Common_types from "../core/common_types.js";
import * as Belenios_platform__Platform from "../../../../belenios_platform_melange/platform.js";
import * as Belenios_core__Serializable_j from "../core/serializable_j.js";

function get_version(x) {
  var j = Yojson.Safe.from_string(x);
  if (typeof j === "string") {
    return Stdlib.failwith("Election.of_string: invalid data");
  }
  if (j.NAME !== "Assoc") {
    return Stdlib.failwith("Election.of_string: invalid data");
  }
  var match = Curry._2(Belenios_core__Common.List.assoc_opt, "version", j.VAL);
  if (match === undefined) {
    return 0;
  }
  if (typeof match === "string") {
    return Stdlib.failwith("Election.of_string: invalid version");
  }
  var variant = match.NAME;
  if (variant === "Int") {
    return match.VAL;
  } else if (variant === "Float") {
    return match.VAL | 0;
  } else {
    return Stdlib.failwith("Election.of_string: invalid version");
  }
}

function of_string(x) {
  var n = get_version(x);
  if (n !== 1) {
    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                    _0: {
                      TAG: /* String_literal */11,
                      _0: "Election.of_string: unsupported version: ",
                      _1: {
                        TAG: /* Int */4,
                        _0: /* Int_d */0,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: /* End_of_format */0
                      }
                    },
                    _1: "Election.of_string: unsupported version: %d"
                  }), n);
  } else {
    return Belenios_v1__Election.of_string(x);
  }
}

function election_uuid_of_string_ballot(x) {
  var j = Yojson.Safe.from_string(x);
  if (typeof j === "string") {
    return Stdlib.failwith("election_uuid_of_string_ballot: invalid ballot");
  }
  if (j.NAME !== "Assoc") {
    return Stdlib.failwith("election_uuid_of_string_ballot: invalid ballot");
  }
  var match = Curry._2(Belenios_core__Common.List.assoc_opt, "election_uuid", j.VAL);
  if (match !== undefined && !(typeof match === "string" || match.NAME !== "String")) {
    return Belenios_core__Common_types.Uuid.wrap(match.VAL);
  } else {
    return Stdlib.failwith("election_uuid_of_string_ballot: invalid election_uuid");
  }
}

function make_raw_election(params, group, public_key) {
  var n = params.e_version;
  if (n !== 1) {
    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.invalid_arg, /* Format */{
                    _0: {
                      TAG: /* String_literal */11,
                      _0: "make_raw_election: unsupported version: ",
                      _1: {
                        TAG: /* Int */4,
                        _0: /* Int_d */0,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: /* End_of_format */0
                      }
                    },
                    _1: "make_raw_election: unsupported version: %d"
                  }), n);
  } else {
    return Belenios_v1__Election.to_string(params, group, public_key);
  }
}

function MakeResult(X) {
  var write_result = function (param) {
    return Belenios_platform__Platform.write(Belenios_core__Common_types.Election_result.unwrap, param);
  };
  var read_result = function (param) {
    return Belenios_platform__Platform.read((function (param) {
                  return Belenios_core__Common_types.Election_result.wrap(X.S.x, param);
                }), param);
  };
  return {
          write_result: write_result,
          read_result: read_result
        };
}

function has_nh_questions(e) {
  return Curry._2(Belenios_core__Common_types.$$Array.exists, (function (param) {
                if (param.TAG === /* Homomorphic */0) {
                  return false;
                } else {
                  return true;
                }
              }), e.e_questions);
}

function compute_checksums(election, trustees, public_credentials, shuffles, encrypted_tally) {
  var ec_public_credentials = Belenios_core__Common_types.Hash.hash_string(Belenios_core__Serializable_j.string_of_public_credentials(public_credentials));
  var ec_num_voters = Curry._1(Belenios_core__Common.List.length, public_credentials);
  var match = Curry._3(Belenios_core__Common.List.fold_left, (function (param, cred) {
          var max = param[2];
          var min = param[1];
          var total = param[0];
          var i;
          try {
            i = Curry._2(Belenios_core__Common.$$String.index, cred, /* ',' */44);
          }
          catch (raw_exn){
            var exn = Caml_js_exceptions.internalToOCamlException(raw_exn);
            if (exn.RE_EXN_ID === Stdlib.Not_found) {
              return [
                      Belenios_core__Common_types.Weight.$plus(total, Belenios_core__Common_types.Weight.one),
                      min,
                      max
                    ];
            }
            throw exn;
          }
          var n = cred.length;
          var w = Belenios_core__Common_types.Weight.of_string(Curry._3(Belenios_core__Common.$$String.sub, cred, i + 1 | 0, (n - i | 0) - 1 | 0));
          var total$1 = Belenios_core__Common_types.Weight.$plus(total, w);
          var min$1 = min !== undefined ? Caml_option.some(Belenios_core__Common_types.Weight.min(w, Caml_option.valFromOption(min))) : Caml_option.some(w);
          var max$1 = max !== undefined ? Caml_option.some(Belenios_core__Common_types.Weight.max(w, Caml_option.valFromOption(max))) : Caml_option.some(w);
          return [
                  total$1,
                  min$1,
                  max$1
                ];
        }), [
        Belenios_core__Common_types.Weight.zero,
        undefined,
        undefined
      ], public_credentials);
  var max = match[2];
  var min = match[1];
  var w_total = match[0];
  var ec_weights = Belenios_core__Common_types.Weight.is_int(w_total, ec_num_voters) ? undefined : (
      min !== undefined && max !== undefined ? ({
            w_total: w_total,
            w_min: Caml_option.valFromOption(min),
            w_max: Caml_option.valFromOption(max)
          }) : Stdlib.failwith("inconsistent weights in credentials")
    );
  var tc_of_tpk = function (k) {
    var tc_checksum = Belenios_core__Common_types.Hash.hash_string(Yojson.Safe.to_string(k.trustee_public_key));
    var tc_name = k.trustee_name;
    return {
            tc_checksum: tc_checksum,
            tc_name: tc_name
          };
  };
  var trustees$1 = Belenios_core__Serializable_j.trustees_of_string(Belenios_platform__Platform.read_json, trustees);
  var ec_trustees = Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
              if (param.NAME === "Pedersen") {
                return /* [] */0;
              } else {
                return {
                        hd: tc_of_tpk(param.VAL),
                        tl: /* [] */0
                      };
              }
            }), trustees$1));
  var ec_trustees_threshold = Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
              if (param.NAME !== "Pedersen") {
                return /* [] */0;
              }
              var p = param.VAL;
              var ts_trustees = Curry._2(Belenios_core__Common.List.map, (function (param) {
                      var key = param[0];
                      return {
                              ttc_pki_key: Belenios_core__Common_types.Hash.hash_string(param[1].s_message),
                              ttc_verification_key: Belenios_core__Common_types.Hash.hash_string(Yojson.Safe.to_string(key.trustee_public_key)),
                              ttc_name: key.trustee_name
                            };
                    }), Curry._2(Belenios_core__Common.List.combine, Curry._1(Belenios_core__Common_types.$$Array.to_list, p.t_verification_keys), Curry._1(Belenios_core__Common_types.$$Array.to_list, p.t_certs)));
              return {
                      hd: {
                        ts_trustees: ts_trustees,
                        ts_threshold: p.t_threshold
                      },
                      tl: /* [] */0
                    };
            }), trustees$1));
  var names = Curry._1(Belenios_core__Common_types.$$Array.of_list, Curry._1(Belenios_core__Common.List.flatten, Curry._2(Belenios_core__Common.List.map, (function (param) {
                  if (param.NAME === "Pedersen") {
                    return Curry._2(Belenios_core__Common.List.map, (function (x) {
                                  return x.trustee_name;
                                }), Curry._1(Belenios_core__Common_types.$$Array.to_list, param.VAL.t_verification_keys));
                  } else {
                    return {
                            hd: param.VAL.trustee_name,
                            tl: /* [] */0
                          };
                  }
                }), trustees$1)));
  var find_trustee_name_by_id = function (id) {
    if (0 < id && id <= names.length) {
      return Caml_array.get(names, id - 1 | 0);
    }
    
  };
  var process_shuffles = function (shuffles) {
    return Curry._2(Belenios_core__Common.List.map, (function (x) {
                  return {
                          tc_checksum: x.owned_payload,
                          tc_name: find_trustee_name_by_id(x.owned_owner)
                        };
                }), shuffles);
  };
  var ec_shuffles = Belenios_core__Common.let$amp(shuffles, (function (shuffles) {
          return process_shuffles(shuffles);
        }));
  return {
          ec_election: election,
          ec_trustees: ec_trustees,
          ec_trustees_threshold: ec_trustees_threshold,
          ec_num_voters: ec_num_voters,
          ec_weights: ec_weights,
          ec_public_credentials: ec_public_credentials,
          ec_shuffles: ec_shuffles,
          ec_encrypted_tally: encrypted_tally
        };
}

function Make(funarg, funarg$1, funarg$2) {
  var n = get_version(funarg.raw_election);
  var x = n !== 1 ? Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
              _0: {
                TAG: /* String_literal */11,
                _0: "Election.Make: unsupported version: ",
                _1: {
                  TAG: /* Int */4,
                  _0: /* Int_d */0,
                  _1: /* No_padding */0,
                  _2: /* No_precision */0,
                  _3: /* End_of_format */0
                }
              },
              _1: "Election.Make: unsupported version: %d"
            }), n) : Belenios_v1__Election.Make;
  return Curry._4(x, MakeResult, funarg, funarg$1, {});
}

export {
  get_version ,
  of_string ,
  election_uuid_of_string_ballot ,
  has_nh_questions ,
  make_raw_election ,
  Make ,
  compute_checksums ,
}
/* Belenios_core__Common Not a pure module */
