// Generated by Melange

import * as Curry from "melange.runtime/curry.js";
import * as Stdlib from "melange/./stdlib.js";
import * as Stdlib__Printf from "melange/./printf.js";
import * as Belenios_v1__Group from "../v1/group.js";

function of_string(version) {
  if (version !== 1) {
    return Curry._1(Stdlib__Printf.ksprintf(Stdlib.failwith, /* Format */{
                    _0: {
                      TAG: /* String_literal */11,
                      _0: "Group.of_string: unsupported version: ",
                      _1: {
                        TAG: /* Int */4,
                        _0: /* Int_d */0,
                        _1: /* No_padding */0,
                        _2: /* No_precision */0,
                        _3: /* End_of_format */0
                      }
                    },
                    _1: "Group.of_string: unsupported version: %d"
                  }), version);
  } else {
    return Belenios_v1__Group.of_string;
  }
}

export {
  of_string ,
}
/* Belenios_v1__Group Not a pure module */
