// Generated by Melange

import * as Stdlib from "melange/./stdlib.js";
import * as Belenios_v1__Trustees from "../v1/trustees.js";

function get_by_version(param) {
  if (param !== 1) {
    return Stdlib.failwith("Trustees.get_by_version: unsupported version");
  } else {
    return Belenios_v1__Trustees;
  }
}

function string_of_combination_error(param) {
  switch (param) {
    case /* MissingPartialDecryption */0 :
        return "a partial decryption is missing";
    case /* NotEnoughPartialDecryptions */1 :
        return "not enough partial decryptions";
    case /* InvalidPartialDecryption */2 :
        return "invalid partial decryption";
    
  }
}

export {
  get_by_version ,
  string_of_combination_error ,
}
/* Belenios_v1__Trustees Not a pure module */
